### ISSUE TITLE
Missing value parameter in effects.base

### ISSUE THREAD

**Issue by Doldol** [Source-Python-Dev-Team/Source.Python#100]
[effects.base line 394](https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/effects/base.py#L394) is missing the `value` parameter ?

I presume it should be (as indicated by doc string):
```python
        self._set_property(prop_name, SendPropType.VECTOR, value)
```

**Comment by satoon101** [comment]
Thank you!
