### ISSUE TITLE
libsqlite3 error linux

### ISSUE THREAD

**Issue by Baster1985** [Source-Python-Dev-Team/Source.Python#110]
Hello
we work on a new script, but theres a big problem when i try to load the script i get a error, its a linux server, but when i load the script on a lokal server (windows) it works perfekt. I tried ipkg install sqlite
on the gameserver but it dosent fix the problem, i send a dev the script when he dont give it a third person
sp load test
[SP] Loading plugin 'test'... 
[SP] Caught an Exception: 
Traceback (most recent call last): 
File '../addons/source-python/packages/source-python/plugins/manager.py', line 71, in __missing__ 
instance = self.instance(plugin_name, self.base_import) 
File '../addons/source-python/packages/source-python/plugins/instance.py', line 82, in __init__ 
self._plugin = import_module(import_name) 
File '../addons/source-python/plugins/test/test.py', line 19, in <module> 
from sqlite3 import dbapi2 as sqlite 
File '../addons/source-python/Python3/sqlite3/__init__.py', line 23, in <module> 
from sqlite3.dbapi2 import * 
File '../addons/source-python/Python3/sqlite3/dbapi2.py', line 26, in <module> 
from _sqlite3 import * 
ImportError: libsqlite3.so.0: cannot open shared object file: No such file or directory 
[SP] Plugin 'test' was unable to be loaded.

**Comment by Baster1985** [comment]
its cs go ;)

**Comment by satoon101** [comment]
If the Linux server is 64-bit, then the 32-bit version of sqlite3 probably needs to be installed on that system.

**Comment by Baster1985** [comment]
Hi, thanks for this answer, I'ask my server supporter if they can do that. I will write here if it solves the problem

**Comment by Ayuto** [comment]
Try copying libsqlite3.so.0 from ../addons/source-python/Python3/plat-linux/ to your base directory (where srcds_linux is located). That's the required version, but somehow the system doesn't find it.

**Comment by Baster1985** [comment]
it works thank you both my support installed sqlite3 and ich put libsqlite3.so.0 at srcds_linux

**Comment by Ayuto** [comment]
I have reopened it, because we need to add the plat-linux directory to RPATH. This will remove the requirement of either copying our file or installing the file.
