### ISSUE TITLE
New Menu Type: PagedList

### ISSUE THREAD

**Issue by Frag1337** [Source-Python-Dev-Team/Source.Python#113]
A new popup class for generating popups listing the contents of long lists that have no need to make the list items selectable menu items. Normally 10 items per page are listed; for lists that contain more items than this, additional pages are automatically created and page navigation is provided to the user.

Screen:
![ss 2016-03-06 at 06 41 58](https://cloud.githubusercontent.com/assets/9024822/13648956/9bbbc002-e63b-11e5-8ef9-5e1d044a351b.jpg)

Attributes could be:
items_per_page = 10 (default)

**Comment by satoon101** [comment]
Maybe this could even have an argument/attribute for whether or not to show the count on the left.

**Comment by Frag1337** [comment]
Any news about this?

**Comment by Ayuto** [comment]
Unfortunately, I haven't had time to work on that. If you really need this feature, you can use something like this for now:
```
from menus import PagedMenu
from menus import PagedOption

class ListMenu(PagedMenu):
    def __init__(
            self, data=None, select_callback=None,
            build_callback=None, description=None,
            title=None, top_separator='-' * 30, bottom_separator='-' * 30,
            fill=True, parent_menu=None, items_per_page=10):
        super().__init__(data, select_callback, build_callback, description,
            title, top_separator, bottom_separator, fill, parent_menu)
        self.items_per_page = items_per_page

    def _get_max_item_count(self):
        return self.items_per_page

class ListOption(PagedOption):
    def __init__(self, text, highlight=True):
        super().__init__(text, None, highlight, False)


# Test
menu = ListMenu(
    title='[Char Ranks]' + ' ' * 8,
    top_separator=' ',
    bottom_separator=' '
)

for x in range(100):
    menu.append(ListOption('Option {0}'.format(x), highlight=False))

menu.send()
```
