### ISSUE TITLE
Wont load source python.

### ISSUE THREAD

**Issue by razqed** [Source-Python-Dev-Team/Source.Python#115]
So when i try launching my CS:GO server, running on linux i get this error:

[Source.Python] Loading...
[SP-LOADER] Could not load library: Python3/plat-linux/libpython3.5m.so.1.0
[SP-LOADER] Error Reported: /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.17' not found (required by /home/tcagame/guld68/11405/csgo/addons/source-python/Python3/plat-linux/libpython3.5m.so.1.0)
Failed to load plugin "addons/source-python"

i also tried moving "libpython3.5m.so.1.0" to the main folder as suggested by someone, that really didnt change anything though, help would be very highly appreciated, thanks.

**Comment by Ayuto** [comment]
Ah, the old GLIBC issue. :)

I will take a look at it at the weekend. Which version do you have installed? You can check the version by running the following command:
```
ldd --version
```

**Comment by razqed** [comment]
haha oh dear, when it comes to stuff like this you might aswell be asking a monkey, where exactly do i run that command?

**Comment by Ayuto** [comment]
You would run the command within a terminal. But nvm I was just curious.

**Comment by razqed** [comment]
Ah okay, i be able to fix this by running an earlier version or something?

**Comment by Ayuto** [comment]
It would run fine if 2.17 is installed. However, I think I'm simply going to ship the required version with SP.

**Comment by razqed** [comment]
Which build would 2.17 be? I'm not really the sharpest tool when it comes to this..

**Comment by Ayuto** [comment]
Ah, you are talking about the SP build? I'm talking about the GLIBC version, which is a Linux library and does not have anything to do with SP. SP just relies on that library. There are old SP builds which rely on an older version of GLIBC (I think it was 2.13). But they are old builds and you should just give me 1 or 2 days to fix this issue.

**Comment by razqed** [comment]
Ahhhhhh, haha woops, yeah i'll just let you have it then, if you could write here when it's done I'd really appreciate it, thanks.

**Comment by razqed** [comment]
Hey do you perhaps have an update on the issue?

**Comment by Ayuto** [comment]
You will receive a GitHub notification when the issue has been resolved.

**Comment by Ayuto** [comment]
I have started a new branch to test a few changes I made. To apply these changes please do the following steps:

1.
Download and copy libc.so.6 to ``../addons/source-python/Python3/plat-linux/``. You can download the required version from here (click on the "Raw" button):
https://github.com/Source-Python-Dev-Team/Source.Python/blob/shipping_glibc/addons/source-python/Python3/plat-linux/libc.so.6

2.
Replace the old source-python.so in ``../addons/`` with the new version which you can download from here:
http://build.affecta.net/job/Source.Python%20-%20Other%20Branches/game=csgo,label=master/lastSuccessfulBuild/artifact/src/Builds/Linux/csgo/

**Comment by razqed** [comment]
I tried applying the changes, i now get this error:

[Source.Python] Loading...

[SP-LOADER] Could not load library: Python3/plat-linux/libc.so.6
[SP-LOADER] Error Reported: /home/tcagame/guld68/11405/csgo/addons/source-python/Python3/plat-linux/libc.so.6: symbol _dl_find_dso_for_object, version GLIBC_PRIVATE not defined in file ld-linux.so.2 with link time reference

Failed to load plugin "addons/source-python"

**Comment by Ayuto** [comment]
Okay, it was worth a try. Another option would be to recompile our Python libraries with an older version of GLIBC. We already did this once with GLIBC 2.13 and Python 3.4.1. However, I don't have the VM anymore which was using the old GLIBC version and I can't downgrade the version of my current system. Thus I need to setup an old system from scratch.

You might simply want to ask your hoster to upgrade the GLIBC version to at least 2.17. And while asking them you could also ask them to tell you the GLIBC version that is currently installed. Upgrading the version should fix the issue and allows me to work with a lower priority on this issue.

**Comment by razqed** [comment]
yeah okay, i'll try asking them about it.

**Comment by Ayuto** [comment]
If you haven't already updated your GLIBC version I would be happy if you could do another test for me. I have now recompiled the Python libraries with GLIBC 2.13.

1. Replace ``core.so`` and ``source-python.so`` with the new versions that are available here:
http://build.affecta.net/job/Source.Python%20-%20Other%20Branches/game=csgo,label=master/lastSuccessfulBuild/artifact/src/Builds/Linux/csgo/

2. Download the python_glibc branch:
https://github.com/Source-Python-Dev-Team/Source.Python/archive/python_glibc.zip

3. Delete the ``../addons/source-python/Python3/`` directory.

4. Copy the ``Python3`` directory from the zip-file to the previously deleted directory.

**Comment by Ayuto** [comment]
GLIBC 2.17 has been added as a minimum requirement.
