### ISSUE TITLE
Radio menu slots not working properly

### ISSUE THREAD

**Issue by jsza** [Source-Python-Dev-Team/Source.Python#116]
I ran into some weird behavior after updating to SP version 303. Running this plugin (TF2, Debian):
```python
from commands.say import SayCommand
from menus import SimpleMenu, SimpleOption


@SayCommand('!menu')
def menu(command, index, team_only):
    menu = SimpleMenu()
    for x in (1, 2, 3, 5, 0):
        menu.append(SimpleOption(x, 'Option {}'.format(x), x))
    menu.send(index)
```

The resulting menu has slots 4 and 6 enabled, but not 5 or 0. 

This commit seems to be the cause, but I've been unable to understand how to fix it: https://github.com/Source-Python-Dev-Team/Source.Python/commit/eb3dbc0fcece3a218e45bc9081eef276af573dc8

**Comment by Ayuto** [comment]
Thanks for reporting! I have reverted the commit.
