### ISSUE TITLE
I modify the language configuration but file error occurred .

### ISSUE THREAD

**Issue by 2389736818** [Source-Python-Dev-Team/Source.Python#118]
Console error log
[Source.Python] Loading...
[Source.Python] Failed to load the main module.
[Source.Python] Could not initialize python.
Failed to load plugin "addons/source-python"
[Source.Python] Unloading...
[Source.Python] Failed to unload the main module.
[Source.Python] Unloaded successfully.
[Source.Python] Plugin did not load properly due to the following error: 
Unloading plugins...

**Comment by Ayuto** [comment]
Could you please post the full log and the content of the config file?

**Comment by 2389736818** [comment]
source-python.2016-04-23.log

04-23-2016 00:26:27 - sp	-	MESSAGE
	[Source.Python] Plugin did not load properly due to the following error:
04-23-2016 00:26:27 - sp	-	DEBUG
	Unloading plugins...
04-23-2016 00:50:35 - sp	-	MESSAGE
	[Source.Python] Plugin did not load properly due to the following error:
04-23-2016 00:50:35 - sp	-	DEBUG
	Unloading plugins...

**Comment by Ayuto** [comment]
And the content of the config file?

**Comment by Ayuto** [comment]
Closed due to no response.
