### ISSUE TITLE
Pass the whole player instance to a menu instead of only his index

### ISSUE THREAD

**Issue by Mahi** [Source-Python-Dev-Team/Source.Python#131]
## Suggestion

Instead of menu instances receiving the player's `index` like they currently do when you use `send()`:

    my_menu.send(player.index)

I suggest it should receive the whole player and internally handle the sending with `player.index`:

    my_menu.send(player)

## Reasoning/Current Issue

If you subclass `players.entity.Player` and add an attribute to its instances inside of  the `__init__()`:

    class MyPlayer(players.entity.Player):
        def __init__(self, *args, gold=0, **kwargs):
            super().__init__(*args, **kwargs)
            self.gold = gold

You can no longer use this class like you could with SP's `Player`, where you simply create the instance with `player = Player(index)` every time you need to access it (not that you should do that with SP's `Player` either though). The reason it **can't** be used in the subclass is due to `gold` being reset for the new instance, instead of remembering the old one's value:

    >>> my_player = MyPlayer(my_index, gold=500)
    >>> my_player_again = MyPlayer(my_index)
    >>> print(my_player.gold, my_player_again.gold)
    500 0

This means that I can not create the player instance in the menu's `build_callback` nor `select_callback` if my menu needs to access the `gold` attribute.

## Current workarounds

There are a few workarounds for this, none of which I believe to be the "correct" way:

1. Cache the custom `Player` class's attributes into an external dictionary to allow the functionality of creating a new instance every time you need to use it. This makes very little sense, and instead I believe `PlayerDictionary` should be used to store the instances for later use.
2. Have a separate file for project-wide global variables, and add the `PlayerDictionary` instance there so it can be accessed from anywhere. Not really a good solution either, global variables usually lead to nothing good, and I would prefer not to have to create a separate file with just one line *just* because menus don't support players.
3. Have all of the menus defined in the main file where your global `PlayerDictionary` is also contained. Just no.

None of these really appeal to me, and they break many good coding rules and conventions. This leaves me with one last option: create a custom menu class/subclass the existing one. But if this is the "correct" solution, why not just make the custom menu class the default one for SP?

## Issues with the suggested functionality

This will greatly harm those who *don't* need to store their players, or don't even need to access the player's entity inside their menus. They would have to create a player entity where they don't really need it.

**Comment by invincibleqc** [comment]
Even if the send method would accept a Player instance and internally send the menu to its index, it would have to internally cache the given player instance and retrieve it back from the index once the selection command gets called: https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/menus/queue.py#L258

I really don't think this is something the API should take care of - storing objects you want to associate with indexes is your responsability.

**Comment by Mahi** [comment]
To be honest, I believe the whole menu system should be reworked -- maybe there's a better solution in general that would fix this issue too.

> I really don't think this is something the API should take care of - storing objects you want to associate with indexes is your responsability.

Isn't this quite the opposite of what API is supposed to do? As far as I've understood, API usually provides proper and easy wrapper around system calls (in this case Game engien though) without the API's user having to worry how the system works internally.

**Comment by invincibleqc** [comment]
> To be honest, I believe the whole menu system should be reworked -- maybe there's a better solution in general that would fix this issue too.

Well, this is _not_ even an issue... :confused:

> Isn't this quite the opposite of what API is supposed to do? As far as I've understood, API usually provides "proper" and easy wrapper around system calls (in this case game engine calls) without the API's user having to worry how the system works internally.

And this is exactly what the menu package does. I really don't see where the workarounds you listed above are breaking coding rules/conventions. Actually, implementing that callbacks could either be called with an index or a Player instance IS what would break coding rules/conventions. To be honnest, I'm not even sure where this is related to the menu package to begin with. Again, associating objects with indexes is your reponsability and should be done in your code, not in the API.

**Comment by Mahi** [comment]
The menu system is very limited and allows no custom data to be passed to the build and select callbacks, forcing the user to use global variables. That honestly is breaking some conventions.

I believe the API should be flexible enough to *at least* allow me to use my own player class instead of the built-in one, but as mentioned, I believe the whole system should be reworked.

**Comment by Ayuto** [comment]
> Isn't this quite the opposite of what an API usually does? As far as I've understood, API normally provides "proper" and easy wrapper around system calls (in this case game engine calls) without the API's user having to worry about how the system works internally.

What you describe is a facade.

I agree with L'In20Cible that the caching part should be up to the user and not to the menus package.

**Comment by satoon101** [comment]
I don't believe this to be an issue, either.  The current implementation works for the vast majority of use-cases, including your's, technically.

Are there supposed to be multiple instances of your MyPlayer object with different values for gold?  If so, that seems very odd to me, and of course you are going to run into issues.  If not, and you are already storing your MyPlayer objects in a dictionary, how does anyone retrieve that specific object with that specific amount of gold in any other event/callback?  If there is no possibility for this, it would seem to be an overall issue with your implementation.

<br />

> 2 . Have a separate file for project-wide global variables, and add the `PlayerDictionary` instance there so it can be accessed from anywhere. Not really a good solution either, global variables usually lead to nothing good, and I would prefer not to have to create a separate file with just one line *just* because menus don't support players.

I don't understand why this would require specifically having a separate file for all project global variables.  Couldn't use modularize your plugin properly to have specific global variables in modules that make sense for each global variable?  Why would there have to be __one__ file for all of them?  And global variables, especially dictionaries and other containers, are great.  Not sure why you would be so against them.

**Comment by Mahi** [comment]
The current implementation revolves around everything being able to be done in `build_callback` and `select_callback` without receiving anything but the menu instance itself as well as `player_index`. This is extremely limited design with absolutely no benefit over a more OOP approach (each player gets sent an own menu instance), and while it's easy to just subclass my own menu class to fix this, I don't see why such subclass isn't the default menu class.

> Are there supposed to be multiple instances of your MyPlayer object with different values for gold?

No, of course not! But that's what ends up happening if I use the `player = MyPlayer(index)` every time I want to use the player. Which is why using that is not an option, and instead I "have to" (it's a good thing, it's what we should be using) use a `PlayerDictionary` instance.

> If not, and you are already storing your MyPlayer objects in a dictionary, how does anyone retrieve that specific object with that specific amount of gold in any other event/callback? If there is no possibility for this, it would seem to be an overall issue with your implementation.

The event callbacks are in the main file, along with the player dictionary. And it kind of makes sense to be this way imo. However, I don't want to ram my 1000 lines of menu code into the main file just because that's where my player dictionary is (and that's where it should be, unlike the menu code). The other modules are usually supposed to contain functions and classes, which are then instantiated and used in the main file. Which is what I'm doing, except with the current system I can't create my menus in an outside file since that file doesn't have access to my main file's player dictionary.

> I don't understand why this would require specifically having a separate file for all project global variables. Couldn't use modularize your plugin properly to have specific global variables in modules that make sense for each global variable? Why would there have to be one file for all of them?

Since I can't access the player dictionary in my main file from my menu file, and I don't want to move my menu content into my main file, it forces me to move the player dictionary into a separate file to a project-wide global variable. And player dictionary makes sense in the main module, it would make very little sense in the menus module.

> And global variables, especially dictionaries and other containers, are great. Not sure why you would be so against them.

How so? They lead to nothing but bugs and are highly frowned upon in the programming community (stackoverflow, programmers.stackexchange, r/programming, r/python, r/learnpython, dreamincode.net to mention a few). Unittesting is nearly impossible with global variables. The code is much harder to read and follow since not everything is located in the local namespace. You're no longer sure which is changed from where since multiple things are accessing the stuff simultaneously (although less of a problem with player dictionary which is only read).

You can google for more, but it's widely accepted that global variables harm the code and lead to bugs as the project grows:
https://tomnomnom.com/posts/why-global-state-is-the-devil-and-how-to-avoid-using-it
http://programmers.stackexchange.com/questions/148108/why-is-global-state-so-evil
http://stackoverflow.com/a/24501533/2505645
http://www.learncpp.com/cpp-tutorial/4-2a-why-global-variables-are-evil/

**Comment by invincibleqc** [comment]
You could simply use a [factory method](https://en.wikipedia.org/wiki/Factory_method_pattern):

```python
from players.dictionary import PlayerDictionary
from players.entity import Player

class MyPlayer(Player):
    _instances = PlayerDictionary()

    def __init__(self, index, gold=0):
        super().__init__(index)
        self.gold = gold

    @classmethod
    def get_instance(cls, index, *args, **kwargs):
        if index not in cls._instances:
            cls._instances[index] = cls(index, *args, **kwargs)
        return cls._instances[index]```

```python
x = MyPlayer.get_instance(1, 500)
print(x.gold) # 500
y = MyPlayer.get_instance(1)
print(y.gold) # 500
```

**Comment by Mahi** [comment]
That is a very possible workaround, but it still doesn't mean the menus work in an optimal way, since it's forcing me to have a separate `get_player()` function and store the global state under one of my classes in a non-main module. This issue is (at least was meant to be) about updating the menu system, although originally I might've been too specific on how to update it; passing player instead of `player_index` is just a patch for *my* issue, I believe something more generic should be done.

**Comment by invincibleqc** [comment]
In my opinion, nothing need to be done. You need to understand that we are wrapping an existing API and that adding unecessary steps (such as storing the objects associated with the indexes) is... well... unecessary. I will try to picture the whole thing differently. If I have the following code:

```python
def some_function(some_argument):
    pass

some_function(some_object.some_value)
```

Since I cannot access some_object from some_argument into the some_function call, does that means python is unflexible? That is basically what is argued here. :confused:

**Comment by Mahi** [comment]
You must've misunderstood something. I'm not suggesting to store the objects associated with their indexes, nor am I suggesting the API to do any extra steps. I'm suggesting to change the API structure so that external data can easily be passed to the menus. I'm thinking of a more general approach, where the `__init__()` is taken full use of, and each player gets his own menu instance. `select_callback` and `build_callback` are no longer callbacks, but overriddable methods. This way *my* problem would be solved by passing the `player` to the `__init__()`, storing it there (and forwarding rest of the arguments to the base class), and later having access to it in the overridable build and select methods.

I'm already working on a PR, although it might take a few days to wrap my head around a proper structure.

**Comment by Ayuto** [comment]
There you go!
```
class MyPagedMenu(PagedMenu):
    player_cache = PlayerDictionary(YourPlayerClass)

    def __init__(self, **wkargs):
        super().__init__(
            select_callback=self.select_callback,
            build_callback=self.build_callback,
            **kwargs)
            
    @staticmethod
    def select_callback(self, index, option):
        return self.on_select(self.player_cache[index], option)
    
    @staticmethod    
    def build_callback(self, index):
        self.on_build(self.player_cache[index])
        
    def on_select(self, player, option):
        # Overwrite this method
        pass
        
    def on_build(self, player):
        # Overwrite this method
        pass
```

**Comment by Mahi** [comment]
Yes, that works, although I'd use `__init__()` like this since it makes very little sense for the `player_cache` to be stored by the menus:

    def __init__(self, player, *args, **kwargs):
        super().__init__(
            *args, **kwargs,
            select_callback=self.select_callback,
            build_callback=self.build_callback,
    )
    self.player = player

 But as mentioned in the original issue:

> None of these really appeal to me, and they break many good coding rules and conventions. This leaves me with one last option: create a custom menu class/subclass the existing one. But if this is the "correct" solution, why not just make the custom menu class the default one for SP?
