### ISSUE TITLE
WCGO Problems On CS:S and CS:GO

### ISSUE THREAD

**Issue by StewDawg** [Source-Python-Dev-Team/Source.Python#135]
Hello, I'm not quite familiar with some of the newer types of WCS, such as WCGO, but I am quickly learning considering I have been away from the "server modding" for quite a while. Well, when I manually type "sp load wcgo" in either CS:S or CS:GO, in my _run.bat_ file (my server start up), I get:
sp load wcgo
[SP] Loading plugin 'wcgo'...

[SP] Caught an Exception:
Traceback (most recent call last):
  File '..\addons\source-python\packages\source-python\plugins\manager.py', line 75, in __missing__
    instance = self.instance(plugin_name, self.base_import)
  File '..\addons\source-python\packages\source-python\plugins\instance.py', line 82, in __init__
    self._plugin = import_module(import_name)
  File '..\addons\source-python\plugins\wcgo\wcgo.py', line 30, in <module>
    import wcgo.menus
  File '..\addons\source-python\plugins\wcgo\menus\__init__.py', line 4, in <module>
    from wcgo.menus.main import main_menu
  File '..\addons\source-python\plugins\wcgo\menus\main.py', line 10, in <module>
    import wcgo.player
  File '..\addons\source-python\plugins\wcgo\player.py', line 23, in <module>
    class Player(easyplayer.EasyPlayer):

AttributeError: module 'easyplayer' has no attribute 'EasyPlayer'

[SP] Plugin 'wcgo' was unable to be loaded.

I have the latest version of python, SQLite, and I have the newest versions of WCGO, Easyplayer, and Source-Python. It isn't quite adding up in my head for some reason. Kind of missing the easy way of WCS on CSS already haha. Anyone have any solutions?

Thanks

**Comment by invincibleqc** [comment]
I've reported to @Mahi that the directory structure of his package was not correct but he didn't seems to care at all: https://github.com/Mahi/EasyPlayer/issues/8

The "easyplayer" directory need to be placed in the "..\addons\source-python\packages\custom" folder, not into "addons" like the structure of the repo suggests.

However, this is not an issue related to Source.Python so please, post your further issues to them: https://github.com/Warcraft-GO-Team/Warcraft-GO

**Comment by Mahi** [comment]
You should download EasyPlayer from the releases page: https://github.com/Mahi/EasyPlayer/releases @StewDawg

**Comment by invincibleqc** [comment]
Meanwhile, I've edited my post as the issue is not related to the installation.
