### ISSUE TITLE
Add the possibility to grant anonymous players permissions

### ISSUE THREAD

**Issue by Ayuto** [Source-Python-Dev-Team/Source.Python#148]
Add the possibility to grant anonymous players/everyone permissions.

This is useful when e. g. a plugin defines a permission for a command, but the server owner wants that everyone is able to use the command.

**Comment by necavi** [comment]
I'll have to check to be certain, but if I recall correctly there is a special group called "guest" that is automaticallu assigned to all players. Anonymous permissions can be assigned to that group.

**Comment by Ayuto** [comment]
I have never seen that guest group in the auth code. But yeah, that's how we should do that.
