### ISSUE TITLE
CS:GO Linux Server Crash when trying to get players velocity OnEndTouch

### ISSUE THREAD

**Issue by Frag1337** [Source-Python-Dev-Team/Source.Python#150]
Hey,   
  
Im having a Crash Issue on CS:GO, where the server crashes when im trying to get players velocity OnEndTouch

```python
from listeners import OnEntityOutput
from players.entity import Player

@OnEntityOutput
def endTouch(output_name, activator, caller, value, delay):
    if output_name == 'OnEndTouch' and caller.classname == 'trigger_multiple':
        if activator.classname == "player":
            leaveZone(activator.index)

def velocity_3d(index):
    velocity = Player(index).velocity
    return velocity
	
def leaveZone(index):
    print(velocity_3d(index))
    print(velocity_3d(index).length)
    leaveZoneVelocity = velocity_3d
```

`----------------------------------------------  
CRASH: Thu Aug 18 17:21:18 CEST 2016    
Start Line: ./srcds_linux -game csgo -lan 0 -console -usercon -maxplayers 16 -port XXXXX -tickrate 66    +login anonymous +net_public_adr XX.XXX.XX.XX -ip XX.XXX.XX.XX  +game_type 3 +game_mode 0    +map surf_beginner -authkey XXXXXXXXXXXXXXXXXXXXX -debug   
[New LWP 18912]   
[New LWP 18917]   
[New LWP 18929]   
[New LWP 18913]   
[New LWP 18933]   
[New LWP 18920]   
[New LWP 18921]   
[New LWP 18927]   
[New LWP 19020]   
[New LWP 19134]   
[New LWP 18923]   
#0  0xacae5787 in ?? ()   
End of Source crash report 
----------------------------------------------`

```
Vector(-1.1000000085914508e-05, 260.0, -6.25)
PreMinidumpCallback: updating dump comment
crash_20160928230924_1.dmp[6819]: Uploading dump (out-of-process)
/tmp/dumps/crash_20160928230924_1.dmp
Segmentation fault (core dumped)
BFD: Warning: /home/kd10095/server/csgo_1636/core is truncated: expected core file size >= 435507200, found: 1122304.
Cannot access memory at address 0xb776c91c
Cannot access memory at address 0xb776c918
debug.cmds:1: Error in sourced command file:
Cannot access memory at address 0xbf8d6914
email debug.log to linux@valvesoftware.com
Wed Sep 28 23:17:52 CEST 2016: Server restart in 10 seconds
```
   
You can use any map which has a trigger_multiple in it, I have tested it with http://europe-surf.de/csgo/maps/surf_aircontrol_ksf.bsp.bz2 (Leave the start platform) or just create a brush trigger and it does the same.

**Comment by invincibleqc** [comment]
Your code is wrong.

→ In your `endTouch` callback, `index` is never defined.
→ In your `leaveZone` function, `velocity_3d` is never called.

However, I'm not sure using the output is the way to go. What about the following code:

```python
from entities.entity import BaseEntity
from entities.hooks import EntityPreHook
from memory import make_object
from players.entity import Player

@EntityPreHook(EntityCondition.is_player, 'end_touch')
def pre_end_touch(stack_data):
    entity = make_object(BaseEntity, stack_data[1])
    if entity.classname != 'trigger_multiple':
        return
    player = make_object(Player, stack_data[0])
    print("{}'s velocity is: {}".format(player.name, player.velocity))
```

**Comment by Frag1337** [comment]
Oh no! I havent checked the code, I just pasted the wrong one from my other server I wasnt using. 

First of all:

I completly use the function in other way, which means Im calling instead of leaveZone(), the player class which has "self.velocity_3d" in it. But I rather just wanted to replicate the issue. Its just a "listener" which fires "self.onEndTouch" from the players player class. Im currently not at home that I can give you the fixed version, but you can probably just fix the syntax and import errors and test it on CS:GO Linux. It should crash after EndTouch & velocity_3d is called.

Can give you debug.log too if needed.

**Comment by invincibleqc** [comment]
I didn't test but, I assume that the crash is caused cause you pass around an object that get freed at some point. What if you return a copy of the vector?

```python
def velocity_3d(index):
    velocity = Vector(*PlayerEntity(index).velocity)
    return velocity
```

**Comment by Frag1337** [comment]
So I have first of all updated the Code in the first post: 
It succesfully crashes the server when leaving a Zone. Its only on CS:GO Linux. Tested it on CS:S Windows/Linux and CS:GO Windows. CS:GO linux crashes. Added debug.log and console output.

To your last post question:

Still crashes after I replaced it.

**Comment by Ayuto** [comment]
Instead of ``print(velocity_3d(index).length)`` try ``print(velocity_3d(index).length_sqr ** 0.5)``. Vector.length uses a different implementation in CS:GO than CS:S, which should speed up the calculation. However, it seems like the hook doesn't like this speed up on Linux.

**Comment by Frag1337** [comment]
Is this now a bug which will get fixed from Source.Python's side or do I need to fix this with my code by getting os & game?

Thank you for taking time to resolve my problem.

**Comment by Ayuto** [comment]
At first I would like to know if this works for you as well.
