### ISSUE TITLE
Source.Python load error .

### ISSUE THREAD

**Issue by 2389736818** [Source-Python-Dev-Team/Source.Python#152]
Console
[Source.Python] Loading...
=========================================================================
[SP-LOADER] Could not load library: Python3/plat-win/vcruntime140.dll
[SP-LOADER] (Code: 126) The specified module could not be found.
=========================================================================
Failed to load plugin "addons/source-python"

**Comment by satoon101** [comment]
What game is this for?  Is there any other information you could give us?

**Comment by 2389736818** [comment]
CSGO

**Comment by 2389736818** [comment]
I did not install the system VC++2015，Incomplete vc installation，
Missing file API-ms-win-crt-runtime-l1-1-0.dll .
Thank you . This is not a problem Source.Python.

**Comment by Ayuto** [comment]
I'm actually surprised that you are getting this error, because ``vcruntime140.dll`` is included in Source.Python. Could you please check that ``vcruntime140.dll`` is present in ``../addons/source-python/Python3/plat-win/``?

> I did not install the system VC++2015，Incomplete vc installation

After the installation of VC++ Redistributable 2015 you are not experiencing this issue anymore?

**Comment by 2389736818** [comment]
I downloaded the DLL for VC++2015 ， There is no error. 
Console
[Source.Python] Loading...
[Source.Python] successfully.

**Comment by Ayuto** [comment]
Alright, I will add an installation note to the wiki. I guess the most people aren't experiencing this issue, because they already have a redistributable installed.
