### ISSUE TITLE
get correct weapon name in CSGO

### ISSUE THREAD

**Issue by maduxthemad** [Source-Python-Dev-Team/Source.Python#153]
ive asked something like this a while back in the forums and didnt get an answer. ive encountered the same problem again today, so i wanted to bring it to attention again.

my goal is to read the name of a players weapon. especially for exceptions like usp/p2000,m4a1/m4a1s etc..

ive found, that the most convenient way, might be to expand source pythons' weapon class for csgo to return a weapons name.. 
so ive added to "source-python\weapons\engines\csgo__init__.py":

```
from filters.weapons import WeaponIter

# =============================================================================
# >> CLASSES
# =============================================================================

wn_exceptions = {"models/weapons/v_rif_m4a1_s.mdl":"m4a1_silencer","models/weapons/v_rif_m4a1.mdl":"m4a1","models/weapons/v_pist_223.mdl":"usp_silencer","models/weapons/v_pist_hkp2000.mdl":"p2000","models/weapons/v_pist_revolver.mdl":"revolver","models/weapons/v_pist_deagle.mdl":"deagle","models/weapons/v_pist_cz_75.mdl":"cz75aw","models/weapons/v_pist_fiveseven.mdl":"fiveseven","models/weapons/v_pist_tec9.mdl":"tec9"}
class Weapon(_Weapon):
    """Allows easy usage of the weapon's attributes."""
    def get_name(self):
        """Return the name of the player weapon."""
        name = weapon_manager[self.classname].basename
        if name in ("hkp2000","m4a1"):
            player = self._validate_ammo()
            for weapon in WeaponIter():
                if player.inthandle == weapon.get_property_int("m_hOwner"):
                    if name in weapon.get_property_string_pointer("m_iClassname"):
                        return wn_exceptions[weapon.get_property_string_pointer("m_ModelName")]

        return weapon_manager[self.classname].basename

```

this is not very efficient, but i couldnt find a distinguished int-identifier/handle.. maybe someone with insight into all the sp files, could jump onto this and maybe have a better solution for this issue.. 

testcode:

```
player.active_weapon.get_name()
```

UPDATE:
preferably the "weapon_" prefix could be added into the return in conjunction with "give_named_item"-calls for example

**Comment by maduxthemad** [comment]
if there is no better solution for this. i would know an enhancement : run the weaponiter() loop, that is used for identifying, in a separate listener, only ONCE everytime a weapon is created and immediately set the alias attribute ( the correct weapon name ) in a dictionary with the weapon entity index. this way, we can always call the weapon name, without looping again through weaponinter() it in the Weapon class simply by:
`.get_name(index)`
additionally, clean up the dictionary for destroyed weapons, in an entity.kill listener for faster access

**Comment by satoon101** [comment]
This is something I have been wanting to work on for some time.  I'm just not sure what the best identifier is.  I don't really want to use the model, because it's not reliable as servers can change the model.  I need to do more research, when I have time, to figure out the best way to make this identification.

I will say, in your instance, you don't need that 'for' loop at all.  You are already on the instance of the weapon itself, so I'm not sure why you are looping through all weapons.  You could easily shorten that to:
```python
    def get_actual_weapon_classname(self):
        extra_weapon_models = {
            "models/weapons/v_rif_m4a1_s.mdl": "m4a1_silencer",
            "models/weapons/v_pist_223.mdl": "usp_silencer",
            "models/weapons/v_pist_revolver.mdl": "revolver",
            "models/weapons/v_pist_cz_75.mdl": "cz75aw",
        }
        return extra_weapon_models.get(self.model_name, self.classname)
```

**Comment by maduxthemad** [comment]
valve doesnt allow viewmodel tempering. so on official servers, its ALWAYS reliable until valve changes their policy.

i was LOOPING there to get the players int-handle-property for identification. it only served as demonstration, thats why i said "maybe someone with insight into all the sp files, could jump onto this" it would have been helpful if you said : "self" in this case comes from the import Weapon, which uses' Entity" as its base, wherefor we have access to model_name. ( ive checked this myself know ;) )

**Comment by satoon101** [comment]
I was doing a bit of testing with that property last night.  It seems reliable when using give_named_item.  The only issue would be maps that spawn weapons not updating the property.  I'm not sure if we really care about that, though, as that would be a problem with the map and not SP, if we use something like that.

I'll work on something tonight and probably create a new feature branch for this implementation.

**Comment by maduxthemad** [comment]
well, good catch on noticing that! 
do you know which functions not create that property? 
im pretty sure the server can hook all map functions, so you could probably prehook into the function anyway and just set the property, IF you know the specific functions..

**Comment by satoon101** [comment]
Working on this tonight and adding the new weapons to the data.  However, I noticed something strange.  It seems that the 'ammo_' ConVars that used to be used for the maxammo (reserve ammo values) are no longer used.  I did not test all of them on every weapon, but the 7 I tested had no effect.  I am just going to hard code the ammo values in the data for the time being, as we can't rely on the ConVars anymore, unfortunately.

**Comment by maduxthemad** [comment]
thanks! isnt clip also hardcoded? so it would kinda fit in then..
the only other idea i would have is retreiving ammostats from its datamap when sp loads...

**Comment by satoon101** [comment]
Well, clip values are hardcoded because there is no ConVar for those.  In CS:S (and used to be true in CS:GO), you could use those ConVars (ie ammo_556mm_max) to control the amount of reserver ammo a player would have when purchasing or being given a weapon.  I'm not sure when or why they removed it, but I did not realize they had until last night.  I still need to test the grenade ConVars to see if they still work or not.

Also, as far as the map issue goes, I have not confirmed that it is an issue.  I only realized that it could be one when I created weapons using Entity.create().  I don't have any maps locally that add weapons to them.  If you know of any, could you let me know or even test them yourself to see if the property is being set?

**Comment by maduxthemad** [comment]
okay, ill test mapspawning and feedback here in a bit. 

also what i meant is, that i dont see a problem in manually setting the ammo settings in an .ini in general. (clip,max_clip,reserve,max_reserve) 
as they probably never change anyway on updates. the only update here has to be done if new weapons get added, which only rarely happens ( revolver update )

and if admins want to use different ammo settings on their server, they can always change them anyway? the standard settings only serve for creating a weapon instance with its correct standard values?

**Comment by maduxthemad** [comment]
testing showed, using a point template to spawn "weapon_X" or natively creating a "weapon_X" entity within the map correctly applies the "ItemDefinitionIndex" property. the property type seems to always work when "weapon_" - entities are created.

**Comment by satoon101** [comment]
This should all be completed in #169.  Are we still missing anything?
