### ISSUE TITLE
adding Vector:normalized and Vector:clone to mathlib

### ISSUE THREAD

**Issue by maduxthemad** [Source-Python-Dev-Team/Source.Python#154]
actually i only wanted to request normalized, but realized, that some people might use vector:clone() in some cases. so i want to request both:

clone function:
-> return a vector copy

normalized function:
-> returns a NEW,normalized vector (function math is : vector:clone() / vector:normalize() )

**Comment by KirillMysnik** [comment]
Totally agree on `clone`. Or `copy`, to reflect the way shallow copies of dictionaries are created.

**Comment by invincibleqc** [comment]
Copying a Vector can easilly be done with a single line of code:
```python
from mathlib import Vector

a = Vector(1, 2, 3)
b = Vector(*a)
print(a == b, a is b) # True, False
```
Actually, both requested methods can be done with a single line of code which make me doubt of the need to get them added. The only benefit I can think of, as far as copy/clone is concerned, is to avoid importing Vector to copy an instance received by an external package (from en entity, for example).

**Comment by maduxthemad** [comment]
```
1) a:clone() -> this is cloned instance of Vector a
2) a:normalized() -> this feature returns a cloned fully normalized Vector 
```
the advantages in having these methods in mathlib will be 1) speed 2) cleaner code

@invincibleqc
if you need coding help for this, you can always request me to upload a pastebin

btw:
```python
from mathlib import Vector
a = Vector(1,2,3)
b = a + Vector(0,0,0)
print(a == b, a is b) # True, False
```

**Comment by KirillMysnik** [comment]
@invincibleqc I wonder why Python has `dict.copy` method then when you can just do `dict(original_dict)`. Speed maybe?

**Comment by Ayuto** [comment]
> function math is : vector:clone() / vector:normalize() )

That's not the math. normalize() normalizes the vector inplace, so the original vector is modified. The proper code would look like this:
```c++
Vector Vector::Normalized()
{
    Vector my_copy = *this;
    my_copy.NormalizeInPlace();
    return my_copy;
}
```
I will add those two methods tomorrow.

**Comment by maduxthemad** [comment]
your wrong @Ayuto 
and your also wrong when declaring source pythons .normalize() as "Normalizes the vector." in its mathlib edition. its returning vector length. 

test in using SP:
> vector:clone() / vector:normalize() 

returns the correct value. 

if you need help reworking normalize and normalized or even clone i can help you. but i dont have access to sp's project source files to compile it for anyone.

**Comment by invincibleqc** [comment]
My point here is that methods should be reserved to complex operations that shorten multiple lines into a single call for convenience. Not only wrapping a single line giving it a name. In this case, I really see no benefit to add a normalized method that return a normalized copy. Next we will have to wrap `set` adding an `added` method that copy the set with the added element? I'm not trying to be sarcastic here, just to show how this will never end.

As for speed, I believe it should not be a concern before it become an issue. However, I'm all for a clone/copy method for the reason I stated above; avoiding an import.

**Comment by satoon101** [comment]
> if you need help reworking normalize and normalized or even clone i can help you. but i dont have access to sp's project source files to compile it for anyone.

Instead of offering help, you could always make the change yourself and create a Pull Request.  I'm really not sure what you mean by that last sentence, as you should have access to everything everyone else does.

**Comment by Mahi** [comment]
> if you need help reworking normalize and normalized or even clone i can help you. but i dont have access to sp's project source files to compile it for anyone.

Fork your own copy of Source.Python (through GitHub's SP repository), clone it onto your local machine, make the changes you wish, commit, push, pull request.

**Comment by maduxthemad** [comment]
ty @Mahi for that info - ill follow your steps on my next "pull request" or test it if i find time!
@satoon101 sorry i didnt know about pull request, im farely new to programming. ( i just tried to say, that i cant compile the official sp built )

**Comment by satoon101** [comment]
Ok, no big deal.  For more info on GitHub Pull Requests:
https://help.github.com/articles/about-pull-requests/

**Comment by Ayuto** [comment]
> and your also wrong when declaring source pythons .normalize() as "Normalizes the vector." in its mathlib edition. its returning vector length.

Yes, ``normalize()`` will return the vector's length (before normalizing it), but I told you that it will also normalize the vector inplace. That's why your code is not correct. It would be correct if you would have used the ``length`` property. I will also update the documentation to make that clear.

@Mahi 
Ideally, you also create a new branch for the pull request.

@maduxthemad 
You might also want to take a look at our wiki page: http://wiki.sourcepython.com/contributing/contributing.html
