### ISSUE TITLE
Request: Get Server IP

### ISSUE THREAD

**Issue by Frag1337** [Source-Python-Dev-Team/Source.Python#155]
Hey,  

Could you guys add a way to get the current server ip? I don't like the way to hardcode or use the cvar 'hostip' and im already using

``` python
from engines.server import server
server_port = server.udp_port
```

Thanks

**Comment by invincibleqc** [comment]
What about the `ip` convar?

```python
from cvars import ConVar

ip = ConVar('ip')
print(ip.get_string())
```

**Comment by Frag1337** [comment]
@invincibleqc It would probably work, but for which reason is server.udp_port added then? If you could just use "hostport" "hostname" "hostip" etc.

**Comment by Ayuto** [comment]
> It would probably work, but for which reason is server.udp_port added then?

I simply exposed the whole IServer interface. We can certainly add something like ``get_server_ip``, but it would probably just a wrapper for the code posted by @invincibleqc.
Though, that probably makes sense, because not everyone might know about the ``ip`` convar.

**Comment by invincibleqc** [comment]
We could also add a SERVER_ADDRESS constant to the core package or something like that, as well.

**Comment by Frag1337** [comment]
Any news? :)

**Comment by Ayuto** [comment]
Try this:
```
from urllib.request import urlopen

def get_public_ip():
    return urlopen('http://ip.42.pl/raw').read().decode()
    
print(get_public_ip())
```
