### ISSUE TITLE
entities.dictionary.EntityDictionary's on_automatically_removed will never get called since 6014cd4

### ISSUE THREAD

**Issue by KirillMysnik** [Source-Python-Dev-Team/Source.Python#159]
The issue is in this [listener callback](https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/entities/dictionary.py#L65):
```python
def _on_entity_deleted(self, index):
        """OnEntityDeleted listener callback."""
        # Is the index not in the dictionary?
        if index not in self:

            # No need to go further...
            return

        # Call the deletion callback for the index...
        self.on_automatically_removed(index)

        # Remove the index from the dictionary...
        super().__delitem__(index)
```

Since 6014cd41ddcc02952bcaf6806c2c1eb2a316a9d5 they no longer receive the index.

And even fcca9a058eddd6ee473bafd7894dd1390761fade didn't fix the issue.
It probably fixed the exceptions SP would be throwing, but `on_automatically_removed` will never get called, because the `index` argument will actually contain the `BaseEntity` instance, which is always going to fall to `if index not in self` condition.

**Comment by invincibleqc** [comment]
I have it fixed locally, just quick patched the exception on GitHub before pushing the changes.
