### ISSUE TITLE
Invalid typed command raises exception on plugin load, but prevents the plugin from unloading properly

### ISSUE THREAD

**Issue by KirillMysnik** [Source-Python-Dev-Team/Source.Python#162]
```python
from commands.typed import TypedClientCommand
from core import echo_console
from listeners.tick import Delay


# Let's create a WeakAutoUnload instance
Delay(5, echo_console, "Hey there")


# Now some invalid typed command (it contains spaces)
@TypedClientCommand("some invalid command")
def typed_some_invalid_command(command_info):
    pass
```

Upon `sp plugin load` attempt, you'll get 3 tracebacks. One on the actual `load` attempt, but other belong to the plugin manager when it tries to unload failed plugin. And in 5 seconds you'll get `Hey there` in your server console (to test this, make sure the server is not hibernating).

Long story short, `WeakAutoUnload` instances won't be unloaded due to exception in plugin manager. That's because `TypedClientCommand` tries to validate itself in `_unload_instance`. And that method is called because the command managed to register itself as an `AutoUnload` instance. This means that `some valid command` is checked to be invalid only when **decorating** the actual callback, but not during **instatiating** `TypedClientCommand`.
E.g. the following won't raise anything:
```python
decorator = TypedClientCommand("some invalid command")
```
Although at this point already we can say that the command will be invalid.

**Comment by invincibleqc** [comment]
Fixed with last commits, thank you! 😉
