### ISSUE TITLE
SP loads in console but doesn't work

### ISSUE THREAD

**Issue by rafalolszewskii** [Source-Python-Dev-Team/Source.Python#166]
I've tried to install Source.Python but ended up with failure.

Within my game console i see that SP has been loaded, then it says there's new version, but in-game when I type `sp version` or `print_plugins` it doesn't return any of expected results.

**Comment by invincibleqc** [comment]
The command is `plugin_print` not `print_plugins`. You can download the lastest version [here](http://builds.sourcepython.com/job/Source.Python/lastSuccessfulBuild/) and follow the steps to successfully update on the [wiki](http://wiki.sourcepython.com/general/updating.html). If that still doesn't works for you, thanks to provide more info such as Game, OS, installed plugins (SourceMod, etc) and everything you think could be useful for us to help you.

**Comment by rafalolszewskii** [comment]
My bad, I ment `plugin_print` - which I did in-game.

I'll try updating as soon as I get home today and will report back if help needed.

**Comment by invincibleqc** [comment]
Alright, if updating doesn't work open back this issue.
