### ISSUE TITLE
couldn't connect to the server after installing SP

### ISSUE THREAD

**Issue by fearrr** [Source-Python-Dev-Team/Source.Python#171]
Greetings, friends.
I want to share a problem ...

```
Distro: Ubuntu 16.04.1 LTS
Arch: x86_64
Kernel: 4.4.19-1-pve
Game: CSGO
CSGO server version: 161125
GLIBC required: 2.3.6
Dependencies: bsdmainutils python util-linux tmux lib32gcc1 libstdc ++ 6 libstdc ++ 6: i386 lib32z1
```

**Installed add-ons:**

- Metamod: Source version 1.10.6
- SourceMod Version: 1.8.0.5963
- Emulator Non-Steam (author bir3yk) the latest version

After installing the SP, couldn't connect to the server. 
Server doesn't have messages about connect client

**Client messages**
```
Retrying public(_IP_HERE_) ...
Retrying public(_IP_HERE_) ...
Connection failed after 30 retries.
```

Server Console on the SP commands responds correctly.

`sp version`
`Current Source.Python version: 503`

The logs are OK
```
[Source.Python] Loading ...
[Source.Python] Loaded successfully.
```

**Comment by invincibleqc** [comment]
We won't give any support for non-steam servers.

**Comment by fearrr** [comment]
Thanks for the friendly answer. A good start to explore the new platform.
