### ISSUE TITLE
old ucrtbase.dll!crt_at_quick_exit thread doesnt terminate when reloading sp scripts on server

### ISSUE THREAD

**Issue by maduxthemad** [Source-Python-Dev-Team/Source.Python#177]
see title
using sp load plugin <scriptname> command

**Comment by satoon101** [comment]
Sooooo....is this supposed to be open or closed?

Assuming the answer is open, perhaps you could try providing an example that we can use to replicate this issue.

**Comment by maduxthemad** [comment]
its f closed
