### ISSUE TITLE
GameThread Update

### ISSUE THREAD

**Issue by Frag1337** [Source-Python-Dev-Team/Source.Python#179]
See reference:

http://forums.sourcepython.com/viewtopic.php?p=9612#p9612

Imo it would be good to have an updated and most recent version out of a super GameThread which can be used for http POST or whatever.

Please! :)

**Comment by Ayuto** [comment]
I'm not sure if I really understood the problem. Why can't you use GameThread to create POST requests?

The lag mentioned in that forum thread can be resolved by either creating a worker thread (like suggested) or simply implement a spam protection. Both don't have much to do with the GameThread class.

**Comment by Frag1337** [comment]
And how does a proper GameThread to create POST requests look like, with the most recent version?

**Comment by Ayuto** [comment]
GameThread has never changed since it has been added. It's working exactly like threading.Thread. The only difference is that it has been fixed to run in a SRCDS.
Example 1:
```
from listeners.tick import GameThread

def do_post_request():
    print('YOU POST REQUEST HERE')

thread = GameThread(target=do_post_request)
thread.start()
```

Example 2:
```
from listeners.tick import GameThread

class MyPostRequest(GameThread):
    def run(self):
        print('YOU POST REQUEST HERE')
        
thread = MyPostRequest()
thread.start()
```
