### ISSUE TITLE
Add user message hooking API

### ISSUE THREAD

**Issue by Ayuto** [Source-Python-Dev-Team/Source.Python#180]
The API should allow hooking every user message. Within a hook it should be possible to change all attributes of the user message.

For reference:
http://forums.sourcepython.com/viewtopic.php?f=20&t=1138

**Comment by maduxthemad** [comment]
isnt that exactly what sp is? an api that can hook into user messages?

**Comment by Ayuto** [comment]
One part of SP is to provide an API to create function hooks. But it has no API to easily create user message hooks. 

Currently, plugin authors have to understand how bitbuffers and protobuf work. Moreover, they have to do checks whether the game uses bitbuffers or protobuf for its user messages to properly create the hook. This new API should change that, so hooking and modifying user messages is unified and easy to do.

**Comment by maduxthemad** [comment]
in csgo atleast, most UMs are serverorigin based. so i assume you are thinking of those that clients send to each other? e.g. saytext? i havent looked into it really, but how about a simpler solution like a playerproperty of textcolor etc, that, if set, inits a prehook for saytext with a precoded arg replacement. 

so plugin authors would only have to set player(1).saytext_color = PINK ( simple solution )
or if you really want a global function , player(1).set_UM("saytext",("color"=PINK)) -- UM / kwargs

hope i didnt misunderstand you though.. but i think best would be to point out first with UMs you are thinking of here

**Comment by Ayuto** [comment]
The idea is to make the solutions proposed in this thread easier to use:
http://forums.sourcepython.com/viewtopic.php?f=20&t=1138

However, this is actually just a reminder for the development team, but if you think you got a great implementation, feel free to create a pull request. The forum thread provides all the information you need.

**Comment by maduxthemad** [comment]
u wot m8?

**Comment by maduxthemad** [comment]
yeah i had something similar in mind. but do you really want to do this for all UM's or just saytext ( + some other maybe )? thats why i asked which UM's you are thinking of. maybe start a list open for discussion? i still think the implementation highly depends on that

**Comment by Ayuto** [comment]
All user messages should be implemented. Though, the priority is obviously SayText2.

**Comment by maduxthemad** [comment]
yeah, i see. most common usages for intercepting usrmgsgs i can really think of are these 3 then:
1) blocking ( mostly used )
2) redirecting ( rare cases used )
3) editing ( very rare cases used )

i think naturally usermsgs are not meant to be edited, except for rare cases like textcolor. i mean this really encourages a lot of tempering imo. like serveradmins trolling people. by letting them write users stuff they never said or serverowners adding advertisment into hud msgs etc. this is really just my opinion. i think hooking everything can be useful in rare cases, so maybe concentrate on implementing only those rare cases, like 

textcolor of a player -> create playerproperty with textcolor
chatfilter -> replacing specific swearwords

btw, i have question
> @UserMessageHook('SayText2')
def pre_saytext2(buffer, recipients, chat, msg_name, index, param1, param2, param3, param4):
    param2.set('blabla')

i know this is an example, but where is the sender in the params? is it part of buffer? i think it would be useful to have the sender deserialized here.

**Comment by satoon101** [comment]
UserMessages are sent **to** a client, not being sent **from** one.  The only reason SayText2 involves a client sending is because it is utilized when a player uses `say` or `say_team`.  We could certainly expose the m_iClientCommandIndex value so that plugin developers have access to that in a SayText2 hook.

**Comment by satoon101** [comment]
> i mean this really encourages a lot of tempering imo. like serveradmins trolling people. by letting them write users stuff they never said or serverowners adding advertisment into hud msgs etc.

You can do all of that already.  There is no need for a UserMessage **hook** to do any of that.

**Comment by Ayuto** [comment]
There is no sender. If you want to know who types something in chat, you need to use SayFilter, which is a hook on ``say`` and ``say_team``.

**Comment by satoon101** [comment]
Well, I do see the merit in allowing access to the `say`/`say_team` sender a SayText2 hook itself.  For instance, to add a `tag` to the player's name, like `[Admin] satoon101`.  A SayFilter just doesn't work as well for this as a SayText2 hook would, in my opinion.  I mean, you could `get` the player's index via their name in the first parameter, but that isn't as nice of a way as just providing access to the player's index which is already stored when they send the chat.

**Comment by maduxthemad** [comment]
and thats exactly why i said in the beginning: isnt this what sp already does? if this "usermsg hook" really is going to be an interceptor for every usermsg, i think there will be a lot of wasted pythonbuffer on non-interfered usrmsgs.... thats the whole thing. i see the point of a playerattribute and chatfilter etc, but i think those could be easierly implemented by admins themselfes as satoon also said 

> You can do all of that already. There is no need for a UserMessage hook to do any of that.

**Comment by satoon101** [comment]
While I said you can already do the things you mentioned, that doesn't mean there isn't a need for UserMessage hooks.  SP doesn't hook UserMessages already.  We do hook `say` and `say_team`, but those are server commands, not UserMessages.

And, it will only intercept the ones that are registered to be intercepted.  That's the same way our entity hooks already work.  Only the ones registered to be hooked are hooked.  We will also provide an API to better handle those situations across engines.  Otherwise, plugin developers have to write a lot of extra code to handle both bitbuf and protobuf (which is what they currently have to do).

**Comment by maduxthemad** [comment]
you **have** to know the sender if you are trying to redirect/block messages from within a usermsg. therefor i would suggest the idea of a separate class that that handles any usermsgs initiated from clients via events/listeners(?) ? thats the client to client traffic i talked about in the beginning, because that is what it comes down to right? ( also includes what the client sends to the server and back to self )

isnt voicechat also usrmsg data? redirecting voice traffic was something i wanted to do for a while, and this method could help implement it, if there isnt any other possibility for it yet

**Comment by maduxthemad** [comment]
> And, it will only intercept the ones that are registered to be intercepted. 

but arent usermsgs itself serialized? how do you know who sent it without deserializing each one and checking? the only non-wasting method i could think of is sthn like blocking a player event. like blocking say_team from creating its automated usermsg by itself, and recreating it in a separated class. but for this implementation, specificly targeted usrmsgs must be chosen, right? so this is kinda my confusion..

**Comment by satoon101** [comment]
As far as I know, the only UserMessage that is indirectly sent from a client is SayText2.  And yes, I meant **in**directly, as the client just sends a command to the server, and the server then creates and sends the SayText2 message to the appropriate recipients.

You certainly don't **have** to know the sender.  And SayText2 can be sent by plugins themselves, they don't always come from the `say`/`say_team` server commands.  And again, you can already get the player's index by using [players.helpers.index_from_name](https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/players/helpers.py#L135) with param1.

I'm also fairly certain that voicechat itself is not a UserMessage, though it might involve a UserMessage.  I'm not sure if it's possible, or at least easily done, to add players to the ones receiving the voice chat.  Though, you can already mute certain players for certain other players:
https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/players/_base.py#L427-#L446

There is no need to have separate classes for these, as one API should easily be able to handle all circumstances.  We will just have to figure out whether we want to expose the player's index who used `say`/`say_team`, or whether using the player's name in param1 would suffice.  I definitely don't think we should expose setting that value, only getting it, if we go that route.
<br />
> but arent usermsgs itself serialized? how do you know who sent it without deserializing each one and checking? the only non-wasting method i could think of is sthn like blocking a player event. like blocking say_team from creating its automated usermsg by itself, and recreating it in a separated class. but for this implementation, specificly targeted usrmsgs must be chosen, right? so this is kinda my confusion..

You still seem to be thinking that UserMessages are sent **from** clients, but absolutely none of them are.  Of course, you can already block SayText2 by blocking `say`/`say_team`.  However, doing so can and will block say commands and the player_say event, which will break plugins.  SP already has a way to know if a command is registered as a say command, but we have no way of knowing if a command is registered from SourceMod, or Mani, or any other server plugin that isn't Source.Python.  To fix that issue, and allow for the text itself to be modified and not block the commands, the best thing to do is to hook SayText2 itself and block/modify it.

**Comment by maduxthemad** [comment]
so when a player creates a say_team command, the server creates a usermsg, **that you dont have to deserialize**, but can directly intercept and edit?

**Comment by maduxthemad** [comment]
and for the voicechat thing... i know that the usermsg is not the streaming data, but it could be sthn like an INT that carries the streaming **channel**. and if you can redirect streaming channels thsi way, that would already do the job for me. but i probably have to look a bit deeper into it to get a proper understanding. thanks for trying to make things clearer though!

**Comment by Ayuto** [comment]
Here is a first aproach to address this issue.
```python
# TODO:
# - Implement more user messages
# - Use a dictionary instead of a list (UserMessageData)? That would also make
#   the callbacks more readable as you won't access/modify values via indexes
#   anymore.
# - Integrate all of this into the messages package. Also use the message
#   implementations for the UserMessageCreator subclasses.

# =============================================================================
# >> IMPORTS
# =============================================================================
# Source.Python
from engines.server import engine_server
from filters.recipients import BaseRecipientFilter

from bitbuffers import BitBufferWrite
from bitbuffers import BitBufferRead

from memory import make_object
from memory import get_virtual_function
from memory.hooks import PreHook
from memory.hooks import PostHook

from messages import UserMessage
from messages import get_message_index

if UserMessage.is_protobuf():
    from _messages import ProtobufMessage


# =============================================================================
# >> ALL DECLARATION
# =============================================================================
__all__ = (
    'on_bitbuffer_user_message_created',
    'OnBitBufferUserMessageCreated',
    'on_protobuf_user_message_created',
    'OnProtobufUserMessageCreated',
    'on_user_message_created',
    'OnUserMessageCreated',
    'UserMessageData',
    'UserMessageImpl',
    'SayText2Impl',
    'implemented_usermessages',
    'get_user_message_impl',
)


# =============================================================================
# >> GLOBAL VARIABLES
# =============================================================================
_user_message_data = None

# TODO: Move this to listeners
from listeners import ListenerManager
from listeners import ListenerManagerDecorator

on_bitbuffer_user_message_created = ListenerManager()

class OnBitBufferUserMessageCreated(ListenerManagerDecorator):
    manager = on_bitbuffer_user_message_created


on_protobuf_user_message_created = ListenerManager()

class OnProtobufUserMessageCreated(ListenerManagerDecorator):
    manager = on_protobuf_user_message_created


on_user_message_created = ListenerManager()

class OnUserMessageCreated(ListenerManagerDecorator):
    manager = on_user_message_created


# =============================================================================
# >> CLASSES
# =============================================================================
class UserMessageData(list):
    """A list that keeps track whether it has been modified via __setitem__."""

    def __init__(self, *args):
        super().__init__(args)
        self.changed = False

    def __setitem__(self, index, value):
        super().__setitem__(index, value)
        self.changed = True


class UserMessageImpl(object):
    """Base class for user message implementations."""

    @staticmethod
    def read_protobuf(buffer):
        """Read data from the given buffer.

        :param ProtobufMessage buffer:
            The buffer to read.
        :rtype: UserMessageData
        """
        raise NotImplementedError

    @staticmethod
    def write_protobuf(buffer, *args):
        """Write data to the given buffer.

        :param ProtobufMessage buffer:
            The buffer to write to.
        :param args:
            The arguments that should be written to the buffer.
        """
        raise NotImplementedError

    @staticmethod
    def read_bitbuffer(buffer):
        """Read data from the given buffer.

        :param BitBufferRead buffer:
            The buffer to read.
        :rtype: UserMessageData
        """
        raise NotImplementedError

    @staticmethod
    def write_bitbuffer(buffer, *args):
        """Write data to the given buffer.

        :param BitBufferWrite buffer:
            The buffer to write to.
        :param args:
            The arguments that should be written to the buffer.
        """
        raise NotImplementedError

    @classmethod
    def read(cls, buffer):
        """A wrapper for :meth:`read_protobuf` and :meth:`read_bitbuffer`.

        :param buffer:
            The buffer to read.
        :rtype: UserMessageData
        """
        if UserMessage.is_protobuf():
            return cls.read_protobuf(buffer)

        return cls.read_bitbuffer(buffer)

    @classmethod
    def write(cls, buffer, *args):
        """A wrapper for :meth:`write_protobuf` and :meth:`write_bitbuffer`.

        :param buffer:
            The buffer to write.
        :rtype: UserMessageData
        """
        if UserMessage.is_protobuf():
            cls.write_protobuf(buffer, *args)
        else:
            cls.write_bitbuffer(buffer, *args)


class SayText2Impl(UserMessageImpl):
    """SayText2 implementation."""

    @staticmethod
    def read_protobuf(buffer):
        return UserMessageData(
            buffer.get_int32('ent_idx'),
            buffer.get_bool('chat'),
            buffer.get_string('msg_name'),
            buffer.get_repeated_string('params', 0),
            buffer.get_repeated_string('params', 1),
            buffer.get_repeated_string('params', 2),
            buffer.get_repeated_string('params', 3))

    @staticmethod
    def write_protobuf(buffer, index, chat, message, param1, param2, param3, param4):
        buffer.set_string('msg_name', message)
        buffer.set_bool('chat', chat)
        buffer.set_int32('ent_idx', index)
        buffer.set_repeated_string('params', 0, param1)
        buffer.set_repeated_string('params', 1, param2)
        buffer.set_repeated_string('params', 2, param3)
        buffer.set_repeated_string('params', 3, param4)

    @staticmethod
    def read_bitbuffer(buffer):
        return UserMessageData(
            buffer.read_byte(),
            buffer.read_byte(),
            buffer.read_string(),
            buffer.read_string(),
            buffer.read_string(),
            buffer.read_string(),
            buffer.read_string())

    @staticmethod
    def write_bitbuffer(buffer, index, chat, message, param1, param2, param3, param4):
        buffer.write_byte(index)
        buffer.write_byte(chat)
        buffer.write_string(message)
        buffer.write_string(param1)
        buffer.write_string(param2)
        buffer.write_string(param3)
        buffer.write_string(param4)


implemented_usermessages = {
    get_message_index('SayText2'): SayText2Impl
}

def get_user_message_impl(msg_index):
    """Return the user message implementation for the given message index.

    :raise KeyError:
        Raised if the given user message index is not implemented.
    :rtype: UserMessageImpl
    """
    # TODO: Catch KeyError and throw NotImplementedError?
    return implemented_usermessages[msg_index]


# =============================================================================
# >> HOOKS
# =============================================================================
if UserMessage.is_protobuf():
    @PreHook(get_virtual_function(engine_server, 'SendUserMessage'))
    def pre_message_end(args):
        # No need to do anything behind this if no listener is registered
        if not on_user_message_created and not on_protobuf_user_message_created:
            return

        recipients = make_object(BaseRecipientFilter, args[1])
        message_index = args[2]
        buffer = make_object(ProtobufMessage, args[3])

        on_protobuf_user_message_created.notify(
            recipients, message_index, buffer)

        # No need to do anything behind this if no listener is registered
        if not on_user_message_created:
            return

        try:
            impl = get_user_message_impl(message_index)
        except KeyError:
            return

        data = impl.read(buffer)
        on_user_message_created.notify(message_index, recipients, data)

        # Update buffer if data has been changed
        if data.changed:
            impl.write(buffer, *data)

else:
    @PostHook(get_virtual_function(engine_server, 'UserMessageBegin'))
    def post_user_message_begin(args, return_value):
        # No need to do anything behind this if no listener is registered
        if not on_user_message_created and not on_bitbuffer_user_message_created:
            return

        global _user_message_data
        _user_message_data = (
            make_object(BaseRecipientFilter, args[1]),
            args[2],
            make_object(BitBufferWrite, return_value))

    @PreHook(get_virtual_function(engine_server, 'MessageEnd'))
    def pre_message_end(args):
        # This happens when we initialize our hooks, while a user message is
        # currently being created
        if _user_message_data is None:
            return

        # No need to do anything behind this if no listener is registered
        if not on_user_message_created and not on_bitbuffer_user_message_created:
            return

        recipients, message_index, buffer_write = _user_message_data
        buffer_read = BitBufferRead(buffer_write, False)

        # For bitbuffers we need to make sure every callback starts reading and
        # writing from the very first bit.
        for callback in on_bitbuffer_user_message_created:
            buffer_read.seek_to_bit(0)
            buffer_write.seek_to_bit(0)
            callback(recipients, message_index, buffer_read, buffer_write)

        # No need to do anything behind this if no listener is registered
        if not on_user_message_created:
            return

        try:
            impl = get_user_message_impl(message_index)
        except KeyError:
            return

        buffer_read.seek_to_bit(0)
        data = impl.read(buffer_read)
        on_user_message_created.notify(message_index, recipients, data)

        # Update buffer if data has been changed
        if data.changed:
            buffer_write.seek_to_bit(0)
            impl.write(buffer_write, *data)


# =============================================================================
# >> TEST
# =============================================================================
@OnUserMessageCreated
def my_on_user_message_created(message_index, recipients, data):
    print(message_index, recipients, data)
    data[4] += '123'
    print(data)
```
With this implementation you just need to subclass and implement ``UserMessageImpl`` for the desired user message and then add the implementation to ``implemented_usermessages``.

Any thoughts?

**Comment by Ayuto** [comment]
@satoon101 @invincibleqc @KirillMysnik 
If anyone of you has some spare time, please take a look at this snippet. I would like to get a feedback on this.

**Comment by invincibleqc** [comment]
While it does works and serves its purpose, I don't necessarily think this is a user-friendly implementation as it feels really "raw" to me. In my opinion, scripters should not have to bother registering wrapper classes, or have to compare user message indexes or even ordering fields by indexes themselves. Ideally, all of this should be done internally and callbacks should receives the same object that they use to send messages where they can dynamically write fields by attributes before being processed. Also, having to read all values from the buffers in order to pass a tuple like objects to the callbacks to then re-write the entire buffer if any value changed seems quite redundant. I think an optimal/easy-to-use implementation should looks like something as simple as the following:
```python
from filters.recipients import RecipientFilter
from messages import SayText2

@OnUserMessageCreated('SayText2')
def pre_saytext2(recipients, user_message):
    print isinstance(user_message, SayText2) # Should prints True

    # Here we can change the message field
    if user_message.message == 'foo':
        user_message.message += ' bar'

    # Pretty sure player with index 1 doesn't want to see this non-sense...
    recipients.remove_recipient(1)

saytext2 = SayText2()
saytext2.message = 'foo'
recipients = RecipientFilter(1)
saytext2.send(recipients)
```

**Comment by Ayuto** [comment]
Thanks for your feedback! Your suggestion would indeed be really user friendly. But being able to do something like this ``isinstance(user_message, SayText2)`` would be too much work to implement, imo. I'm fine with the rest.

>Also, having to read all values from the buffers in order to pass a tuple like object to the callbacks to then re-write the entire buffer if any value changed seems quite redundant.

You mean reading/writing values on demand? I don't think that technically feasible for bitbuffers, because you don't know to which bit you need to seek to read/write a value. Also, rewriting a value might require rewriting all values that follow after the value we have written. That can easily happen if the number of bits of the original value is different than the number of bits we have written.

I will update the snippet to implement the following suggestions/TODOs:
* ``@OnUserMessageCreated('SayText2')``
* ``user_message.message``
* ``recipients.remove_recipient(1)`

**Comment by invincibleqc** [comment]
> But being able to do something like this isinstance(user_message, SayText2) would be too much work to implement, imo.

True, could always be any object that carries a "name" and map the attributes with the same names as the original message class. As long as they are mirroring, I see no inconvenient.

> Also, rewriting a value might require rewriting all values that follow after the value we have written. That can easily happen if the number of bits of the original value is different than the number of bits we have written.

Very good point. At least, could worth the effort to make it dynamic for protobuf tho. 😛

**Comment by invincibleqc** [comment]
>Alright, I have updated the code.

Awesome, syntax definitely looks much better! I like the addition of having separated `Bitbuf/Protobuf` listeners; good idea. The main reason being the keybinds into HudHint messages that are not translatable with protobuf so having them separated prevent having to do some engine/game testing, etc. in case we want to strip them off.
