### ISSUE TITLE
Bots don't call OnClientDisconnect on map change

### ISSUE THREAD

**Issue by ThaPwned** [Source-Python-Dev-Team/Source.Python#181]
Well, title. But here's some code to see what I'm talking about:
```python
from listeners import OnClientActive
from listeners import OnClientDisconnect

@OnClientActive
def on_client_active(index):
    print('{0} connected'.format(index))

@OnClientDisconnect
def on_client_disconnect(index):
    print('{0} disconnected'.format(index))
```
Then using `bot_add`, you get `1 connected`. Change the map using `changelevel de_dust2` (or any other map name), and you get `1 connected` once again but no `1 disconnected`.

Here's some info about my setup (from `sp info`, and bot_index is the code above):
```
Date          : 2017-01-31 20:46:15.290783
OS            : Windows-8.1-6.3.9600-SP0
Game          : css
SP version    : 549
Server plugins:
   00: Source.Python, (C) 2012-2016, Source.Python Team.
SP plugins:
   00: bot_index
```
And just because: @Ayuto made me do it.

**Comment by invincibleqc** [comment]
This is not an issue. [OnClientActive](http://wiki.sourcepython.com/developing/module_tutorials/listeners.html#onclientactive) is called when the client is fully connected and ready to receive networkable data while [OnClientDisconnect](http://wiki.sourcepython.com/developing/module_tutorials/listeners.html#onclientdisconnect) is called when the player is disconnecting from the server. During a map change, players are not reconnecting; this would makes no sense if it was called.

**Comment by maduxthemad** [comment]
not sure if this is going to help, but @Event("player_activate") could be something you are looking for

**Comment by satoon101** [comment]
No, he's wanting to be notified when bots **leave** the server, not when they **join**.

This really isn't a 'bug' with SP, as we just forward the ClientDisconnect that is called within the engine itself.  Note that they also don't cause the player_disconnect event to fire, either.  What I primarily do is just clean up after bots in OnLevelEnd.

Though, doing a bit of testing, it does seem that there is a bug in our PlayerDictionary object.  Bots also don't cause the on_entity_deleted_listener_manager to notify when leaving the server during map change.  We might consider using a listener for level end to remove all bots from the dictionary on map change.

**Comment by ThaPwned** [comment]
> This is not an issue. OnClientActive is called when the client is fully connected and ready to receive networkable data while OnClientDisconnect is called when the player is disconnecting from the server. During a map change, players are not reconnecting; this would makes no sense if it was called.

They are reconnecting (kind of) as both OnClientDisconnect and OnClientActive are called for players when `changelevel` is used, as shown below (1 is me, while 2 is the bot):
```
Client "Tha Pwned" connected (192.168.0.10:27006).
1 connected
bot_add
2 connected
status
# userid name                uniqueid            connected ping loss state  adr
#      2 "Tha Pwned"         [U:1:73830190]      00:08       40    0 active 192.168.0.10:27006
#      3 "Mark"              BOT                                     active
changelevel de_dust2
1 disconnected
2 connected
1 connected
status
# userid name                uniqueid            connected ping loss state  adr
#      2 "Tha Pwned"         [U:1:73830190]      00:25       34    0 active 192.168.0.10:27006
#      4 "Ian"               BOT                                     active
```
You'll also notice that it's a completely different bot (even got a new userid) that is now on the server.

SourceMod seems to [handle](https://github.com/alliedmodders/sourcemod/blob/master/core/PlayerManager.cpp#L763) it by hooking either `IServerGameDLL::ServerHibernationUpdate` or `IServerGameDLL::SetServerHibernation` depending on the game.
> This really isn't a 'bug' with SP, as we just forward the ClientDisconnect that is called within the engine itself. Note that they also don't cause the player_disconnect event to fire, either. What I primarily do is just clean up after bots in OnLevelEnd.

Definitely not a problem with SP, however, it'll no doubt help coders, as they don't have to wonder why their stuff "breaks" for bots when the map changes.

**Comment by maduxthemad** [comment]
i dont understand how this listener is needed to avoid breaking in the case of changelevel? can you elaborate on a specific case?

**Comment by invincibleqc** [comment]
Thank you for explaining it better. This is actually an easy patch to implement. I will add a hook on those methods to call the listener for bots. 

I tested PlayerDictionary, and bots are correctly removed on my side (OnEntityDeleted relies on the global entity list, so whenever an entity pointer is freed, listener is called and in theory, hibernation should not affect it). What game did you test on?

**Comment by invincibleqc** [comment]
Lastest build should fix all the issues related to this thread. Please, close this issue once you confirmed everything works fine for you, @ThaPwned.

**Comment by ThaPwned** [comment]
Seems to be working now. Thanks!
