### ISSUE TITLE
raise exception for maximum precache objects for tempentities

### ISSUE THREAD

**Issue by maduxthemad** [Source-Python-Dev-Team/Source.Python#183]
a

**Comment by maduxthemad** [comment]
the engine handles this "error" by forcing the target range index with a standard function:
user_given_int%max_sendtables_int

for example index 65, will become index 1

**Comment by Ayuto** [comment]
Can you please provide links to the temp entities and their SendTables you are talking about?

That fix shouldn't be applied to the precache classes, because they really just precache and have no knowledge about where the precache index is used. It's up to the TempEntity class to raise an error.

>the engine handles this "error" by forcing the target range index with a standard function:
>user_given_int%max_sendtables_int
>
>for example index 65, will become index 1

This is not handles by the engine. It's called arithmetic overflow:
https://en.wikipedia.org/wiki/Arithmetic_overflow

**Comment by maduxthemad** [comment]
here is a link to tempentities :
https://github.com/Source-Python-Dev-Team/Source.Python/blob/daf06d0532b2be2a2a57b292e18364baec988c10/addons/source-python/data/source-python/effects/CTEFootprintDecal.ini

nice, you found a term on wiki that also describes my example. cool.

i dont think it should be added to the precache class, but be raised from within, because u can compare indexes of right after and before precaching. lest say i use tempentity("TEST").decal = Decal("model"), right before i precache it has the user_input_index and right after it has the engine changed index. i just thought this way one can workaround setting limits for each class singularily. 

but sure you can also hardcode the limits and then let the te class for the decal_index property raise a warning or exception. therefor a MAX_SIZE parameters could be added. but i really waynted to discuss the further detail about from which class or where in the code this warning is raised, once its assured that no fix can be applied for this. i dont want to jump to detailed conclusions if the issue isnt really understood. it really doesnt help to play on words, if you understand this issue, this will move forward.

**Comment by maduxthemad** [comment]
ill just post the decals, i have looked up on the sdk for reference:

te_footprintdecal.cpp 
SENDINFO(m_nIndex),			8,	SPROP_UNSIGNED ), **256** char type

te_bspdecal.cpp 
SendPropInt( SENDINFO(m_nIndex), 9, SPROP_UNSIGNED ), **512** short type

te_worlddecal.cpp 
SendPropInt( SENDINFO(m_nIndex), 9, SPROP_UNSIGNED ), **512** short type

te_decal.cpp 
SendPropInt( SENDINFO(m_nIndex), 9, SPROP_UNSIGNED ), **512** short type

te_projecteddecal.cpp 
SendPropInt( SENDINFO(m_nIndex), 9, SPROP_UNSIGNED ), **512** short type

and right now i will try to edit the template class of sp, to allow larger ints, somewhere like this:

https://github.com/Source-Python-Dev-Team/Source.Python/blob/3e3af6562ea4f88336d8d69b5018c5d14c31a227/addons/source-python/packages/source-python/effects/templates.py#L132

but i dont have a good overview over the sp classes, so any help is appreciated to test a fix

**Comment by maduxthemad** [comment]
okay, so i have looked into it. the index can even be ctempered via TempEntityPreHook ( after sendtables were created ), because the placeholder for index in sendtable is Sendprop INT type, that allows all smaller ints to fill into it.
https://github.com/Source-Python-Dev-Team/Source.Python/blob/daf06d0532b2be2a2a57b292e18364baec988c10/src/core/modules/entities/entities_props_wrap.cpp#L175

the only problem is, that once bigger ints, than the native max allows are filled, the deserializing on the client seems to bug out. i guess this is due to the fact, that the client expects to e.g. deserialize a uchar, and therefor ( if a larger int is forced) shifts the rest of the sendtable data.

maybe someone can doublecheck this, because im really not familiar with the sp code. maybe there is still a way to temper the sendtable and achieve a correct deserialization on the client to render decals correctly even above the native limit.

but it seems, it cant really be fixed from serverside. and the only option here is to raise the mentioned warnings to users via hardcoded limits adding to the te class @ setting decal_index property.

to clear up once again, in the list above you can derive from, that footprintdecal only allows 0-256 indexing (different decals), and the other four types 512 max.

this is only illustrating decals type, not mentioning the other tempentitites and precache types that exist

**Comment by maduxthemad** [comment]
**here you go:**

most tempentites have different sendtables. looking more closely the index for each precache type also differs.

this is an example for a m_nIndex property.
SendPropInt( SENDINFO(m_nIndex),	8,	SPROP_UNSIGNED ),

which apparently indexes up to 256. while other sendtables also index differently. source python only loads the sendtable templates. so when users try to use tempentites with indexes that exceed the maxsize, ( because the precache class allows of this ) the precache class could simply raise exception/warning that the the tempentity object the user is trying create will not be delivered/rendered correctly on the client.

a further note, on the clients end the tes' int property seems to be received with a larger int, that works for all
RecvPropInt( RECVINFO(m_nIndex))

which makes me wonder if its possible to temper the sendtables on the server to higher indexes, and see if the client is able to correctly draw higher indexes thus. this can be separately tested and issued to expand sp's functionality. EDIT: maybe this should be tested first.

so again, the other and main point of this, is to raise an exception or warning to users, from within the precache class, if sp cant create a fix to index higher than native templates allow. when users try to precache precache-types of te's that are limited to a specific size due to their sendtable. (e.g. bsp decal, that maxes at 512, but users try to pass decal class object/decalindex that carries higher than 512)

the engine handles this "error" by forcing the target range index with a standard function:
user_given_int%max_sendtables_int

here is a link to tempentities :
https://github.com/Source-Python-Dev-Team/Source.Python/tree/daf06d0532b2be2a2a57b292e18364baec988c10/addons/source-python/data/source-python/effects

nice, you found a term on wiki that also describes my example. cool.

i dont think it should be added to the precache class, but be raised from within, because u can compare indexes of right after and before precaching. lest say i use tempentity("name").decal = Decal("model"), right before i precache it has the user_input_index and right after it has the engine changed index. i just thought this way one can workaround setting limits for each class singularily.

but sure you can also hardcode the limits and then let the te class for the decal_index property raise a warning or exception. therefor a MAX_SIZE parameters could be added. but i really only wanted to discuss the further detail about from which class or where in the code this warning is raised, once its assured that no fix can be applied for this. i dont want to jump to detailed conclusions if the issue isnt really understood. it really doesnt help to play on words, if you understand this issue, this will move forward.

ill just post the decals, i have looked up on the sdk for reference:

te_footprintdecal.cpp
SENDINFO(m_nIndex),	8,	SPROP_UNSIGNED ), 256 char type

te_bspdecal.cpp
SendPropInt( SENDINFO(m_nIndex), 9, SPROP_UNSIGNED ), 512 short type

te_worlddecal.cpp
SendPropInt( SENDINFO(m_nIndex), 9, SPROP_UNSIGNED ), 512 short type

te_decal.cpp
SendPropInt( SENDINFO(m_nIndex), 9, SPROP_UNSIGNED ), 512 short type

te_projecteddecal.cpp
SendPropInt( SENDINFO(m_nIndex), 9, SPROP_UNSIGNED ), 512 short type

note that the sdk might be outdated...
and right now i will try to edit the template class of sp, to set larger ints ( actually for testing probably gonna set all to 12bit == precache limit )

but i dont have a good overview over the sp classes, so any help is appreciated to test this fix

okay, so i have looked into it. the index can even be ctempered via TempEntityPreHook ( after sendtables were created ), because the placeholder for index in sendtable is Sendprop INT type, that allows all smaller ints to fill into it.
https://github.com/Source-Python-Dev-Team/Source.Python/blob/daf06d0532b2be2a2a57b292e18364baec988c10/src/core/modules/entities/entities_props_wrap.cpp#L175

the only problem is, that once bigger ints, than the native max allows are filled, the deserializing on the client seems to bug out. i guess this is due to the fact, that the client expects to e.g. deserialize a uchar, and therefor ( if a larger int is forced) shifts the rest of the sendtable data.

maybe someone can doublecheck this, because im really not familiar with the sp code. and maybe there is still a way to temper the sendtable and achieve a correct deserialization on the client to render decals correctly even above the native limit.

but from my looking into it, it seems, it cant really be fixed from serverside. and the only option here is to raise the mentioned warnings to users via hardcoded limits adding to the te class @ setting decal_index property.

to clear up once again, in the list above you can derive from, that footprintdecal only allows 0-256 indexing (different decals), and the other four types 512 max.

this is only illustrating decals type, not mentioning the other tempentitites and precache types that exist

**Comment by maduxthemad** [comment]
my github account got hacked

**Comment by satoon101** [comment]
I haven't re-opened the thread, it remains closed.  All I did was restore your main comment and quoted your follow-up comments in my reply that asked you to not blank out your comments.

Also:
> my github account got hacked

I highly doubt this was actually the case.  Why would someone hack your account and only blank out your posts in this thread and close it?  Not to mention, this is certainly not the first time you have done this.

And, as I am one of the project managers for Source.Python, I can and will do what I see fit on this board.  So, please, don't try to tell me I can't do something without your permission.

**Comment by maduxthemad** [comment]
yes, you **did** reopen the discussion. and i dont agree with it. you dont respect my wish to have this thread closed after i wasnt satisfied with the reaction of one your team-members. i will remember this.
