### ISSUE TITLE
Prehook Saytext2 sent twice if HLTV is on the server.

### ISSUE THREAD

**Issue by Frag1337** [Source-Python-Dev-Team/Source.Python#185]
To replicate use following cfgs into autoexec.cfg

http://forums.sourcepython.com/viewtopic.php?p=9799#p9799

Can be tested with iPlayers Deadchat or the proven code few posts back.

**Comment by Ayuto** [comment]
Just tested this and the hook does indeed gets called twice, but the content of the recipient filter differs. The first call only sends the message to the TV bot. The second call sends the message to all players (or team members).

That doesn't look like a bug in SP. It's caused by the engine.

**Comment by Frag1337** [comment]
and how do I find out if it gets sent to the TV bot and which not? Want to fix it in my code.

**Comment by Ayuto** [comment]
Something like this might work:
```python
from players import PlayerGenerator
from players.helpers import playerinfo_from_edict
from entities.helpers import index_from_edict

def get_tv_bot():
    """Return the index of the TV bot.
    
    Return None if no TV bot was found.
    """
    for edict in PlayerGenerator():
        info = playerinfo_from_edict(edict)
        if info.is_hltv():
            return index_from_edict(edict)
            
    return None
    

# In your SayText2 hook
if len(recipients) == 1 and recipients[0] == get_tv_bot():
    # Message is only sent to TV bot
```
