### ISSUE TITLE
_AuthManager.is_player_authorized issue

### ISSUE THREAD

**Issue by KirillMysnik** [Source-Python-Dev-Team/Source.Python#189]
# Problem #
[`is_player_authorized`](https://github.com/Source-Python-Dev-Team/Source.Python/blob/3e3af6562ea4f88336d8d69b5018c5d14c31a227/addons/source-python/packages/source-python/auth/manager.py#L358)
```python
    def is_player_authorized(self, index, permission):
        """Return True if the player has been granted the given permission.

        :rtype: bool
        """
        return permission in self.get_player_permissions(index)
```

[`get_player_permissions`](https://github.com/Source-Python-Dev-Team/Source.Python/blob/3e3af6562ea4f88336d8d69b5018c5d14c31a227/addons/source-python/packages/source-python/auth/manager.py#L338)
```python
    def get_player_permissions(self, index):
        """.. seealso:: :meth:`get_player_permissions_from_steamid`"""
        return self.get_player_permissions_from_steamid(
            playerinfo_from_index(index).steamid)
```

[`get_player_permissions_from_steamid`](https://github.com/Source-Python-Dev-Team/Source.Python/blob/3e3af6562ea4f88336d8d69b5018c5d14c31a227/addons/source-python/packages/source-python/auth/manager.py#L343)
```python
    def get_player_permissions_from_steamid(self, steamid):
        """Return the permissions of a player.

        :param str/int steamid:
            The SteamID2, SteamID3 or SteamID64 of a player.
        :return:
            If the given SteamID is invalid (e.g. 'BOT'), None will be
            returned.
        :rtype: PlayerPermissions
        """
        try:
            return self.players[steamid]
        except ValueError:
            return None
```

See, `get_player_permissions_from_steamid` (and thus `get_player_permissions`) can return `None`. But in that case the following line in `is_player_authorized`:
```python
return permission in self.get_player_permissions(index)
```
will raise `TypeError: argument of type 'NoneType' is not iterable`

# Possible solution #
```python
    def is_player_authorized(self, index, permission):
        """Return True if the player has been granted the given permission.

        :rtype: bool
        """
        permissions = self.get_player_permissions(index)
        if permissions is None:
            return False

        return permission in permissions
```

**Comment by Ayuto** [comment]
Looks good! Please go ahead and add that change.
