### ISSUE TITLE
Player.address / address_from_playerinfo unexpected return value for bots

### ISSUE THREAD

**Issue by KirillMysnik** [Source-Python-Dev-Team/Source.Python#190]
Windows, CS:GO

This is what [docstring](https://github.com/Source-Python-Dev-Team/Source.Python/blob/1237596c12f9d385ecbf31dde882932d81a67e4c/addons/source-python/packages/source-python/players/_base.py#L156) says:

> Return the player's IP address and port.
        If the player is a bot, an empty string will be returned.
        :return: The IP address. E.g. '127.0.0.1:27015'
        :rtype: str

And it's true for regular bots.

But when I try the following snippet
```python
@OnClientActive
def listener_on_client_active(index):
    print("IP Address: {}".format(Player(index).address))
```

this is what is printed for just connected bots:
```
IP Address: 176924864
IP Address: 177622352
IP Address: 506225408
IP Address: 177475584
IP Address: 167048448
IP Address: 176134112
IP Address: 167642080
IP Address: 167835328
IP Address: 168081648
IP Address: 165674592
IP Address: 166054496
IP Address: 166136576
IP Address: 162450224
IP Address: 162537840
IP Address: 162635200
```

All values are integer.

So at least the docsting (and rtype) mismatches the case "we try to access bot address too early".
Though, for human players everything's fine and their actual IP address is returned. As a string.

For those who's going to look into the issue, I'd like to remind that `Player.is_fake_client` (not sure about `Player.is_hltv`) also returns False for bots in `OnClientActive` listener.

**Comment by satoon101** [comment]
We probably need to change it to use the same check that we do when getting the language:
https://github.com/Source-Python-Dev-Team/Source.Python/blob/daf06d0532b2be2a2a57b292e18364baec988c10/addons/source-python/packages/source-python/players/_language/base.py#L23

We added that previously for the same reason.

**Comment by KirillMysnik** [comment]
Also AFAIK there's some... prop? that scripts can alter and `is_fake_client` will return `False` after that. Not that it's good to alter such props, but `is_fake_client` is also not reliable from that point of view.

**Comment by satoon101** [comment]
Yes, `is_fake_client` just checks against the `FL_FAKECLIENT` flag.
https://github.com/alliedmodders/hl2sdk/blob/3957adff10fe20d38a62fa8c018340bf2618742b/game/server/player.cpp#L8622-L8625

There really isn't much we can do if people are going to mess with their servers in this manner, nor should we care.
