### ISSUE TITLE
PlayerIter.filters['bot'] should return True in OnClientActive listener

### ISSUE THREAD

**Issue by KirillMysnik** [Source-Python-Dev-Team/Source.Python#192]
To continue [the topic](https://github.com/Source-Python-Dev-Team/Source.Python/issues/190) of `is_fake_client` returning `False` for bots when the bots have just connected, I want to suggest several ways to choose from to improve the `PlayerIter.filters['bot']` and `PlayerIter.filters['human']` filters.

## Why?
Because I used these filters in `OnClientActive` listener and had to do [this](https://github.com/Source-Python-Dev-Team/Source.Python.Admin/commit/6143230c91aa669bd2a78b753ef4cf2fd1874e35).

### A. Add SteamID check to these filters
Just like so ([these lines](https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/filters/players.py#L95)):
```python
PlayerIter.register_filter('bot', lambda player: (
    player.is_fake_client() or 'BOT' in player.steamid))

PlayerIter.register_filter('human', lambda player: (
    not player.is_fake_client() and 'BOT' not in player.steamid))
```

### B. Add `is_bot` method to the `Player` class that does the above check
```python
def is_bot(self):
    return self.is_fake_client() or 'BOT' in self.steamid
```

```python
PlayerIter.register_filter('bot', lambda player: player.is_bot())
PlayerIter.register_filter('human', lambda player: not player.is_bot())
```

## My choice
I'd definitely go with the `is_bot` method because I often find myself writing that SteamID check in my plugins.

**Comment by satoon101** [comment]
I like the is_bot idea, but we could also add the steamid check to Player.is_fake_client itself.

Along the same line, does is_hltv have this same issue and does hltv have a unique steamid?  I have never used it before, so I have no idea.

**Comment by KirillMysnik** [comment]
HLTV's SteamID is also `BOT`.
I don't know if hltv suffers from this issue.

But I'm fine if `is_bot()` would return `True` for HLTV as I usually do bot checks just to make sure non-player characters don't go into the database or something like that. I consider HLTV a bot in all those cases.

**Comment by satoon101** [comment]
Ok, I would definitely vote for adding is_bot then.  I wouldn't want is_fake_client to always return True for hltv itself.

**Comment by KirillMysnik** [comment]
Does it make any sense to actually test `player.is_fake_client()` before checking steamid?

```python
def is_bot(self):
    return self.is_fake_client() or 'BOT' in player.steamid
```
```python
def is_bot(self):
    return 'BOT' in player.steamid
```

**Comment by KirillMysnik** [comment]
> Along the same line, does is_hltv have this same issue [...]

Apparently, yes: #168

**Comment by Ayuto** [comment]
``is_bot`` sounds good to me. I would also leave the rest untouched.

But why do you check for "contains" instead of equality?

**Comment by KirillMysnik** [comment]
> But why do you check for "contains" instead of equality?

I redirect this question to whoever wrote these lines
https://github.com/Source-Python-Dev-Team/Source.Python/blob/3288ad1aeb9fa8e2181c9ab859855f30da368ebe/addons/source-python/packages/source-python/players/helpers.py#L166
https://github.com/Source-Python-Dev-Team/Source.Python/blob/daf06d0532b2be2a2a57b292e18364baec988c10/addons/source-python/packages/source-python/players/_language/base.py#L23
And also that's why I asked why do we check `player.is_fake_client()` before checking for `'BOT'`.
