### ISSUE TITLE
Add player.set_active_weapon(weapon)

### ISSUE THREAD

**Issue by Frag1337** [Source-Python-Dev-Team/Source.Python#195]
Hey,

How about adding a set_active_weapon(weapon) which puts the weapon as the main weapon.
I dont like to use 'lastinv'  currently.

**Comment by invincibleqc** [comment]
I guess we could add a setter to `player.active_weapon` (currently read-only), but it would be as easy as doing  `player.active_weapon_handle = weapon.inthandle`.

**Comment by Frag1337** [comment]
With the addition of a setter to player.active_weapon would be pretty cool.

Good to know theres also player.weapon_switch(weapon).

Thanks

**Comment by invincibleqc** [comment]
https://github.com/Source-Python-Dev-Team/Source.Python/commit/99c29f35e7181488dc2e271cd57b81b239c3d123
