### ISSUE TITLE
Source Python doesnt load with newest CS:GO Update 

### ISSUE THREAD

**Issue by Frag1337** [Source-Python-Dev-Team/Source.Python#196]
Source Python (latest build) doesnt load with the latest CS:GO Update (http://blog.counter-strike.net/index.php/2017/05/18665/).

It just stucks at Loading..

Im using Windows 10.

**Comment by KirillMysnik** [comment]
Can't confirm
```
[Source.Python] Loading...
d:\srcds\csgo\csgo\addons\source-python\packages\source-python\__init__.py:390: UserWarning: sys.stdout and/or sys.stderr is None. All data will be redirected through core.console_message() instead. If you receive this warning, please notify us and tell us your operating system, game and Source.Python version. The information can be posted here: https://github.com/Source-Python-Dev-Team/Source.Python/issues/175. Source.Python should continue working, but we would like to figure out in which situations sys.stdout is None to be able to fix this issue instead of applying a workaround.
  'sys.stdout and/or sys.stderr is None. All data will be redirected through '
[Source.Python] Loaded successfully.
```

```
sp info

Date          : 2017-05-04 06:05:48.777595
OS            : Windows-10-10.0.14393
Game          : csgo
SP version    : 573
Server plugins:
   00: Source.Python, (C) 2012-2016, Source.Python Team.
SP plugins:
```

I have SP installed exclusively.

**Comment by IedSupo** [comment]
choo choo, @KirillMysnik 's trolltrain has already departed.. latest build is 575. mb check IMDLCache signatures ;) core dll needs updatooo

**Comment by satoon101** [comment]
I have this same issue on my local Windows 10.  I have narrowed down the issue to this line:
https://github.com/Source-Python-Dev-Team/Source.Python/blob/9f6daa21df370b67d2cc9f69a7d47515ec8ba9f9/addons/source-python/packages/source-python/loggers.py#L381

It seems to be an issue trying to get the ConVar object itself.  I added a debug message to print out `self._level` and SP fails to load, then fails to unload, then the server crashes.  Without that message, it just hangs at `Loading main module...`

**Comment by IedSupo** [comment]
ive tried to create a build for sp to test if i can fix it. but when i compile with build.bat on windows i get this error:

> C:\Users\tester\Documents\SP GITHUB\Source.Python\src\patches\csgo\lib\win32\release\vs2010\libprotobuf.lib
> C:\Users\tester\Documents\SP GITHUB\Source.Python\src\patches\csgo\public\networkvar.h
> 2 Datei(en) kopiert
> Der Befehl "cmake" ist entweder falsch geschrieben oder
> konnte nicht gefunden werden.

in english: cmake couldnt be found. i have visual studio etc installed on my system. is there a way to create a manual path in the bat to call cmake? or do i have to modify system variables? this should be the line within build.bat (maybe its messed up by me already, tried this a few days ago or so) :

    :: Create the build files
    cmake . -B%BUILDDIR% -G"Visual Studio 12" -DBRANCH=%branch%

is it possible to add a manual "cmake path" via console  (or even automatic scan)  to the bat script, if cmake couldnt be found?

or maybe im just totally off here with the error. maybe someone can help

**Comment by KirillMysnik** [comment]
@satoon101 Invincible told me it's probably due to this update:
https://github.com/alliedmodders/hl2sdk/commit/7ba42dff44d5a4acd3ed69f104861c34c6a13844
https://github.com/alliedmodders/hl2sdk/commit/8f20c14b05b4f599b0ec2e89ec19aa20fe788a45

Because other than that, there were no significant changes in C++ side since our previous build.

**Comment by satoon101** [comment]
@IedSupo - the simplest way to fix your issue would be to simply install cmake.

@KirillMysnik - Ok, when I get the chance, I will try to manually build after rolling back my local hl2sdk for csgo.  I'll post my findings here when I am done.

**Comment by Ayuto** [comment]
>@KirillMysnik - Ok, when I get the chance, I will try to manually build after rolling back my local hl2sdk for csgo. I'll post my findings here when I am done.

I already did some tests and with the old tier1.lib everything is working fine. I also recompiled the tier1.lib with the latest SDK changes and it's working fine as well. That's why I have commited the recompiled library:
https://github.com/Source-Python-Dev-Team/Source.Python/commit/c8d5bd949962c3b5cdfffe9d909655afd7a01c21

Right now I'm waiting for the buildbot to come back (it's a bit overloaded currently). If that is working fine as well, I'm going to contact psychonic. Maybe something happened to the file during the upload or he accidentally uploaded the wrong files.

**Comment by satoon101** [comment]
@Ayuto - I didn't see your commit before.  I just tested building locally with that fix, and it works fine now, thank you!  Hopefully the buildbot comes back up soon so we can verify with the official builds, as well.

**Comment by IedSupo** [comment]
no, these changes are intended. valve updated the csgo client against certain hooking methods. srcds servers are running almost like a client. but source python is using the exact hooking method and thus breaking the the client of the server to load its modules properly. ofc you can spoof the gc connection and serve old file signatures but this is really on valves end to fix.

**Comment by Frag1337** [comment]
Latest official build works

`sp info

Date          : 2017-05-08 00:23:57.387546
OS            : Windows-10-10.0.15063
Game          : csgo
SP version    : 576`

Can confirm.
