### ISSUE TITLE
Python as git submodule

### ISSUE THREAD

**Issue by Cubixmeister** [Source-Python-Dev-Team/Source.Python#197]
Wouldn't it be better to keep whole "addons/source-python/Python3" directory as git submodule?
It can be pinned to given commit from upstream Python repo.

Using a submodule would greatly simplify searching in Source.Python code - currently naive searches return a lot of junk from Python directories.

Does Source.Python modify core Python code in any way?

**Comment by Ayuto** [comment]
Yes, we have made a few changes to the Python3 directory, which includes removing some unnecessarry libraries and adding the compiled Python binaries for Linux and Windows. Also, we don't need the whole CPython repository, but only the Python libraries.
