### ISSUE TITLE
KeyValues 'Default' changes to 'default' in .as_dict()

### ISSUE THREAD

**Issue by Frag1337** [Source-Python-Dev-Team/Source.Python#202]
Reference:

https://forums.sourcepython.com/viewtopic.php?f=20&t=1577

EDIT: 

I dont know how to reproduce it with other words, but another example would be 'r' ends as 'R' in the dict.

**Comment by Ayuto** [comment]
Looks like this is the nature of KeyValues (this isn't an issue of the ``as_dict()`` function). I have also been able to reproduce this issue with the following KeyValues (the key ``test`` is printed as ``Test``):
```
"Test"
{
   "Test 1"
   {
         "test"   "test"
   }
   "Default"
   {
         "test"   "test"
   }
}
```

**Comment by Frag1337** [comment]
So, is there a aroundway fix for this? I realy dont like that all KeyValues are in big letters and some are only in small ones when they shouldnt.

**Comment by Ayuto** [comment]
There isn't except parsing the file on your own. Why don't you use a different method to store your data?

**Comment by KirillMysnik** [comment]
+1 for "use a different method to store your data". If you migrate from sourcemod and want to use the configs of their plugins, I'd supply your plugin with some kind of standalone `KeyValues -> JSON` converter. Or maybe not standalone - you might add a server command to convert the SM configs to your new format.

[keyvalues-python](https://github.com/JulioC/keyvalues-python) package might help there.

JSON is more powerful in sense that it lets you store *collections* of objects, while only VMF dialect of KeyValues (the format that Hammer Editor maps are stored in) allows you to do something similar.

**JSON**
```json
{
    "collection": [
        "object 1",
        "object 2"
    ]
}
```

**VMF KeyValues**
```
{
    "collection" "object1"
    "collection" "object2"
}
```
But if you follow this syntax, there's no way to distinguish a 1-item collection from a regular key.

**Comment by asherkin** [comment]
@Ayuto drive by year later comment, but if Python dict keys are case-sensitive, your `as_dict` method should probably be lowercaseing all the keys. KV keys are case-insensitive by design, and will end up as whatever case of the first instance *anywhere in the game* due to case-insensitive string pooling.

**Comment by Ayuto** [comment]
Thanks for the explanation! I will think about changing the ``as_dict`` method.
