### ISSUE TITLE
game specific USRMSGS

### ISSUE THREAD

**Issue by IedSupo** [Source-Python-Dev-Team/Source.Python#210]
are there any existing sp files for gamespecific usermessages or is everything in 

> packages/source-python/messages/base.py

? if thats the case my idea would be to add any game specific missing usermessages ( csgo ) into the existing base.py with a gamecheck @loadtime for game dependend classes.

otherwise, to also keep it a bit more clean, i could think of having seperate folders like

> packages/source-python/messages/csgo

 to load from in base.py in a smiliar manner?

**Comment by Ayuto** [comment]
``base.py`` was originally intended to contain all user messages that are shared across all supported games. Engine and game specific messages should be arranged similar to the player package:
https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/players/entity.py#L24-L50

**Comment by IedSupo** [comment]
okay but did you understand my question? if i want to add new usermsgs for csgo, where should i place them? are you suggesting this folder:
> packages/source-python/messages/engines/csgo
? and furthermore adding a load command within base.py ? is that your suggestion?

thanks if you can get more clear.

**Comment by Ayuto** [comment]
>okay but did you understand my question?

I could ask the same. :D Did you understand the player package structure? But your assumption is correct. ``../messages/engines/csgo/__init__.py`` is where the CS:GO specific user messages should be placed. Engine and game specific files are then imported by ``messages/__init__.py``, not by ``base.py``.

**Comment by IedSupo** [comment]
why could you ask the same? you always reiterate the question to a non-answer or claim the question was malformed, although you never ask for clarification.

**Comment by satoon101** [comment]
In all honesty, there are messages in `base` and `dialog` that are imported into the `__init__` that do not work on specific games.  Game specific should really only be used for any messages that have to be handled differently on one game compared to another.

This does not include bitbuf vs protobuf, which are all handled properly in the `base`.  So, if you want to add CS:GO specific messages, `base` should work fine, as it is the only one that supports protobuf anyway.  If anything, create the bitbuf method to just raise a NotImplementedError if the UserMsg is not available on ANY bitbuf game.

If this is for the `VoteStart` stuff you have posted on the forums, I am pretty sure the same UserMsg (only the bitbuf version) exists in other games (L4D2?).

**Comment by IedSupo** [comment]
yes currently for the votemenu that exists in csgo. but i am still trying to figure out the protobuf layout for it though.

i would also like to try some of the other "left out" csgo msgs too, i just dont know where to find the exact layout for each protobuf msg. ayuto reiterated my idea that i would have to use ida, but im not very familiar with ida and wouldnt know how to go about it. 

in general i just thought that it would be helpful if i would at least leave some notes or even working functions to whomever wants to add it to sp in the future.

**Comment by IedSupo** [comment]
okay i also just checked what you said about lfd2. it seems to have the same usermsg. so thats a good hint, maybe i will find some info there about the layout.

from what i tested the server can create a vote with votestart. and then the user sends back his "reply" in a different usermsg id, while the vote is running on the server. so it should be easy to create a voteclass for csgo,lfd2 etc and add it to sp this way.

**Comment by satoon101** [comment]
> i would also like to try some of the other "left out" csgo msgs too, i just dont know where to find the exact layout for each protobuf msg.

This would be a good starting point for that:
https://github.com/alliedmodders/hl2sdk/tree/csgo/public/game/shared/csgo/protobuf

**Comment by IedSupo** [comment]
well i found those too, but those are only the args right? i think some usermsgs utilize serverspecific objs. ( like UserMessage e.g. ? )

**Comment by IedSupo** [comment]
for reference i found this : https://github.com/ValveSoftware/Source-1-Games/issues/1160

**Comment by IedSupo** [comment]
ive got it mostly working. the only problem is that csgo works with stringtables, so the disp_str param field, requires sthn in the type of "#SFUI_vote_swap_teams" and internally calls a stringdict in the client. its not customizable. there is a second param though called "details_str" which can be used to append to the first string in the votemenu. im currently looking through the entire strintable to see if i can find anything utilizable...
