### ISSUE TITLE
TempEntity('breakmodel') - some properties dont work

### ISSUE THREAD

**Issue by IedSupo** [Source-Python-Dev-Team/Source.Python#213]
.flags .randomization are without effect. are there any datamaps do see what values wirj in these properties work? i tried [2**i for i in range(0,64)] for flags and saw no difference...

**Comment by invincibleqc** [comment]
You can read the `TempEntity('breakmodel').template.properties` dictionary to see the available `SendProp` instances of a specific `TempEntity` object. However, we are simply wrapping the member variables that are declared in the `SendTable` of a specific `CTempEntity` class and as far as what the server/client does with them is not our responsibility. So if `effects/flags/randomization` have no effect for that one, there is nothing we can do on our end.

**Comment by IedSupo** [comment]
my question is if someone knows what values go into .flags and .randomization properties. 

i already looked into the client files for csgo and dont see any use for them. could it be that csgo, doesnt utilize .flags etc but another game e.g. bms or tfs etc do? then maybe it would help to indicate this somewhere in the csgo ini. 
its just a suggestion. so.. i dont really get why you didnt adress the concern OR look into it, but only, clearly, quickly evaded it.

**Comment by invincibleqc** [comment]
I literally replied to your only "question".  :expressionless:

> are there any datamaps do see what values wirj in these properties work?

>You can read the TempEntity('breakmodel').template.properties dictionary to see the available SendProp instances of a specific TempEntity object.

And I also mentioned that we are only wrapping the classes, everything else doesn't concern us. If you have questions, this is very simple: you go on the forums. Here you report issues or request features related to `Source.Python`.
