### ISSUE TITLE
setting angles math problem

### ISSUE THREAD

**Issue by IedSupo** [Source-Python-Dev-Team/Source.Python#214]
setting angles with .angles property is not accurate.
where can i find the function for it to check for math errors?

**Comment by invincibleqc** [comment]
COuld you please provide more info when you report an issue? Info such as...

- What class?

- What code did you use?

- Why do you say it is not accurate?

If you are referring to [Entity.angles](https://github.com/Source-Python-Dev-Team/Source.Python/blob/ea0b35b164a7323981b62735c981970a4b307dec/addons/source-python/data/source-python/entities/CBaseEntity.ini#L53-L55), we are wrapping the _angles_ keyvalues so the wrapped code is within the engine itself into the [CBaseEntity::KeyValue](https://github.com/alliedmodders/hl2sdk/blob/csgo/game/shared/baseentity_shared.cpp#L407-L418) method.

**Comment by KirillMysnik** [comment]
The only metric math that I remember that SP does by itself starts on [this line](https://github.com/Source-Python-Dev-Team/Source.Python/blob/ea0b35b164a7323981b62735c981970a4b307dec/addons/source-python/packages/source-python/players/_base.py#L264)

See `set_view_coordinates`, `view_vector` and `get_view_angle`
