### ISSUE TITLE
Source.Python loads but doenst list in plugins

### ISSUE THREAD

**Issue by rafal-olszewski** [Source-Python-Dev-Team/Source.Python#215]
I've followed instructions on your wiki, ran everything on fresh debian installation + fresh csgo server, while debugging I saw in the console that SP was loaded, and then while typing `plugins_print` ingame in console, none were listed. only something like
```
Loaded plugins:
---------------
---------------
```

**Comment by KirillMysnik** [comment]
(the command is `plugin_print`)

Typing `plugin_print` in your game console will only print plugins installed on your game client (that is possible when running the game with `-insecure` launch argument).

If you install Source.Python on server, you should type `plugin_print` there instead. That's what I get:
```
plugin_print
Loaded plugins:
---------------------
0:      "Source.Python, (C) 2012-2016, Source.Python Team."
---------------------
```

Another way to check if SP is installed successfully is to run any of its built-in commands. Like
`sp info`
will print something like
```
sp info

Date          : 2017-07-17 16:56:36.272704
OS            : Windows-10-10.0.14393
Game          : csgo
SP version    : 585
Server plugins:
   00: Source.Python, (C) 2012-2016, Source.Python Team.
SP plugins:
   00: badlocalanglesfix
```
Again, you need to try it in the _server_ console if you install SP on the server.

**Comment by rafal-olszewski** [comment]
That was the issue, i ran it on game client.
Thanks!
