### ISSUE TITLE
Vector operands

### ISSUE THREAD

**Issue by Predz** [Source-Python-Dev-Team/Source.Python#216]
I have been working on a teleport skill for my warcraft plugin recently and noticed that some operations are not working with Vector objects. Could there be a problem the other operations?

Currently I have to store the player's view vector, then manipulate it how I want, just to add it to the player's origin. 
```python
original = player.origin
view_vector = player.view_vector
view_vector *= 800.0
location = original + view_vector
if engine_trace.is_point_outside_of_world(location):
    return
```

Where as this could easily be written as: with the * operation.
```python

location = player.origin + (player.view_vector * 800.0)
if engine_trace.is_point_outside_of_world(location):
    return
```

The error I am getting is below:
`
[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\plugins\warcraft\calls.py", line 132, in _filter_commands_call_events
    player.hero.call_clientcommands(command_name, player=player, command=command)
  File "..\addons\source-python\plugins\warcraft\heroes\__init__.py", line 160, in call_clientcommands
    method(*args, **kwargs)
  File "..\addons\source-python\plugins\warcraft\heroes\extensions.py", line 428, in _on_command
    location = player.origin + (player.view_vector * 800.0)

TypeError: unsupported operand type(s) for *: 'float' and 'Vector'
`

I can see they are defined, so unsure on the problem...

https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/src/core/modules/mathlib/mathlib_wrap.cpp#L235

Or am I mis-understanding something? Sorry

**Comment by Ayuto** [comment]
Actually, it should work. What's the output of ``sp info``?

**Comment by Predz** [comment]
`Date          : 2017-07-30 11:04:55.998514
OS            : Windows-10-10.0.14393
Game          : csgo
SP version    : 585
Server plugins:
   00: Source.Python, (C) 2012-2016, Source.Python Team.
SP plugins:
   00: warcraft`

**Comment by KirillMysnik** [comment]
Looking at the exception (the order of reported types), I'd say you were doing this
```python
location = player.origin + (800.0 * player.view_vector)
```
instead of this
```python
location = player.origin + (player.view_vector * 800.0)
```

**Comment by Predz** [comment]
Yup, exactly what I was doing, oops. I changed the order to clean the code for reading to be honest. Obviously though, it screws up if executed in the opposite order.

In final. Yes it works if put in the 2nd order you shown iPlayer, but why doesn't it work in the 1st order? Because you are calling <float>.__mul__, instead of <Vector>.__mul__?

**Comment by Ayuto** [comment]
>Because you are calling .mul, instead of .mul?

I guess you meant ``__rmul__``. But yes, that's exactly why.
