### ISSUE TITLE
[CS:GO] server crashes since latest update

### ISSUE THREAD

**Issue by IedSupo** [Source-Python-Dev-Team/Source.Python#219]
sp info
> Date          : 2017-08-18 13:00:31.363655
> OS            : Windows-7-6.1.7601-SP1
> Game          : csgo
> SP version    : 582
> 
console debug on dust2
> Compressing fragments for The Chosen One(192.168.2.100:27005) (12998 -> 6482 bytes)
> PutClientInServer: no info_player_start on level
> Sending full update to Client The Chosen One (The Chosen One can't find frame from tick -1)
> Compressing fragments for The Chosen One(192.168.2.100:27005) (9476 -> 6270 bytes)
> unhandled input: (OnPlayerJoin) -> (game_player_manager), from (player,); target entity not found
> unhandled input: (OnPlayerSpawn) -> (game_player_manager), from (player,); target entity not found
> ESP not present.
> 

the server doesnt create a crashdump, are there other ways to investigate?

**Comment by IedSupo** [comment]
sorry to ask, what are AM commits?
im gonna try to update the sigs now and see what will happen. hopefully ill get some more insight to the problem then. thanks for the help. btw: csgo updated something about faster mapload. i wonder if there is a way to investigate such csgo changes. ayuto once posted this : https://github.com/SourceChanges. but i dont feel that its really up to date..

**Comment by KirillMysnik** [comment]
By AM commits I meant [AlliedModders commits on Sourcemod repo](https://github.com/alliedmodders/sourcemod/commits/master)

**Comment by IedSupo** [comment]
ah, wow. they seem to be very active.. ill probably just wait then

**Comment by KirillMysnik** [comment]
To make it more narrow, the crash is caused by [this entity listener](https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/entities/hooks.py#L223).

Commenting out its decorator or making it return immediately avoids the crash.

**Comment by KirillMysnik** [comment]
To make it even more narrow, the crash is caused by [this `EntityPreHook`](https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/listeners/_run_command.py#L35)

**Comment by KirillMysnik** [comment]
The issue is closed, thanks for report!

**Comment by IedSupo** [comment]
yeah i was just gonna say the runcommand hook was causing the actual crash. thanks !

**Comment by KirillMysnik** [comment]
As I stated in the commit description, indeed there're lots of other signatures to update (Valve's added something to `CBasePlayer` and offsets got incremented).
I didn't feel like renaming this issue so I thought that other (crash-unrelated) signatures deserve their own issue. Feel free to open it.
