### ISSUE TITLE
Precache Class Speedup?

### ISSUE THREAD

**Issue by Speed0x** [Source-Python-Dev-Team/Source.Python#227]
due to this thread:
https://forums.sourcepython.com/viewtopic.php?f=20&t=1644&start=20

would sthn like this be faster? ( did not test it, just to give you the idea )
[https://pastebin.com/YugNTMYM](https://pastebin.com/YugNTMYM)

**Comment by Ayuto** [comment]
No, I just did a test and it seems like the ``AutoUnload`` class is super slow. We will need to fix that class.

**Comment by Speed0x** [comment]
wouldnt it be enough to call inspect.stack(0)?

**Comment by Ayuto** [comment]
I already added that. It's speeding it up a little bit.

**Comment by Ayuto** [comment]
This one should suffice: https://github.com/Source-Python-Dev-Team/Source.Python/commit/19382f7764577c14b24e5495c4af2fb54105e922

```python
import time

from inspect import getmodule
from inspect import stack
from inspect import currentframe

def get_caller_slow():
    return getmodule(stack(0)[1][0])
    
def get_caller_fast():
    return getmodule(currentframe().f_back)
    
def measure_call(iterations, func):
    now = time.time()
    for x in range(iterations):
        func()
        
    print(func, time.time()-now)
    
    
measure_call(1000, get_caller_slow)
measure_call(1000, get_caller_fast)
```
Output:
```
<function get_caller_slow at 0x1C64EA08> 4.41125226020813
<function get_caller_fast at 0x1C64EA98> 0.04300260543823242
```

**Comment by Speed0x** [comment]
`import sys
import inspect
import time

print(inspect.getmodule(inspect.stack()[1][0]))

frame = inspect.stack()[1][0]

print(sys._getframe(1).f_back.f_globals['__name__'],sys._getframe(1).f_back.f_globals['__file__'])
print("")

sttime = time.time()
for i in range(1,1000):
  frame = sys._getframe(1)
  mod = frame.f_back.f_globals['__name__']
  file = frame.f_back.f_globals['__file__']
  
  
print(time.time()-sttime)

sttime = time.time()
for i in range(1,1000):
  frame = inspect.stack()[1][0]
  mod = inspect.getmodule(inspect.stack()[1][0])
  
print(time.time()-sttime)`

**Comment by Speed0x** [comment]
```
import time
import sys

from inspect import getmodule
from inspect import stack
from inspect import currentframe

def get_caller_slow():
    return getmodule(stack(0)[1][0])
    
def get_caller_fast():
    getmodule(currentframe().f_back)
    
def get_caller_fastest():
    return sys._getframe(1).f_back
    
    
def measure_call(iterations, func):
    now = time.time()
    for x in range(iterations):
        func()
        
    print(func, time.time()-now)
    
    
measure_call(1000, get_caller_slow)
measure_call(1000, get_caller_fast)
measure_call(1000, get_caller_fastest)
```

OUTPUT:
```
<function get_caller_slow at 0x7f4198a6e488> 1.2425510883331299
<function get_caller_fast at 0x7f4198a6e620> 0.40924715995788574
<function get_caller_fastest at 0x7f4198a6e6a8> 0.0004467964172363281
```

i know this doesnt take certain checks into account about getattr etc, but maybe this won't be needed anyway, so you could doublecheck for it, if you want

**Comment by Ayuto** [comment]
Yeah, I saw that ``_getframe`` function on StackOverflow. However, it's an internal function. Thus, I don't want to and shouldn't use it. Moreover, your improvement is not quite correct. You forgot the ``getmodule`` call, which will slow down it again a little bit. Btw. if you use ``_getframe(2)`` you can remove the ``f_back`` thing.

**Comment by Speed0x** [comment]
woops, my bad... gonna edit it

```
import time
import sys

from inspect import getmodule
from inspect import stack
from inspect import currentframe

def get_caller_slow():
    return getmodule(stack(0)[1][0])
    
def get_caller_fast():
    getmodule(currentframe().f_back)
    
def get_caller_fastest():
    try:
      sys.modules[sys._getframe(1).f_back.f_globals['__name__']]
    except:
      try:
        sys._getframe(1).f_back.f_globals['__file__']
      except:
          None
    
    
def measure_call(iterations, func):
    now = time.time()
    for x in range(iterations):
        func()
        
    print(func, time.time()-now)
    
    
measure_call(1000, get_caller_slow)
measure_call(1000, get_caller_fast)
measure_call(1000, get_caller_fastest)
```

**Comment by Speed0x** [comment]
idk... someone just has to test it i guess, to see if it would work with sys calls. but arent the modules always in ram? so shouldnt:

> sys.modules[sys._getframe(1).f_back.f_globals['__name__']]

always work??
