### ISSUE TITLE
ValueError: Pointer is NULL for pre events after map changes

### ISSUE THREAD

**Issue by backraw** [Source-Python-Dev-Team/Source.Python#230]
The [pre events in my script, or at least one of them](https://github.com/backraw/udm/blob/master/addons/source-python/plugins/udm/udm.py#L125) (lines 125-140) are causing the following error after a map change:
```
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/events/hooks.py", line 197, in _pre_game_event
    game_event = make_object(GameEvent, args[1])

ValueError: Pointer is NULL.
```
I haven't looked into it much, so I cannot tell whether it happens on all maps or just a few - but it does for de_train on CS:GO with build #616. I don't see any changes in builds 617 through 618 related to pre events, so I assume my testing environment is 'up to date' in this case.

It seems like a general error, maybe the make_object() call is being done too early or something?

**Comment by satoon101** [comment]
I have noticed this, too, every time I start a map when GunGame is loaded.  I don't think it's too big of a deal, but it is odd that the pointer is null.

**Comment by backraw** [comment]
True. However the console spamming is not very nice. I might as well take a closer look at it myself.

**Comment by Ayuto** [comment]
I will also take a look at it soon. What's the output of ``sp info``?

**Comment by backraw** [comment]
I've updated to build #618:
```
sp info

Date          : 2017-11-26 21:17:52.943154
OS            : Linux-4.9.63-1-MANJARO-x86_64-with-glibc2.9
Game          : csgo
SP version    : 618
Server plugins:
   00: Source.Python, (C) 2012-2016, Source.Python Team.
SP plugins:
   00: udm, 1.4, https://forums.sourcepython.com/viewtopic.php?f=7&t=1643
```

**Comment by Ayuto** [comment]
Does this only happen with CS:GO or other games as well?

**Comment by satoon101** [comment]
I have only seen it during map change on CS:GO.

**Comment by backraw** [comment]
I'll test CS:S tomorrow, but I have also only seen it with CS:GO so far.

**Comment by backraw** [comment]
The error doesn't show up on CS:S. Tried multiple map changes and the console is quiet.

**Comment by Ayuto** [comment]
Hmm, I'm unable to reproduce this issue on my Linux machine.

**Comment by backraw** [comment]
I'll try to figure out the exact steps that cause the issue as soon as I can

**Comment by satoon101** [comment]
Did some testing, and it seems it might have to do with bots.  The following reproduces the issue on Windows with no other server plugins loaded besides SP and no other SP plugins loaded:

Start the server with `bot_join_after_player` set to `1`.  Load the following plugin:
```python
from events.hooks import PreEvent
```

Change the following cvars in the server's console:
```
bot_quota 10
bot_join_after_player 0
```

**Comment by Ayuto** [comment]
Thanks! Now, I'm able to reproduce this issue and this is definitely a bug in CS:GO, because you can crash the server by enabling ``display_game_events`` even without SP being loaded.

The crash can be explained by taking a look at the pseudo-code for ``CGameEventManager::FireEvent`` and ``CGameEventManager::FireEventIntern``:
```c++
bool CGameEventManager::FireEvent(FireEvent(IGameEvent* event, bool bDontBroadcast)
{
  if (display_game_events is enabled)
  {
    Msg("Game Event Fired: %s\n", event->GetName());
  }
  return FireEventIntern(event, bDontBroadcast, 0);
}

bool CGameEventManager::FireEventIntern(IGameEvent* event, bool, bool)
{
    if (event)
    {
        // Do something
    }
}
```
As you can see the server tries to send a message showing the name of the event that should be fired (if ``display_game_events`` is enabled). This will crash the server if ``event`` is ``NULL``. It doesn't crash if ``display_game_events`` is disabled, because ``FireEventIntern`` has a check on ``event``.

I will go ahead and fix this with SP.

PS: Someone might want to report this to the CS:GO developers.
