### ISSUE TITLE
[Please Close] Issue resolved in new version.

### ISSUE THREAD

**Issue by Raklatif** [Source-Python-Dev-Team/Source.Python#238]
[SP] Encountered a Warning:
File '..\addons\source-python\plugins\es_emulator\eventscripts\esc\parse.py', line 62: DeprecationWarning
generator 'getcommands' raised StopIteration

[corelib/interfaces/register 232] es_foreachval: Unable to retrieve a pointer of this object.
[SP] Loading plugin 'wcs'...

[SP] Encountered a Warning:
File '..\addons\source-python\packages\site-packages\path.py', line 1713: DeprecationWarning
path is deprecated. Use Path instead.

[SP] Encountered a Warning:
File '..\addons\source-python\plugins\wcs\commands.py', line 480: DeprecationWarning
invalid escape sequence \l

[SP] Encountered a Warning:
File '..\addons\source-python\plugins\wcs\commands.py', line 587: DeprecationWarning
invalid escape sequence \s

[SP] Encountered a Warning:
File '..\addons\source-python\plugins\wcs\commands.py', line 628: DeprecationWarning
invalid escape sequence \p

[SP] Encountered a Warning:
File '..\addons\source-python\plugins\wcs\showitems.py', line 13: DeprecationWarning
invalid escape sequence \w

**An Example below is from Line(s) 581-587 for the commands.py issue listed above as "invalid escape sequence \s"**
```python
@ServerCommand('hawk_attack')
def _hawk_attack_effect(command):
    userid = int(command[1])
    player = Player(index_from_userid(userid))
    origin = player.origin
    queue_command_string('est_effect_18 #a 0 "%s, %s, %s" 255 2 2 50 100 3 10' % (origin[0], origin[1], origin[2]))
    queue_command_string('est_effect_14 #a 0 models\seagull.mdl "%s, %s, %s" "%s, %s, %s" 1000 6 500' % (origin[0], origin[1], origin[2], origin[0], origin[1], origin[2]+200)) 
```

**Comment by Raklatif** [comment]
****

**Comment by Ayuto** [comment]
This has nothing to do with Source.Python, but with ES Emulator and WCS. Moreover, you already reported the ES Emulator warnings and those already have been fixed:
https://github.com/Ayuto/EventScripts-Emulator/issues/16

All remaining warnings are caused by WCS, so please use the WCS issue list.
