### ISSUE TITLE
Strange behavior with Player.eye_angle

### ISSUE THREAD

**Issue by ThaPwned** [Source-Python-Dev-Team/Source.Python#243]
If you modify a locally saved Player.eye_angle, and retrieve a new value later on, you will get the modified value instead of the original one.

Info:
```
Date          : 2018-03-11 19:40:41.591779
OS            : Windows-8.1-6.3.9600
Game          : csgo
SP version    : 642
Github commit : 828d8ffc7d191b297f64c33c347eaea62cd42a81
Server plugins:
   00: Source.Python, (C) 2012-2018, Source.Python Team.
SP plugins:
   00: test
```

Code to reproduce the problem:
```python
from events import Event
from players.entity import Player


@Event('player_say')
def player_say(event):
    if event['text'] == '!test':
        player = Player.from_userid(event['userid'])
        eye_angle = player.eye_angle

        eye_angle[1] += 180

        assert eye_angle != player.eye_angle
```

**Comment by Ayuto** [comment]
It's a feature, not a bug. Source.Python retrieves the address of ``m_angEyeAngles`` and wraps/casts it to a ``QAngle``. So, if you modify the return value, the real ``QAngle`` instance is modified.

**Comment by ThaPwned** [comment]
So if you just wanted to modify the values temporarily, you'd have to do it like so?:
```python
eye_angle = QAngle(*player.eye_angle)
eye_angle[1] += 180
```

**Comment by Ayuto** [comment]
Exactly, that creates a copy of the ``QAngle`` instance.
