### ISSUE TITLE
TypedSayCommand does not accept the colon character

### ISSUE THREAD

**Issue by ns-phennessy** [Source-Python-Dev-Team/Source.Python#244]
**Game**: Team Fortress 2
**Input in chat**: `!mapdl http://test.com/test.bsp`
**Code in question**:
```python
from commands.typed import TypedSayCommand

@TypedSayCommand('!mapdl')
def on_mapdl(command_info, map_url: str):
    print(map_url)
```

**Error**: 
```
Too many arguments:
  !mapdl <map_url:str>
```

Works fine without the colon character. Not sure if this is just a parse issue or deliberately there? It also looks like it truncates everything after the colon, even if i did a *args: `('http', ':')`

**Comment by Ayuto** [comment]
Have you tried passing the URL in quotation marks?

**Comment by ns-phennessy** [comment]
Yes, single and double quotes are no dice.

It only appears to be when coming from chat commands; it works fine as a server console command (though that needs quotes)

**Comment by Ayuto** [comment]
Looks like we need to split the arguments on our own instead of relying on ``CCommand``.

**Comment by Cheaterman** [comment]
FWIW, the single quote doesn't seem to work either (dunno why anyone would want that, in my case I wanted a hidden command for godmode when people said `I'M JOHN CENA` in the chat, I settled on `I AM JOHN CENA` instead).

**Comment by invincibleqc** [comment]
The Tokenize class I posted back in 2013 seems to have the desired outputs here: https://forums.sourcepython.com/viewtopic.php?p=1221#p1221

```python
from re import compile

class Tokenize(list):
    _pattern = compile('"[^"]*"|[^ ]+')

    def __init__(self, given_string, comment_prefix=None):
        self.string = given_string

        for token_match in self._pattern.finditer(self.string):
            token_string = token_match.group()

            if comment_prefix and token_string.startswith(comment_prefix):
                self.string = self.string[:token_match.start()]
                break

            self.append(token_string.strip('"'))

    def __str__(self):
        return self.string

print(repr(Tokenize('!mapdl http://test.com/test.bsp')))

# Result:  ['!mapdl', 'http://test.com/test.bsp']

print(repr(Tokenize("I'M JOHN CENA")))

# Result: ["I'M", 'JOHN', 'CENA']
```

**Comment by Cheaterman** [comment]
Le Québec invincible gagne encore! :-)

I'm going to try monkey-patching the standard Tokenize with your regexp and see if it doesn't break anything in my code.

If it works for everyone else, can we expect a PR from you, @invincibleqc ?
