### ISSUE TITLE
Segfault when banning a player

### ISSUE THREAD

**Issue by Cheaterman** [Source-Python-Dev-Team/Source.Python#248]
Hello buddiez, I hope you're all doing goodie!

I made a very simple ban command as follows:

```python
@TypedSayCommand('!ban', 'tms.ban')
def ban(command, index :int, duration :int = 0):
    player = Player(command.index)

    try:
        target = Player(index)
    except ValueError:
        SayText(
            'The userid "{}" is invalid.'.format(index),
        ).send(player)
        return CommandReturn.BLOCK

    target.ban(duration)

    SayText(
        'Player "{}" was banned.'.format(
            target.name,
        ),
    ).send()
```

It segfaults whenever I try using it.

Thanks in advance! Owiii ^__^

**Comment by Ayuto** [comment]
What's the output of ``sp info``?

Btw. your message should say "invalid index" instead of "invalid userid".

**Comment by Cheaterman** [comment]
Hi @Ayuto, thanks for your quick response!

The output is as follows:

```
sp info

IMPORTANT: Please copy the full output.
--------------------------------------------------------
Checksum      : 4ce9c62ca1a1f0606e7d13f975d50f88
Date          : 2018-05-27 08:39:27.442584
OS            : Linux-3.16.0-4-amd64-x86_64-with-debian-9.4
Game          : csgo
SP version    : 649
Github commit : 3435c018d7b315e1fbda8a3b663267931415bd89
Server plugins:
   00: Source.Python, (C) 2012-2018, Source.Python Team.
SP plugins:
   00: tms
--------------------------------------------------------
```

You're right about the message, I shouldn't re-define terminology, but my users are familiar with another videogame (SA:MP) in which I generally use "player id" for this - so I'll probably use this instead!

**Comment by Ayuto** [comment]
Should be fixed now. Internally, the ``ban`` method uses the server commands ``banid`` and ``writeid``. It looks like CS:GO doesn't like them being called directly. Now, they are passed to the server command queue.
