### ISSUE TITLE
Failed to load plugin in csgo (windows)

### ISSUE THREAD

**Issue by GamerDude1237886** [Source-Python-Dev-Team/Source.Python#250]
When i launch csgo this error message appears in the console :
[Source.Python] Loading...
=========================================================================
[SP-LOADER] Could not load library: Python3/plat-win/vcruntime140.dll
[SP-LOADER] (Code: 126) The specified module could not be found.
=========================================================================
Failed to load plugin "addons/source-python"
And i looked into the files and saw that it's there though
i went to dllfiles.com
and downloaded the 64-bit version it still didn't work.

**Comment by Ayuto** [comment]
Try installing this:
https://www.microsoft.com/en-us/download/details.aspx?id=48145

Source.Python is a 32 bit application, so you need the x86 version.

**Comment by GamerDude1237886** [comment]
Thank you i will try it :)

**Comment by Ayuto** [comment]
Alright, please let me know if this fixes your problem.
