### ISSUE TITLE
CSGO, SayText2 and the colors module

### ISSUE THREAD

**Issue by backraw** [Source-Python-Dev-Team/Source.Python#252]
Tested games: CSGO, CS:S

I usually send a prefixed and colored SayText2 message like this:
```py
from colors import WHITE
from colors import ORANGE

SayText2(
    f'{ORANGE}[{WHITE}My Plugin Name{ORANGE}] {WHITE}My message ....
).send(some_index)
```

This works for CS:S, but it doesn't for CSGO. It shows the following chat message all in red instead: `FFA500[FFFFFFMy Plugin NameFFA500] FFFFFFMy message ....`. This tells me that these colors simply can only be used on entities in CSGO. I'm not sure if there have been plans to 'fix' this 'issue'.

My question is: Should we separate **entity colors** and **message colors**?
A quick and dirty solution could be:
```py
# messages/message_colors.py

from core import GAME_NAME

if GAME_NAME == 'csgo':
    WHITE = '\x01'
    # more...

else:
    from colors import WHITE
    # more...
```
This could all be done in a much cleaner way using data files etc. so conflicts don't occur, of course. Is something in the works for this? If not, I could try to figure out a way.

I personally think it should be integrated, so scripters don't have to think about how to color their messages, but simply do it in a standard way.

**Comment by Ayuto** [comment]
I like the idea. Do you want to create a PR for this? The quick and dirty solution would be fine. Though, I would put it in ``messages/colors/saytext2.py``. Just in case we add that for other messages as well.

**Comment by backraw** [comment]
Alright, I'll get on it asap. Is SayText2 the only one affected by this currently?

**Comment by backraw** [comment]
My other idea was to change the `Color` class to have a `SayText2` or `saytext2` property returning the correct value. Example:

```python
from colors import RED
from messages import SayText2

# change player color
player.color = RED

# send red SayText2 message
SayText2(f'{RED.saytext2}This is a red message!').send(player.index)
```

Maybe this is the ultimate goal. Still not sure how to do it. When I did it, the colors module became very bloated with unnecessary code - maybe we should add data files and change the C++ module directly, or add the properties after the class definition somehow. But that's a topic for another day, I think.
