### ISSUE TITLE
CSGO: player.get_view_player() crash on linux dedicated server

### ISSUE THREAD

**Issue by KhaimovMR** [Source-Python-Dev-Team/Source.Python#258]
Code, to reproduce:
```python
from players.entity import Player
from events.hooks import PreEvent

@PreEvent('weapon_fire')
def on_weapon_fire(event):
	player = Player.from_userid(event['userid'])

	if player.get_view_player():
		player.view_coordinates = player.view_player.eye_location
```
The problem only comes out when this code executes on `PreEvent`. Everything works fine If we change `PreEvent` to `Event`. If not - dedicaded linux server is crashing.

The crash is occurred on the line:
```python
	if player.get_view_player():
```

**Comment by Ayuto** [comment]
PreEvent is using a hook internally. So, it's actually the same problem like issue #233 and #157.
