### ISSUE TITLE
make_object can cause crash

### ISSUE THREAD

**Issue by Velocity-plus** [Source-Python-Dev-Team/Source.Python#265]
Using make_object in the wrong place can cause a crash. If I put the variable 'other' after the if statement it won't crash. This could be related to that make_object couldn't convert the memory pointer and in that case there should be an error handler which prevents a crash (it is too fragile to mess around with).

```
IMPORTANT: Please copy the full output.
--------------------------------------------------------
Checksum      : 5a60a1bae2f27f62a5aa05e68b7c835b
Date          : 2018-11-27 21:13:22.564059
OS            : Linux-4.15.0-38-generic-x86_64-with-debian-buster-sid
Game          : csgo
SP version    : 667
Github commit : 4b4d6a886456e7f59793af7ca0a9d2f098683b78
Server plugins:
   00: Source.Python, (C) 2012-2018, Source.Python Team.
   01: Metamod:Source 1.10.7-dev
SP plugins:
   00: hook
--------------------------------------------------------

```

```python
# Source.Python
from memory import make_object
from entities.entity import BaseEntity
from entities.hooks import EntityPreHook, EntityCondition

is_teleport = EntityCondition.equals_entity_classname('trigger_teleport')
@EntityPreHook(is_teleport, 'touch')
def pre_touch_teleport(stack_data):
	base_entity = make_object(BaseEntity, stack_data[0]) # Doesn't crash
	other = make_object(BaseEntity, stack_data[1]) # Will crash
	if 'trigger_teleport' in base_entity.classname:
		pass


# A temporary fix would be
@EntityPreHook(is_teleport, 'touch')
def pre_touch_teleport(stack_data):
	base_entity = make_object(BaseEntity, stack_data[0]) 
	if 'trigger_teleport' in base_entity.classname:
		return


         other = make_object(BaseEntity, stack_data[1]) # This is ok as long as the classname is ok.

   
```

**Comment by jordanbriere** [comment]
> This could be related to that make_object couldn't convert the memory pointer and in that case there should be an error handler which prevents a crash (it is too fragile to mess around with).

This is there already. If you try to make an object from an invalid Pointer, a RuntimeError will be raised. For example:

```python
entity = make_object(BaseEntity, Pointer(123456789))
```

Would results into:

```
[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\file.py", line 53, in <module>
    entity = make_object(BaseEntity, Pointer(123456789))

RuntimeError: Access violation - no RTTI data!
```

If you don't get that exception, that means the passed pointer is valid for that class as it is carrying the correct run-time type info and Boost was able to cast it as such. Also, if the passed Pointer wasn't an entity, it would raise later when trying to find an index to instantiate the entity class.

That being said, the memory module is low-level stuff that should be used carefully and there is really so much that can be done as an API standpoint to prevent users from crashing their server.
