### ISSUE TITLE
Server Crash on load because of importing HookUserMessage

### ISSUE THREAD

**Issue by Frag1337** [Source-Python-Dev-Team/Source.Python#269]
Hello,

just found out that my Windows CS:S server crashes when importing HookUserMessage.

You can recreate it by making a test plugin and fill it with:

    from messages.hooks import HookUserMessage

sp info:

    --------------------------------------------------------
    Checksum      : 0f7b442c46acbdcf48f47508c5812854
    Date          : 2018-12-31 07:27:02.080466
    OS            : Windows-10-10.0.17134
    Game          : css
    SP version    : 676
    Github commit : 434ef35ccc11a679b4181a1942bd241795f15b92
    Server plugins:
       00: Metamod:Source 1.11.0-dev+1116
       01: Source.Python, (C) 2012-2018, Source.Python Team.
       02: Tickrate_Enabler 0.4, Didrole
    SP plugins:
       00: game_description_override, 1.0, http://steamcommunity.com/profiles/76561198063282915
       01: bad_setlocalangles_fix, 1.0, https://forums.sourcepython.com/viewtopic.php?f=7&t=1058
       02: dissolver, 1.3, http://forums.sourcepython.com/viewtopic.php?f=7&t=1101
       03: idle_kicker, 1.0,
    --------------------------------------------------------

Havent tested it on linux yet.

**Comment by Ayuto** [comment]
Works fine for me. Could you please try to reproduce the crash without all the server and SP plugins?

**Comment by Frag1337** [comment]
Seems to be an issue with sourcemod. (Only works without sourcemod loaded)

Not sure if it helps but here is the sourcemod dump:
[3fdd0f9d-f783-44cf-9df0-21b7460e5fa4.zip](https://github.com/Source-Python-Dev-Team/Source.Python/files/2718066/3fdd0f9d-f783-44cf-9df0-21b7460e5fa4.zip)

**Comment by Frag1337** [comment]
any updates on this?

**Comment by Ayuto** [comment]
No, I haven't tested it yet.

**Comment by Ayuto** [comment]
Sorry for the delay. I just tested it and I'm unable to reproduce the crash with the latest version of MM, SM and SP.
