### ISSUE TITLE
windows csgo client as server with sp launch

### ISSUE THREAD

**Issue by Battleweaver** [Source-Python-Dev-Team/Source.Python#270]
Greetings.
Windows.
I launch CS:GO client through steam with -insecure option.
Till and including SP version 677(2018 december 15 buildbot release) everything works fine.

When I try to download SP from http://downloads.sourcepython.com/ I see the following info:
Version:        676
Date:           December-30-2018
AND launching CS:GO client with -insecure option just fails and closes CS:GO client.
No ideas about collecting logs. All I have is black screen and CSGO icon disappears from taskbar.
Any tips which version of Source Python is correct and what to do in future?

**Comment by Ayuto** [comment]
http://downloads.sourcepython.com/ is correct. The build from the buildbot has a higher version number (because some builds failed due to internet connection), but it's one commit behind http://downloads.sourcepython.com/. 

I will check your issue this weekend.

**Comment by Ayuto** [comment]
I cannot reproduce the issue. It loads fine for me.

Could you please add ``-condebug`` to your command line. It will generate a ``console.log`` that should provide some more information.

**Comment by Battleweaver** [comment]
Doublechecked today. 
I also can't reproduce bug. Everything works fine.
I think, time to close issue.
