### ISSUE TITLE
Creating effects issues

### ISSUE THREAD

**Issue by BrutalCSkakan** [Source-Python-Dev-Team/Source.Python#271]
Hello! 
I might be doing something wrong, but I seem to get this error from the console when I try to do the following code:

vector1 = Vector(*player.origin)
vector2 = Vector(*player.view_coordinates)
box(player, vector1, vector2, color=Color(255, 255, 255, 255))

I get the console error:
GetSpriteAxes: Bad sprite type -1082148226

I guess that I dont have the sprite, but how can I even define what sprite should be used?

**Comment by BrutalCSkakan** [comment]
I guess I found some issues from the repo that probably solved my problems

**Comment by Ayuto** [comment]
You need to define a model via the additional keyword arguments.
