### ISSUE TITLE
Server TF2 crash `run_command` (Windows)

### ISSUE THREAD

**Issue by Sam839** [Source-Python-Dev-Team/Source.Python#280]
Server TF2 (Windows) crash.
Error: In file `source-python\data\source-python\entities\orangebox\tf\CBasePlayer.ini`
Fix: Need replace `offset_linux = 423` to `offset_linux = 422`
Question: What the hell? Linux? (I checked more than once)

**Comment by Ayuto** [comment]
I highly doubt this would fix the issue if your server is running on Windows. Could you please post the output of ``sp info`` and run the following plugin?
```python
from core import PLATFORM

print(PLATFORM)
```

**Comment by Sam839** [comment]
`sp info`
--------------------------------------------------------
Checksum      : 7293142cef0c8f7205ea09e826d9382d
Date          : 2019-08-06 15:35:10.878548
OS            : Windows-10-10.0.18362
Game          : tf2
SP version    : 691
Github commit : 4d827210579479b15ac622e04ebd6cbde6143594
Server plugins:
   00: Metamod:Source 1.11.0-dev+1127
   01: Source.Python, (C) 2012-2019, Source.Python Team.
SP plugins:
   00: BadSetLocalAnglesFixer
   01: AdvancedBunnyHop
   02: AntiAutoKick
   03: InstantReSpawn
   04: UTF8
   05: TauntMusicChanger
   06: VoiceMod
   07: SprayChanger
   08: RealisticCamera
--------------------------------------------------------

`from core import PLATFORM; print(PLATFORM)` = `windows`

**Comment by Sam839** [comment]
When using SourceMod, this error appears. It is still unknown what is the reason (Probably a broken class (vTable)).

**Comment by jordanbriere** [comment]
> When using SourceMod, this error appears. It is still unknown what is the reason (Probably a broken class (vTable)).

CBasePlayer's offsets for TF2 should be updated in this commit: https://github.com/Source-Python-Dev-Team/Source.Python/commit/481661993d989307b863e78631f94f9578a8ea92

Please confirm and close this issue if it is working fine for you. Thanks!
