### ISSUE TITLE
[CSGO] Player objects don't works after update of 2019-11-18

### ISSUE THREAD

**Issue by progre** [Source-Python-Dev-Team/Source.Python#285]
I noticed that all bots on my server no longer have weapons.

for example;

```
player.give_named_item('weapon_elite') # not working
print(player.name) # UnicodeEncodeError: 'ascii' codec can't encode character '\u2606' in position 2: ordinal not in range(128)
```

The cause of the problem looks like yesterday's CS:GO update. And it looks like it points to the wrong address. There may be other similar problems.
Could you fix it?

**Comment by jordanbriere** [comment]
Re-opening this issue as, while the data was confirmed at a binary level, I didn't performs any tests in-game yet. I also suspect the following offsets might need updating as well:

```
Player.assists
Player.mvps
Player.clan_tag
```

> `print(player.name) # UnicodeEncodeError: 'ascii' codec can't encode character '\u2606' in position 2: ordinal not in range(128)`

I am unable to reproduce this error. Could you please provide the output of `sp info`? Also, what is the name that should actually be retrieved?

**Comment by progre** [comment]
> I am unable to reproduce this error.
It maybe includes CJK strings. So this may be another problem.
I'll verify after 4 hours, but if you're curious, you can ignore this problem.

**Comment by progre** [comment]
`print('あ')  # UnicodeEncodeError`
I understood the problem happens with any CJK strings. You can ignore this problem.

Most of my problems were solved by https://github.com/CookStar/Source.Python/commit/d7216ea4198263986b28c34b12788de4237a28c4.
Thank you to the corresponding.

**Comment by jordanbriere** [comment]
Right, the error occurs when printed not when retrieved. I thought you were saying `player.name` alone was using ascii and raising (which was weird, since it is [internally decoded to utf-8](https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/src/core/modules/players/players_wrap.h#L47)). I assume your problem is your default encoding being set to ascii, rather than utf-8. If you load the following code as a plugin, everything should be correctly printed:

```python
import sys

encoding = sys.stdout.encoding

def load():
    sys.stdout.encoding = 'utf-8'

def unload():
    sys.stdout.encoding = encoding
```

**Comment by CookStar** [comment]
As far as tested on Linux, the pre_think and post_think offsets have not changed. https://github.com/Source-Python-Dev-Team/Source.Python/commit/8c906e446a203b528c10a1cf3b9701fbd4cf6080#diff-54e669af5bbfe4847856171573c785da

**Comment by jordanbriere** [comment]
> As far as tested on Linux, the pre_think and post_think offsets have not changed. 8c906e4#diff-54e669af5bbfe4847856171573c785da

Double checked just now and yup, you are right. They haven't changed on Windows either. My first scan showed the insertion in the table was prior that offset, so assumed they did change too. Can you please make a PR to fix those? If not, I will do in a few. Thanks.
