### ISSUE TITLE
Repeat for building menu doesn't stop.

### ISSUE THREAD

**Issue by invisiblesoldiers** [Source-Python-Dev-Team/Source.Python#296]
Repeat on building menu doesn't stop when plugin is unloading or player exit from menu. Only player's disconnect will stop it.
Repeat is still calling but nothing happen. You can view it with log_level >= 4

**Comment by Ayuto** [comment]
Yes, it's a global repeat that handles all players and it's intended. We didn't put much effort in always starting/stopping the repeat, because there isn't much going on behind the scenes, if no menu is active for any player.

**Comment by invisiblesoldiers** [comment]
Well, this really makes diffucult to read logs due to 1.0s spam

**Comment by Ayuto** [comment]
Then we might want to increase the log level for that message or simply remove it. But I don't think changing the implementation is the proper approach to reduce the number of lines in the log file.

**Comment by invisiblesoldiers** [comment]
And what if 10 plugins was unloaded. Does it means that there will be 10 useless repeats?

**Comment by Ayuto** [comment]
No, there is still only one global repeat.
