### ISSUE TITLE
Projectile weapons raising error on IsWeapon

### ISSUE THREAD

**Issue by satoon101** [Source-Python-Dev-Team/Source.Python#298]
CBaseEntityWrapper::IsWeapon() is returning False for Projectile weapons on CS:S (and likely other games).  This is causing an error to be raised when iterating over WeaponIter when any of those entities exists on the server.  Because they exist in the weapon_manager, it tries to get a Weapon instance, and it raises the following error:
```python
[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\packages\source-python\events\listener.py", line 92, in fire_game_event
    callback(game_event)
  File "..\addons\source-python\plugins\gungame\plugins\included\gg_dead_strip\gg_dead_strip.py", line 21, in _strip_weapons
    remove_idle_weapons()
  File "..\addons\source-python\plugins\gungame\core\weapons\helpers.py", line 35, in remove_idle_weapons
    tag for tag in ('tool', 'objective') if tag in weapon_manager.tags
  File "..\addons\source-python\packages\source-python\filters\iterator.py", line 53, in __iter__
    for item in self.iterator():
  File "..\addons\source-python\packages\source-python\filters\weapons.py", line 47, in iterator
    yield Weapon(index_from_edict(edict))
  File "..\addons\source-python\packages\source-python\entities\_base.py", line 127, in __call__
    obj = super().__call__(index)
  File "..\addons\source-python\packages\source-python\weapons\_base.py", line 40, in __init__
    WeaponMixin.__init__(self, index)

ValueError: Index '75' is not a valid weapon.
```

**Comment by jordanbriere** [comment]
Are they all inheriting from `CBaseProjectile`?

**Comment by jordanbriere** [comment]
Upon reflection, I think hard-coding all the possible classes will become redundant and harder to maintain on the long run than using what we already know about:

```cpp
bool CBaseEntityWrapper::IsWeapon()
{
	static object is_weapon = import("weapons").attr("manager").attr("weapon_manager").attr("__contains__");
	return is_weapon(str(IServerUnknownExt::GetClassname(GetThis())));
}
```

**Comment by satoon101** [comment]
Unfortunately, no.  I printed out all of the server_class names for each entity on each game that has projectile weapons support (which is currently only 4 games anyway).  CS:S, CS:GO, and L4D2 all inherit from `CBaseGrenade`.  HL2:DM on the other hand is fairly wonky.  prop_combine_ball, for instance, only has these 3 server classes:
* CPropCombineBall
* CBaseAnimating
* CBaseEntity


Using the weapon manager is a good idea, but the projectiles are stored in weapon_manager.projectiles, not in the main dictionary itself.

**Comment by jordanbriere** [comment]
> Using the weapon manager is a good idea, but the projectiles are stored in weapon_manager.projectiles, not in the main dictionary itself.

I haven't tested yet, but at a code level, `_format_name` seems to take care of that, no?

**Comment by satoon101** [comment]
Oh yeah, good point.  It certainly should.

**Comment by jordanbriere** [comment]
If you have a chance to test and confirm it fixes the issue, please feel free to push that change. If not, I will do some testings around that most likely tomorrow night.

**Comment by satoon101** [comment]
Yes, it worked like a charm, thank you!
