### ISSUE TITLE
VectorVectors

### ISSUE THREAD

**Issue by invisiblesoldiers** [Source-Python-Dev-Team/Source.Python#300]
What about to wrap the function from source-sdk 2013 mathlib

```c++
void VectorVectors( const Vector &forward, Vector &right, Vector &up )
{
	Assert( s_bMathlibInitialized );
	Vector tmp;

	if (forward[0] == 0 && forward[1] == 0)
	{
		// pitch 90 degrees up/down from identity
		right[0] = 0;	
		right[1] = -1; 
		right[2] = 0;
		up[0] = -forward[2]; 
		up[1] = 0; 
		up[2] = 0;
	}
	else
	{
		tmp[0] = 0; tmp[1] = 0; tmp[2] = 1.0;
		CrossProduct( forward, tmp, right );
		VectorNormalize( right );
		CrossProduct( right, forward, up );
		VectorNormalize( up );
	}
}
```

**Comment by Ayuto** [comment]
Just curious: for what do you need this?

Also, it would be great if you could always add a link to the source instead of just copying the source:
https://github.com/alliedmodders/hl2sdk/blob/0ef5d3d482157bc0bb3aafd37c08961373f87bfd/mathlib/mathlib_base.cpp#L500-L523

**Comment by invisiblesoldiers** [comment]
For some movement math.

**Comment by vinci6k** [comment]
While you're at it, could you also wrap [VectorAngles](https://github.com/alliedmodders/hl2sdk/blob/0ef5d3d482157bc0bb3aafd37c08961373f87bfd/mathlib/mathlib_base.cpp#L1002) and [AngleVectors](https://github.com/alliedmodders/hl2sdk/blob/0ef5d3d482157bc0bb3aafd37c08961373f87bfd/mathlib/mathlib_base.cpp#L921)?

**Comment by invisiblesoldiers** [comment]
> While you're at it, could you also wrap [VectorAngles](https://github.com/alliedmodders/hl2sdk/blob/0ef5d3d482157bc0bb3aafd37c08961373f87bfd/mathlib/mathlib_base.cpp#L1002) and [AngleVectors](https://github.com/alliedmodders/hl2sdk/blob/0ef5d3d482157bc0bb3aafd37c08961373f87bfd/mathlib/mathlib_base.cpp#L921)?

AngleVectors is alredy here.
http://wiki.sourcepython.com/developing/modules/mathlib.html?highlight=get_angle#mathlib.QAngle.get_angle_vectors

**Comment by vinci6k** [comment]
Dang, can't believe I missed that while searching for it. Thanks for pointing it out to me!

**Comment by invisiblesoldiers** [comment]
I noticed that the vector does not support the unary operator?

```python
v = Vector(5.0, 5.0, 5.0)
v + -v = Vector(0.0, 0.0, 0.0)
```
