### ISSUE TITLE
SourceMod's Accelerator incompatibility

### ISSUE THREAD

**Issue by jordanbriere** [Source-Python-Dev-Team/Source.Python#321]
Thanks, that solved my problem.

@jordanbriere I found another bug which crashes my server.

So I have sourcemod installed and if I load the following plugin. (Yes, just 1 line)

`from messages.hooks import HookUserMessage`

it crashes my server upon writing in-game "!admin" or "!rcon", literally anything whats sourcemod related.

(I tested both, the current hooks.py & your updated hooks.py, the result was the same)

Minidump, if it helps:

[crash_var45l7mon2k.zip](https://github.com/Source-Python-Dev-Team/Source.Python/files/4526032/crash_var45l7mon2k.zip)

_Originally posted by @Frag1337 in https://github.com/Source-Python-Dev-Team/Source.Python/issues/314#issuecomment-618741349_

**Comment by jordanbriere** [comment]
What's the output of `sm plugins list`? I'm unable to reproduce a crash and it works fine for me with a vanilla installation of MM, SM and SP without any plugins installed beside the line you mentioned above.

**Comment by Frag1337** [comment]
Hey,

I figured out now, that it's not the fault of a plugin. (You need to have the base plugins from sourcemod loaded.)

The cause of the crash is an extension for sourcemod, called [**Accelerator - Crash Reporting That Doesn't Suck**](https://forums.alliedmods.net/showthread.php?t=277703&). I thought thats a pretty neat extension to figure out random crashes, but for now I could just disable it to prevent crashes. Ofcourse I would prefer a fix for it, since its very helpful.

Sorry for the late answer.

**Comment by jordanbriere** [comment]
It crashes [here](https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/messages/hooks.py#L214) when the pointer is being wrapped as an `IRecipientFilter`. It should normally raise a `RuntimeError`, because that pointer doesn't have RTTI, as per #314, but that extension appears to prevent Boost's from handling the exception and just process with the crash anyway. I believe this happens [here](https://github.com/asherkin/accelerator/blob/master/extension/extension.cpp#L296-L302) in their handler. There is not much we can do, as everything that would normally raise an exception (for example, [#312](https://github.com/Source-Python-Dev-Team/Source.Python/issues/312#issuecomment-612888886)) will no longer be prevented if you are using that extension.

**Comment by Frag1337** [comment]
Thanks for the investigation. Your efforts are very appreciated. 

I will simply just move on, since as you said, theres not much we can do.

I will close this for now.

**Comment by Ayuto** [comment]
We might want to add a note to our compatibility page.

**Comment by jordanbriere** [comment]
> 
> 
> We might want to add a note to our compatibility page.

Added into [554d5ed](https://github.com/Source-Python-Dev-Team/Source.Python/commit/554d5edf9780d55772459b2e1d7b90595c3b1a35).
