### ISSUE TITLE
[TF2] Crash when creating entity.

### ISSUE THREAD

**Issue by Sam839** [Source-Python-Dev-Team/Source.Python#336]
```
--------------------------------------------------------
Checksum      : 7c36b9194739d27c9aa0c969997c4da4
Date          : 2020-05-29 14:48:28.237797
OS            : Windows-10-10.0.18362
Game          : tf2
SP version    : 696
Github commit : 268d1d7b1a46946133bc6df5ccf46687a718917c
Server plugins:
   00: Source.Python, (C) 2012-2020, Source.Python Team.
SP plugins:
   00: Test
--------------------------------------------------------
```
`ent = Entity.create('prop_dynamic') # After that comes crash`

**Comment by jordanbriere** [comment]
Works fine for me:

```python
from entities.entity import Entity

ent = Entity.create('prop_dynamic')
print(ent.classname)
```

```
sp info;sp plugin load testing

IMPORTANT: Please copy the full output.
--------------------------------------------------------
Checksum      : 38a37230088a25638378a8e56ef171d3
Date          : 2020-05-29 16:17:15.818228
OS            : Windows-10-10.0.18362
Game          : tf2
SP version    : 696
Github commit : 268d1d7b1a46946133bc6df5ccf46687a718917c
Server plugins:
   00: Source.Python, (C) 2012-2020, Source.Python Team.
SP plugins:
--------------------------------------------------------

[SP] Loading plugin 'testing'...
prop_dynamic
[SP] Successfully loaded plugin 'testing'.
```

**Comment by Sam839** [comment]
I will analyze the dump and all modules and try to find a reason for this

**Comment by Sam839** [comment]
1. I completely reinstalled SP but, surprisingly, the checksum and time does not match yours
```
--------------------------------------------------------
Checksum      : 316dede1eb539a461085685fd0a9505b
Date          : 2020-05-29 21:13:53.492316
OS            : Windows-10-10.0.18362
Game          : tf2
SP version    : 696
Github commit : 268d1d7b1a46946133bc6df5ccf46687a718917c
Server plugins:
   00: Source.Python, (C) 2012-2020, Source.Python Team.
SP plugins:
--------------------------------------------------------
```
2. I did part of the analysis (it would be nice if will be pdb in future builds) and I found an error (Exception...).

Dump & Analyze (mdmp + idb): [Google Disk](https://drive.google.com/file/d/1W2Hmqj-PJ9H0Sg4LnpTAaa9c7jwy6fef/view)
Error: ```core.dll + 0x219317 = 0x5A4D9317```
Error (Assembler): ```mov ecx, [esi]```

**Comment by jordanbriere** [comment]
>     1. I completely reinstalled SP but, surprisingly, the checksum and time does not match yours

It will never be the same, because that is the time at which the info was printed and the checksum is based on the whole output. Are you loading that plugin via autoexec.cfg? If so, then that is your issue. You cannot create entities unless there is a map running.

**Comment by Sam839** [comment]
Can I record a video of how the server starts and how I loading the plugin with one line of code?
(Do you think I don't know about such simple things?...)

**Comment by jordanbriere** [comment]
Huh. No need to be offended. It had to be asked to eliminate that possibility. But hey, good luck.

**Comment by Sam839** [comment]
I’m not offended (it’s hard to offend a person with manic syndrome). I'm waiting a reason for this error. It will be good if I get pdb.

**Comment by Sam839** [comment]
I found out the error and fixed it. Thanks for the help -w-

**Comment by Ayuto** [comment]
Do you perhaps want to share the solution to your error?

**Comment by Sam839** [comment]
RAM was not enough for the server

**Comment by Sam839** [comment]
I forgot to remove the limitation on RAM due to which an error was caused. (My fault xD)
