### ISSUE TITLE
Keyvalues / properties from data files return incorrect color values.

### ISSUE THREAD

**Issue by vinci6k** [Source-Python-Dev-Team/Source.Python#346]
Running the following script on dm_runoff in HL2DM:
```py
# ../fog_test/fog_test.py

# Source.Python
from entities.entity import Entity


fog = Entity.find('env_fog_controller')
prop_color = fog.get_property_color('m_fog.colorSecondary')


print(f'prop: {prop_color}\nkeyv: {fog.fog_color2}')
```
Gives these results: 
```
prop:FFFFFF00
keyv:FF95FF00
```

When I added `m_fog.colorSecondary` to CFogController.ini, I was getting the raw color value (long) instead of a Color instance. 
So then I hardcoded the property to use Color as the type - turns out that returns the same value as the above mentioned keyvalue.

**Comment by Ayuto** [comment]
Looks like the keyvalues doesn't provide what we expect:
```python
from entities.entity import Entity

fog = Entity.find('env_fog_controller')

print('prop:', fog.get_property_color('m_fog.colorSecondary'))
print('keyv:', fog.fog_color2)
print('dmap:', fog.get_datamap_property_color('m_fog.colorSecondary'))
print('nwrk:', fog.get_network_property_color('m_fog.colorSecondary'))
print('kstr:', fog.get_key_value_string('fogcolor2'))
print('kclr:', fog.get_key_value_color('fogcolor2'))
```
Output:
```
prop:FFFFFF00
keyv:FFC5FF00
dmap:FFFFFF00
nwrk:FFFFFF00
kstr: 16777215 10863813 16777215 1140457472
kclr:FFC5FF00
```
The kstr line is interpreted here:
https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/src/core/modules/entities/entities_entity.cpp#L393-L403

I will take a deeper look later as I'm in hurry, currently.
