### ISSUE TITLE
Two instances of Model class with the same model path cause an error

### ISSUE THREAD

**Issue by olegtsvetkov** [Source-Python-Dev-Team/Source.Python#35]
This code:
```python
from engines.precache import Model

test_model = Model('models/player/t_leet.mdl')
test_model2 = Model('models/player/t_leet.mdl')
```
produces this error on load:
```
[SP] Loading plugin 'testik'...

[SP] Caught an Exception:
Traceback (most recent call last):
  File '..\addons\source-python\packages\source-python\plugins\manager.py', line 72, in __missing__
    instance = self.instance(plugin_name, self.base_import)
  File '..\addons\source-python\packages\source-python\plugins\instance.py', line 82, in __init__
    self._plugin = import_module(import_name)
  File '..\addons\source-python\plugins\testik\testik.py', line 4, in <module>

    test_model2 = Model('models/player/t_leet.mdl')
  File '..\addons\source-python\packages\source-python\engines\precache.py', line 75, in __init__
    event_registry.register_for_event('server_spawn', self._server_spawn)
  File '..\addons\source-python\packages\source-python\events\manager.py', line 65, in register_for_event
    self[event].append(callback)
  File '..\addons\source-python\packages\source-python\events\listener.py', line 63, in append
    'for event '{1}''.format(callback, self.event))

ValueError: Event callback '<bound method Model._server_spawn of Model('models/player/t_leet.mdl')>' is already registered for event 'server_spawn'


[SP] Plugin 'testik' was unable to be loaded.
```
Probably there is the same problem with Generic and Decal classes.

Tested only on CS:S Windows server with Jan 15 build.

**Comment by satoon101** [comment]
That is an odd one.  Thank you for reporting, we will look into it.

**Comment by olegtsvetkov** [comment]
I've also found, that using `download` argument cause a type error.
Code: ~~(yes, it's a standard model, but I have the same error with any other model)~~
```python
Model('models/player/ct_gign.mdl', True)
```
Error:
```
[SP] Caught an Exception:
Traceback (most recent call last):
  File '..\addons\source-python\packages\source-python\plugins\manager.py', line 72, in __missing__
    instance = self.instance(plugin_name, self.base_import)
  File '..\addons\source-python\packages\source-python\plugins\instance.py', line 82, in __init__
    self._plugin = import_module(import_name)
  File '..\addons\source-python\plugins\ns_test\ns_test.py', line 20, in <module>
    Model('models/player/ct_gign.mdl', True),

TypeError: str() argument 2 must be str, not bool
```

CS:S, Windows, Jan 17 (or maybe 15) build.

**Comment by satoon101** [comment]
Not at home to test myself, but try using download as a keyword instead:
```python
Model('models/player/ct_gign.mdl', download=True)
```

**Comment by olegtsvetkov** [comment]
Same traceback, but other error:
```
TypeError: 'download' is an invalid keyword argument for this function
```

**Comment by Ayuto** [comment]
Can you show us the whole test script? I'm actually a bit confused why it says "function". The error should rather look like this.
```
TypeError: __init__() got an unexpected keyword argument 'download'
```

**Comment by olegtsvetkov** [comment]
```python
from engines.precache import Model

model = Model('models/player/ct_gign.mdl', download=True)
```

**Comment by invincibleqc** [comment]
Was able to fix the error adding the following to _PrecacheBase:
```python
    def __new__(cls, path, download=False):
        return super().__new__(cls, path)
```
Problem seems to be Path passing the given keywords to some random functions.

**Comment by olegtsvetkov** [comment]
What about `download` argument?

**Comment by invincibleqc** [comment]
The download argument is only needed on __init__.

**Comment by invincibleqc** [comment]
As for the main issue, the problem is that ```list.__contains__``` is returning True if the given element is __equaling__ rather than __beeing__ an already appened element. After some testing, it seems that ```__equals__```  is returning True for bound methods of an immutable object (in our case, since Model is inheriting of Path which inherits of str) even though they are bound to different instances of the same class.

```python
class foo(str):
    def bar(self):
        pass
        
x, y = foo('blah'), foo('blah')
print('x.bar == y.bar:', x.bar == y.bar)
print('x.bar is y.bar:', x.bar is y.bar)

blah = list()
blah.append(x.bar)
print('y in blah:', y.bar in blah)
print('id(y) in map(id, blah):', id(y) in map(id, blah))
``` 
Result:
``` python
x.bar == y.bar: True
x.bar is y.bar: False
y in blah: True
id(y) in map(id, blah): False
```

**Comment by Ayuto** [comment]
A bit late, but here is the fix. _PrecacheBase does not inherit from Path anymore. I don't think having Path objects is a benefit here.

**Comment by satoon101** [comment]
While I don't disagree with removing the Path inheritance, I think it should at least inherit from string.  Though, obviously that would leave us with the same issue.  The main purpose, though, is that you can pass the object itself when wanting to use the string form of it.  The current fix actually breaks our set_model method for BaseEntity.  We obviously could just pass model._path, but I think passing just the model looks nicer.

**Comment by Ayuto** [comment]
I think writing "model.path" isn't a bad idea, because that would create consistency with the "index" property.

**Comment by satoon101** [comment]
That is probably the best compromise, as I don't know how else we would fix the issue here.

**Comment by Ayuto** [comment]
Alright, I will go ahead and make that change.
