### ISSUE TITLE
Why was gamerules discarded?

### ISSUE THREAD

**Issue by CookStar** [Source-Python-Dev-Team/Source.Python#362]
When I tried to introduce gamerules into Source.Python, I found this commit history. https://github.com/Source-Python-Dev-Team/Source.Python/commit/18389d6e45c82c525b371c0f09d5acdbb627c87a

But it seems to have been discarded immediately https://github.com/Source-Python-Dev-Team/Source.Python/commit/2c80297b586a9b0b7e0a3b21bcecf0ce9b3a1084, but what's the reason for that exactly?

If there is no particular reason, I support reintroducing it, but what do you all think?

**Comment by Ayuto** [comment]
IIRC, the public base class we have access to is very limited in functionality. The most interesting parts are located in the game depent implementations like CCSGameRules. I guess that's why I discarded it two days later.

**Comment by CookStar** [comment]
> IIRC, the public base class we have access to is very limited in functionality. The most interesting parts are located in the game depent implementations like CCSGameRules. I guess that's why I discarded it two days later.

That's for sure.

However, I think it would be useful to provide a pointer to the user, or to get the gamerules property correctly, wouldn't it?
https://forums.sourcepython.com/viewtopic.php?t=1795

How to get the property correctly currently.
```python
def get_total_rounds_played()
    proxy = BaseEntity.find_or_create("cs_gamerules")
    
    cls = proxy.server_class
    while cls:
        for prop in cls.table:
            if "gamerules_data" not in prop.name:
                continue
    
            game_rules = prop.data_table_proxy_function(None, None, None, None, 0)
    
            for data_table in prop.data_table:
                if data_table.name == "m_totalRoundsPlayed":
                    return game_rules.get_int(data_table.offset)
            break
    
        cls = cls.next
```

I think these can be moved to the C++ side.

**Comment by Ayuto** [comment]
Ideally, we would have a generic solution, but that seems to be a little bit complicated. Moreover, it seems like game rules uses the only data table proxy function that actually returns a different pointer. All the other ones just seem to modify the recipients (team only or just send the table to the local player, etc.).
