### ISSUE TITLE
[L4D2] Crash when map loaded

### ISSUE THREAD

**Issue by Pinsplash** [Source-Python-Dev-Team/Source.Python#368]
SP works fine when a map isn't loaded, but when any map is loaded it crashes ~80% of the way through. Only other plugins are MetaMod and SourceMod, regular install of everything.

Happens on listen and dedicated.

**Comment by jordanbriere** [comment]
Did https://github.com/Source-Python-Dev-Team/Source.Python/commit/cde9313fc80b8c4f1755175ebb246c4d621fffba fix that issue?

**Comment by Pinsplash** [comment]
yep
