### ISSUE TITLE
PlayerEntity (BaseEntity) doesn't update itself

### ISSUE THREAD

**Issue by olegtsvetkov** [Source-Python-Dev-Team/Source.Python#37]
If I save PlayerEntity of some player (BaseEntity of some entity), then all it's properties will not be updated if something "outside" will change them. Before entities update it works fine...

I have a simple plugin, which gives me 100HP when I type something in chat:
```python
from events import Event
from players.entity import PlayerEntity

player = None

@Event
def player_say(event):
    global player

    if player is None:
        player = PlayerEntity(index_from_userid(event.get_int('userid')))

    player.health += 100
```
Let's say I got 300HP (total) and died, but then if I type something in chat **only one time** after respawn I will get 400HP (300 that was before death + 100 new), instead of 200HP (100 from spawn + 100 new). Same for all other properties (tested with speed, gravity and cash).

I can be wrong, but I think it can be a problem with BaseEntity.pointer...

CSS, Jan 15 build

**Comment by satoon101** [comment]
Can you please confirm that the update @invincibleqc committed fixes your issue?  It was an issue we had previously that was fixed the same way, so I imagine it did, but just want verification.

**Comment by invincibleqc** [comment]
I was able to replicate it and confirmed it does fix it.
