### ISSUE TITLE
Menu exception 

### ISSUE THREAD

**Issue by NosferatuJoe** [Source-Python-Dev-Team/Source.Python#390]
I encountered an exception with the menus, not sure if it's a big issue but thought to report it nevertheless.

```
2021-03-26 19:48:01 - sp	-	EXCEPTION	
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/commands/auth.py", line 44, in __call__
    return self.callback(*args)
  File "../addons/source-python/packages/source-python/menus/queue.py", line 267, in _menuselect_callback
    _radio_queues[index]._select(choice)
  File "../addons/source-python/packages/source-python/menus/queue.py", line 126, in _select
    next_menu = active_menu._select(self._index, choice)
  File "../addons/source-python/packages/source-python/menus/radio.py", line 113, in _select
    self._player_pages[player_index].options[choice_index])

KeyError: 1
```

I might've been using the adaptive radar plugin from the forums though, not sure if it was turned on or off.

**Comment by jordanbriere** [comment]
Could you please provide a reproducible code? That traceback is rather ambiguous, as there is no way to tell if the missing key is the player index or the selected option..

**Comment by vinci6k** [comment]
He mentioned he was might've been using the [adaptive radar](https://forums.sourcepython.com/viewtopic.php?f=37&t=2472#p15224) plugin, so I have a feeling this might be causing issues with menus created by SourceMod plugins:
```py
@ClientCommand('menuselect')
def menu_select(command, index):
    """Called when the player selects an option in the menu."""
    # Did the player close their menu?
    if SimpleMenu.get_user_queue(index).active_menu is None:
        PlayerAR(index).show_radar()
```
I'll see if I can reproduce it in a few minutes.

**Comment by vinci6k** [comment]
Ran into a small issue:
```
[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\packages\source-python\messages\hooks.py", line 188, in _pre_send_user_message
    buffer = make_object(ProtobufMessage, args[3])

RuntimeError: Access violation - no RTTI data!
```
That happens whenever a menu is created/sent by SourceMod.

**Comment by jordanbriere** [comment]
> 
> 
> Ran into a small issue:
> 
> ```
> [SP] Caught an Exception:
> Traceback (most recent call last):
>   File "..\addons\source-python\packages\source-python\messages\hooks.py", line 188, in _pre_send_user_message
>     buffer = make_object(ProtobufMessage, args[3])
> 
> RuntimeError: Access violation - no RTTI data!
> ```
> 
> That happens whenever a menu is created/sent by SourceMod.

That's likely part of the issue, actually. I currently don't have the time, or an up-to-date environment for that game to dig deeper, but the solution would be similar to what was suggested into #140. Feel free to play around with it and make a PR if you get it to work.

**Comment by vinci6k** [comment]
Will do as soon as I get back!
