### ISSUE TITLE
Server crashing on startup 

### ISSUE THREAD

**Issue by NorthernLuff** [Source-Python-Dev-Team/Source.Python#392]
Greetings! I'm attempting to start my CS:S server with sourcepython installed, but it crashes upon start.

Basic info:
The server files have been downloaded off of steamcmd
No add-on or modification is installed aside from sourcepython
VCredist 2010 is installed
OS: Windows 8.1.
SourcePython version: 704

Console.log outputs this

```
" [Source.Python] Loading...
Missing shutdown function for sv.Init( bDedicated ) : sv.Shutdown()
Missing shutdown function for g_GameEventManager.Init() : g_GameEventManager.Shutdown()
Missing shutdown function for NET_Init( bDedicated ) : NET_Shutdown()
Missing shutdown function for Key_Init() : Key_Shutdown()
Missing shutdown function for Filter_Init() : Filter_Shutdown()
Missing shutdown function for saverestore->Init() : saverestore->Shutdown()
Missing shutdown function for COM_Init() : COM_Shutdown()
Missing shutdown function for V_Init() : V_Shutdown()
Missing shutdown function for g_pCVar->Init() : g_pCVar->Shutdown()
Missing shutdown function for Cmd_Init() : Cmd_Shutdown()
Missing shutdown function for Cbuf_Init() : Cbuf_Shutdown()
Missing shutdown function for Con_Init() : Con_Shutdown()
Missing shutdown function for Memory_Init() : Memory_Shutdown()
Missing shutdown function for Host_Init( s_bIsDedicated ) : Host_Shutdown()
Missing shutdown function for Sys_InitMemory() : Sys_ShutdownMemory()
Missing shutdown function for Sys_Init() : Sys_Shutdown()
Missing shutdown function for COM_InitFilesystem( info.m_pInitialMod ) : COM_ShutdownFileSystem()"
```

I'm confused as to what this might mean. 
Thanks in advance.

**Comment by jordanbriere** [comment]
Are you sure you installed the right [build for that game](http://downloads.sourcepython.com/)? If so, please add the following option to your launch command:

```
+developer 1
```

This should generate more messages after `[Source.Python] Loading...` possibly giving more hints about the issue.

**Comment by NorthernLuff** [comment]
Yup. I'm sure. Okay, so after adding +developer 1, the results changed a bit. Earlier, the server window would just disappear and shut down, now i get a "program has stopped working"windows msg. Anyhow, I'm attaching the console.log file to this message. Fingers crossed. 
[console.log](https://github.com/Source-Python-Dev-Team/Source.Python/files/6384774/console.log)

**Comment by jordanbriere** [comment]
> 
> 
> Yup. I'm sure. Okay, so after adding +developer 1, the results changed a bit. Earlier, the server window would just disappear and shut down, now i get a "program has stopped working"windows msg. Anyhow, I'm attaching the console.log file to this message. Fingers crossed.
> [console.log](https://github.com/Source-Python-Dev-Team/Source.Python/files/6384774/console.log)

Seems to crash when reconnecting the streams. My first guess would be that you don't have `-console` in your launch command and is using the builtin launcher.

**Comment by jordanbriere** [comment]
Please try the following fix: [source-python-392.zip](https://drive.google.com/file/d/1PS8vBw8e0qA6DwNAnqZWlUSkioV3erKG/view?usp=sharing)

**Comment by NorthernLuff** [comment]
Got it! Your guess was correct. I was using the built-in launcher. As soon as i tried starting the server with the "-console"-launch command, it was solved. I didn't know you weren't able to use them together. Thanks a lot for your help.

**Comment by jordanbriere** [comment]
> 
> 
> Got it! Your guess was correct. I was using the built-in launcher. As soon as i tried starting the server with the "-console"-launch command, it was solved. I didn't know you weren't able to use them together. Thanks a lot for your help.

You should be able to. However, a fix for a different issue that affects some Windows version (#175) is causing the streams to be reconnected to non-allocated channels when launching a dedicated server without a console. This is an oversight, and I've added a simple check just now that will check for the presence of the `-console` option which should make it work properly going forward: https://github.com/Source-Python-Dev-Team/Source.Python/blob/dfc2c284c0282d17063afa94c1a04a3bf4de7a7a/src/core/sp_python.cpp#L196-L197
