### ISSUE TITLE
[SP] Caught an Exception base.py

### ISSUE THREAD

**Issue by Nummee** [Source-Python-Dev-Team/Source.Python#398]
2021-05-20 14:37:03 - sp	-	EXCEPTION	
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/entities/_base.py", line 132, in __call__
    obj = super().__call__(index)
  File "../addons/source-python/packages/source-python/entities/_base.py", line 199, in __init__
    super().__init__(index)

ValueError: Conversion from "Index" (79) to "BaseEntity" failed.

         IMPORTANT: Please copy the full output.
         --------------------------------------------------------
         Checksum      : 453a4456332e211cccb4d6a4c027aed1
         Date          : 2021-05-20 12:40:58.433239
         OS            : Linux-3.10.0-1127.13.1.el7.x86_64-x86_64-with-centos-7.8.2003-Core
         Game          : css
         SP version    : 704
         Github commit : bcea09ef14a15cefdc4a5bd01a1521337af06879
         Server plugins:
            00: Metamod:Source 1.11.0-dev+1144
            01: Source.Python, (C) 2012-2020, Source.Python Team.
         SP plugins:
            00: gungame, 1.3.2, https://forums.sourcepython.com/viewtopic.php?t=1621

**Comment by jordanbriere** [comment]
This exception means that a plugin tried to retrieve an `Entity` instance from an index that was not valid (likely removed by that point). Without the full traceback I cannot tell you more about its exact origin, but this is not a Source.Python issue per se. I would suggest you look into which plugin threw it and report the problem to their authors so they can silence/handle it better if needs be.

Thanks!
