### ISSUE TITLE
The imported project "C:\Microsoft.Cpp.Default.props" was not found

### ISSUE THREAD

**Issue by ArtichaTM** [Source-Python-Dev-Team/Source.Python#412]
I've been googl-ing it for hour, but found fixes for Visual Studio, but I don't have it...
```
Choose the branch you wish to build against:

   (1) blade
   (2) bms
   (3) csgo
   (4) css
   (5) dods
   (6) gmod
   (7) hl2dm
   (8) l4d2
   (9) tf2

3
Cloning into '.'...
remote: Enumerating objects: 24312, done.
remote: Counting objects: 100% (98/98), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 24312 (delta 20), reused 38 (delta 9), pack-reused 24214 eceiving objects: 100% (24312/24312), 474.38 MiB | 11.06 MiB/s
Receiving objects: 100% (24312/24312), 474.46 MiB | 11.02 MiB/s, done.
Resolving deltas: 100% (11083/11083), done.
Updating files: 100% (3805/3805), done.
Updating files: 100% (5786/5786), done.
Switched to a new branch 'csgo'
Branch 'csgo' set up to track remote branch 'csgo' from 'origin'.
Already up to date.
C:\Source\src\patches\csgo\lib\public\tier1.lib
C:\Source\src\patches\csgo\lib\win32\release\vs2010\libprotobuf.lib
C:\Source\src\patches\csgo\public\networkvar.h
3 File(s) copied
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error in CMakeLists.txt:
  Failed to run MSBuild command:

    C:/Windows/Microsoft.NET/Framework/v4.0.30319/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 4.8.4084.0
    [Microsoft .NET Framework, version 4.0.30319.42000]
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 9/18/2021 11:27:28 PM.
    Project "C:\Source\src\Builds\Windows\csgo\CMakeFiles\3.21.2\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Source\src\Builds\Windows\csgo\CMakeFiles\3.21.2\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
    Done Building Project "C:\Source\src\Builds\Windows\csgo\CMakeFiles\3.21.2\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\Source\src\Builds\Windows\csgo\CMakeFiles\3.21.2\VCTargetsPath.vcxproj" (default target) (1) ->
      C:\Source\src\Builds\Windows\csgo\CMakeFiles\3.21.2\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00.28


  Exit code: 1



-- Configuring incomplete, errors occurred!
See also "C:/Source/src/Builds/Windows/csgo/CMakeFiles/CMakeOutput.log".
Press any key to continue . . .
```
CMakeOutput.log: The system is: Windows - 10.0.19043 - AMD64

I want build #353 , but can't even master. Tried to laucnh from user directory and from c:/

Latest on 18.09.2021:
CMake 2.8
Git
Visual C++ 2010
Microsoft Build Tools (Installed after 2 unsuccessful builds, didn't help btw)

And I found attribute of player, named "set_transmit", but didn't found reference or any information

**Comment by CookStar** [comment]
Looks like your VCTargetsPath is not set correctly.

Try this before you start compiling.
SET VCTargetsPath="C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0"

Also double check that Microsoft.Cpp.Default.props exists in `C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0`.

I've also updated #353 to master, so please fetch it.
If the compilation still does not succeed, try this. [csgo.zip](https://github.com/Source-Python-Dev-Team/Source.Python/files/7190777/csgo.zip)

**Comment by ArtichaTM** [comment]
> Also double check that Microsoft.Cpp.Default.props exists in `C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0`.
Doesn't exist. **Installed**:
```
1. MS C++ 2005 Redistributable x64/x84\
2. MS C++ 2008 Redistributable x64/x84
3. MS C++ 2010 Redistributable x64/x84
4. MS C++ 2012 Redistributable x64/x84
5. MS C++ 2013 Redistributable x64/x84
5. MS C++ 2015-19 Redistributable x64/x84
6. MS C++ 2015-19 Redistributable x64/x84
7. Microsoft Visual Studio Community 2019
8. CMake
9. Git v. 2.24.1.2
10. Microsoft Build tools 2015
```

What to do next? Still errors.
I searched my PC for file Microsoft.Cpp: doesn't exist
`Program Files (x86)/MSBuild` has _14.0_, _15.0_, _Microsoft_ folders
Btw there's a _Microsoft.CSharp.targets_ in `Program Files (x86)/MSBuild/14.0/Bin`

**Comment by CookStar** [comment]
Just follow the link in the Wiki.
http://wiki.sourcepython.com/contributing/building.html#windows

Find  `Visual Studio Express 2010` or `Visual Studio Express 2010 for Visual C++`.

If the installation fails, please uninstall MS C++ 2010 Redistributable and then install MSVC.

**Comment by CookStar** [comment]
Did you succeed to compile it?

**Comment by ArtichaTM** [comment]
Yeah

**Comment by srpg** [comment]
I have same issue for css. I have follow the link in Wiki, for Visual Studio 10

**Comment by CookStar** [comment]
Have you tried this?

> Looks like your VCTargetsPath is not set correctly.
> 
> Try this before you start compiling.
> SET VCTargetsPath="C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0"
> 
> Also double check that Microsoft.Cpp.Default.props exists in `C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0`.

**Comment by srpg** [comment]
I tried that and it doesn't exist there

**Comment by CookStar** [comment]
Then the C++ component was probably missing when you installed Visual Studio Express 2010.
Reinstall or fix Visual Studio Express 2010 and make sure that the C++ component is installed.

**Comment by srpg** [comment]
Got it now work, thanks for help
