### ISSUE TITLE
PagedMenu's top seperator can't be None, check missing

### ISSUE THREAD

**Issue by MarkusMeskanen** [Source-Python-Dev-Team/Source.Python#42]
`PagedMenu`'s attribute `top_seperator` raises an error if set to `None` due to a missing check in */packages/source-python/menus/radio.py* on line 199 and 200:

    buffer = (_translate_text(self.title or '', ply_index)).ljust(
        len(self.top_seperator) - len(info)) + info

**Comment by invincibleqc** [comment]
Try an empty string.

**Comment by MarkusMeskanen** [comment]
Empty string would cause lines 206-207 to execute, they check for `None`

    if self.top_seperator is not None:
        buffer += self.top_seperator + '\n'

**Comment by Ayuto** [comment]
Thanks for reporting! I fixed this issue in this commit. https://github.com/Source-Python-Dev-Team/Source.Python/commit/524f34374ab9a52201d36a4e8006aa4542e796eb
