### ISSUE TITLE
Outdated data causing crashes after updating Source.Python

### ISSUE THREAD

**Issue by Xiazee** [Source-Python-Dev-Team/Source.Python#420]
I updated Source.Python by extracting the latest build into my server folder. This seems to have downgraded the data to an older version than the latest automatically downloaded `source-python-data.zip`.

It crashes whenever the first player connects to the server.

I know @NosferatuJoe ran into a similar issue, but after using the `sp update` command. I suspect this is for the same reason. I can also confirm that the issue happens in this case.

Deleting `csgo\addons\source-python\data\source-python-data.zip` fixes the issue.

I suspect extracting the latest build again after running the server at least once will also cause the issue.

#409 seems to be the same underlying problem.

**Comment by jordanbriere** [comment]
When you manually update your installation, you should remove the directory listed in the updating guide before extracting the new build: http://wiki.sourcepython.com/general/updating.html
