### ISSUE TITLE
ValueError: Could not find symbol: gEntList

### ISSUE THREAD

**Issue by RocKs-Painkiller** [Source-Python-Dev-Team/Source.Python#446]
Hello SP Team,

I get this error when I try to use SP
with this server_srv.so (Linux)
https://drive.google.com/drive/folders/118gbn8VwcB6aVdxl0iN8cZlgEAzxsHJ5
to start.

I use this because this server_srv.so contains everything that valve once deleted.

Examples:

fast_zombie
fast_zombie_torso
zombine
npc_ichthyosaur
npc_ministrider
npc_stalker

and many other things, for example:
 ep1 and ep2 
Synergy and Obsidian Conflict.

what is not normally available in hl2dm.

Sourcemod and Metamod work great, only SP unfortunately does not.
Most of my plugins are for SP.

And I can count SourceMod plugins on one hand.

It would be great if someone could help me with this problem.

Greetings Painkiller

[Source.Python] Loading...

> [SP] Encountered a Warning:
>   File '../addons/source-python/packages/source-python/__init__.py', line 183: UserWarning
>     Did not find address for BaseEntityOutput.fire_output. OnEntityOutput listener
>         will not fire.
> 
> [Source.Python] Failed to load the main module due to following exception:
> Traceback (most recent call last):
> 
>   File "/home/ogp_agent/OGP_User_Files/31/hl2mp/addons/source-python/packages/source-python/__init__.py", line 88, in load
>     setup_global_pointers()
> 
>   File "/home/ogp_agent/OGP_User_Files/31/hl2mp/addons/source-python/packages/source-python/__init__.py", line 307, in setup_global_pointers
>     SP_DATA_PATH / 'memory' / 'global_pointers.ini'))
> 
>   File "/home/ogp_agent/OGP_User_Files/31/hl2mp/addons/source-python/packages/source-python/memory/manager.py", line 765, in create_global_pointers_from_file
>     self.global_pointer(cls, *data)
> 
>   File "/home/ogp_agent/OGP_User_Files/31/hl2mp/addons/source-python/packages/source-python/memory/manager.py", line 734, in global_pointer
>     ptr = binary.find_pointer(identifier, offset, level)
> 
> ValueError: Could not find symbol: gEntList
> [Source.Python] Could not initialize python.
> Failed to load plugin "addons/source-python"
> [Source.Python] Unloading...
> [Source.Python] Unloaded successfully.

Edit: 

> 2022-03-08 14:22:37 - sp.hooks.warnings   -   WARNING   [Source.Python]
[SP] Encountered a Warning:
  File '../addons/source-python/packages/source-python/__init__.py', line 183: UserWarning
    Did not find address for BaseEntityOutput.fire_output. OnEntityOutput listener
        will not fire.

Edit 2: The version of the game is the same.

**Comment by Ayuto** [comment]
We only support the official and latest Valve version.
