### ISSUE TITLE
Newest TF2 update causes SP to seg fault on boot

### ISSUE THREAD

**Issue by neilstottler** [Source-Python-Dev-Team/Source.Python#448]
I've already made sure that I'm on the latest build of SP (April 18 2022).

Loaded 1343 VPK file hashes from /home/tf/tf/tf2_sound_misc.vpk for pure server operation.
Loaded 1343 VPK file hashes from /home/tf/tf/tf2_sound_misc.vpk for pure server operation.
Loaded 2710 VPK file hashes from /home/tf/tf/tf2_misc.vpk for pure server operation.
Loaded 2710 VPK file hashes from /home/tf/tf/tf2_misc.vpk for pure server operation.
Loaded 2710 VPK file hashes from /home/tf/tf/tf2_misc.vpk for pure server operation.
Loaded 1217 VPK file hashes from /home/tf/hl2/hl2_textures.vpk for pure server operation.
Loaded 574 VPK file hashes from /home/tf/hl2/hl2_sound_vo_english.vpk for pure server operation.
Loaded 383 VPK file hashes from /home/tf/hl2/hl2_sound_misc.vpk for pure server operation.
Loaded 451 VPK file hashes from /home/tf/hl2/hl2_misc.vpk for pure server operation.
Loaded 451 VPK file hashes from /home/tf/hl2/hl2_misc.vpk for pure server operation.
Loaded 5 VPK file hashes from /home/tf/platform/platform_misc.vpk for pure server operation.
Loaded 5 VPK file hashes from /home/tf/platform/platform_misc.vpk for pure server operation.
server_srv.so loaded for "Team Fortress"
For FCVAR_REPLICATED, ConVar must be defined in client and game .dlls (sv_use_steam_voice)
ProtoDefs post data loaded.
ProtoDefs loaded. 18.03 MB used
ProtoDefs post data loaded.
ProtoDefs loaded. 18.03 MB used
 failed to dlopen /home/tf/tf/addons/metamod/bin/linux64/server.so error=/home/tf/tf/addons/metamod/bin/linux64/server.so: wrong ELF class: ELFCLASS64
Unable to load plugin "addons/metamod/bin/linux64/server"
[Source.Python] Loading...
[Source.Python] Could not retrieve interface ServerGameDLL010
Failed to load plugin "addons/source-python"
[Source.Python] Unloading...
Segmentation fault (core dumped)
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
Wed Jun 22 17:25:10 UTC 2022: Server restart in 10 seconds

**Comment by Ayuto** [comment]
The interface version of the ServerGameDLL was incemented. I'm currently creating a new release based on the updated SDK (was updated today), which should be available in ~20 minutes. Please let me know if the new build is working for you.

**Comment by neilstottler** [comment]
Seems to be working now. Is there any way that I'm able to compile this myself in the future?

**Comment by satoon101** [comment]
http://wiki.sourcepython.com/contributing/building.html

**Comment by waldotf** [comment]
You'll want to follow that build guide with a rather old toolchain; up-to-date GCC will run into a few issues. I had a pretty easy time getting everything to compile in a Debian 8 Docker image, where you can just `apt install gcc-4.8 g++4.8` and all their dependencies without mucking around too much with repositories.
