### ISSUE TITLE
mathlib's Vector.normalize() returns false result

### ISSUE THREAD

**Issue by high-voltage** [Source-Python-Dev-Team/Source.Python#46]
I am getting the exact same result as Vector.get_length() (a float), but it should return a Vector, like this:

```
def normalize_vector(vec):
    x, y, z = tuple(vec)
    length = vec.get_lenght()
    return Vector(x / length, y / length, z / length)
```

(April 15 csgo release)

**Comment by invincibleqc** [comment]
Well, this is normal. This method returns a float and modify your object directly. Run the following code and you will see:

```python
from mathlib import Vector

vec = Vector(100, 100, 100)
print(vec.normalize())
print(vec.x, vec.y, vec.z)
```

If you want to keep your Vector intact, copy it first.

**Comment by high-voltage** [comment]
Oh okay, a misunderstanding then. sorry
