### ISSUE TITLE
Can't install Source.Python in CSS.

### ISSUE THREAD

**Issue by H1N1-dev** [Source-Python-Dev-Team/Source.Python#465]
VS2010 installed, anything in archive copied to `Counter-Strike Source\cstrike\`
But, CSS console prints on the first line:
```
No valid signature found for c:\program files (x86)\steam\steamapps\common\counter-strike source\cstrike\custom\source-python\addons\source-python.dll
```
Am I doing something wrong? Everything seems to be installed correctly.

**Comment by H1N1-dev** [comment]
Thanks! It works!
Maybe it's worth mentioning "-insecure" in the installation tutorial?
I struggled with this problem for a month, and the solution turned out to be extremely simple.

**Comment by satoon101** [comment]
@H1N1-dev - we don't support running SP from the client.  I am pretty sure that's written somewhere, but I can't find it..  Not that it won't work, but that's not really something we support.  We recommend running a server locally and connecting to that instead.
