### ISSUE TITLE
'Edict' object has no attribute 'get_team_index' in PlayerIter()

### ISSUE THREAD

**Issue by MarkusMeskanen** [Source-Python-Dev-Team/Source.Python#47]
[SP] Caught an Exception:
    Traceback (most recent call last):
      File '..\addons\source-python\packages\source-python\events\listener.py', line
     93, in fire_game_event
        callback(game_event)
      File '..\addons\source-python\plugins\hw\hw.py', line 400, in round_start
        for index in PlayerIter(is_filters=('ct', 't')):
      File '..\addons\source-python\packages\source-python\filters\iterator.py', lin
    e 39, in __iter__
        if not self._is_valid(item):
      File '..\addons\source-python\packages\source-python\filters\iterator.py', lin
    e 77, in _is_valid
        if not self.manager._filters[filter_name](item):
      File '..\addons\source-python\packages\source-python\filters\players.py', line
     103, in _player_is_on_team
        return playerinfo.get_team_index() == self.team

    AttributeError: 'Edict' object has no attribute 'get_team_index'

**Comment by satoon101** [comment]
This was already fixed in 4b91bb1.

Also:
http://forums.sourcepython.com/showthread.php?802
