### ISSUE TITLE
Emit Sound does not work correctly (attenuation)

### ISSUE THREAD

**Issue by RoOF3** [Source-Python-Dev-Team/Source.Python#48]
Hi Guys,

I noticed that the Emit sound function of SP isn't work correctly.

If i change attenuation > 0 it does not work. No Sound gets played. But if its zero it  works.

Tried this:

cheer = Sound((), SOUND_FROM_WORLD, "source-python/zombiemod/fz_scream1.mp3", volume= 0.6, attenuation = 0.9)

also this

cheer = Sound((), SOUND_FROM_LOCAL_PLAYER, "source-python/zombiemod/fz_scream1.mp3", volume= 1.0 , attenuation = 0.9)

I want to play a sound from a Player but the volume should be set by distance to the Player.

Like ES did:

es.emitsound('player', userid, sound, 1.0, 0.9) # 1.0 = Volume , 0,9 attenuation

Thanks :)

**Comment by satoon101** [comment]
Have you tried providing an entity index instead of SOUND_FROM_WORLD or SOUND_FROM_LOCAL_PLAYER?  Basically, the 'userid' from es.emitsound except for the player's index instead of their userid.

**Comment by satoon101** [comment]
Have you had a chance to test using a player index?  I am sure it works, I would just like you to verify.

**Comment by RoOF3** [comment]
Sorry for late reply :). Tested it with player index. Worked perfekt :+1:
