### ISSUE TITLE
Gravity not resetting

### ISSUE THREAD

**Issue by EinariTuukkanen** [Source-Python-Dev-Team/Source.Python#49]
PlayerEntity.gravity attribute's value is not resetting on player death or round end (needs to be reset to 1.0 manually on spawn to avoid stacking gravity values).

**Comment by Ayuto** [comment]
Yes, it seems like the engine doesn't reset this value. I'm not sure if SP should take on responsibility to reset this value. That's how the engine works.

**Comment by satoon101** [comment]
Is this with the csgo engine?  I don't remember the orangebox engine having this issue, but I could be wrong.

I am with Ayuto.  This is not something the plugin itself should be worried about.

**Comment by EinariTuukkanen** [comment]
Alright.

PS. I only tested it in CS:S so apparently it applies to OB at least.

**Comment by invincibleqc** [comment]
This is not an issue with the plugin. The engine/game is not setting this value on new round/spawn. As long as setting/getting it works, the rest is engine dependant.

**Comment by EinariTuukkanen** [comment]
Yeah, Ayuto and Satoon answered to this already.
