### ISSUE TITLE
TF2 Update 04/18/2024

### ISSUE THREAD

**Issue by waldotf** [Source-Python-Dev-Team/Source.Python#494]
Getting unpredictable crashes after this update (Accelerator is still unpatched so no useful logs, sorry). Probably just gamedata changes since Source.Python loads fine.

**Comment by Ayuto** [comment]
A re-compile with the latest changes from the SDK is required. I'm currently working on it.

**Comment by Ayuto** [comment]
A new version is available. Could you please try the new version and give a short feedback? Thansk!

**Comment by waldotf** [comment]
Seems to have fixed all of the crashes (as well as a hang-on-exit behavior, which I hadn't attributed to SP). Thanks for the quick response!
