### ISSUE TITLE
PlayerWeapons class issues in CSGO

### ISSUE THREAD

**Issue by high-voltage** [Source-Python-Dev-Team/Source.Python#50]
~~I was playing around with setting the clips/ammo of weapons and when setting the clip of weapon_knife, I'm getting this error:~~

```PlayerEntity(1).set_ammo('weapon_knife', 1)```

```
  File '..\addons\source-python\packages\source-python\players\weapons\__init__.py', line 117, in set_ammo
    self._set_weapon_ammo(value, classname)
  File '..\addons\source-python\packages\source-python\players\weapons\__init__.py', line 150, in _set_weapon_ammo
    weapon_manager.ammoprop + '%03d' % weapon.ammoprop, value)
  File '..\addons\source-python\packages\source-python\entities\entity.py', line 434, in set_property_int
    self._set_property(name, 'int', value)
  File '..\addons\source-python\packages\source-python\entities\entity.py', line 502, in _set_property
    name, self.classname))

ValueError: Property 'm_iAmmo.-01' not found for entity type 'player'
```

~~Furthermore I found a weird behaviour when setting the ammo of other weapons. For example, I've set  the ammo of weapon_awp to 10, and after I reloaded the gun it resetted back to it's previous value, before I set it in my script.~~

Test script:

```
from events import Event

from players.entity import PlayerEntity
from players.helpers import index_from_userid

@Event
def player_jump(game_event):
    userid = game_event.get_int('userid')
    index = index_from_userid(userid)
    player = PlayerEntity(index)
    player.set_ammo('weapon_awp', 10)
```
~~If you test this, jump, then shoot once or more, then reload. Ammo will set back to the value it had before setting it.~~

**EDIT**
First bug can be ignored, as answered by satoon.
Second bug was just a temporary game bug, I had sv_inifinite_ammo set to 1 before I tested this, setting it back to 0 created this weird behavior. I restarted my server with default value 0 and it worked fine.
And by doing this, I discovered another bug: For example, if I manually set the ammo to 10, then shoot 10 times and reload, I should have now 0 ammo. But instead the game sets it back to the default value (awp 30).

And this bug still exists:
Setting the ammo to 0 does nothing.

**Comment by satoon101** [comment]
Knives shouldn't have ammo or clip anyway.  A different error should probably be raised when -1 is returned for the ammo property, though.  I don't think we should implicitly silence that error completely, as that could too easily hide other possible issues.

**Comment by high-voltage** [comment]
Okay, ignore this then, it's not that important anyways. I've updated my post with 2 more issues.

**Comment by Ayuto** [comment]
At least CS:S does not seem to have this issue. Not sure about CS:GO.

**Comment by satoon101** [comment]
Please, from now on, report each issue as a separate issue on the issues list.  We want to keep things separated to know what progress is being made on each.

**Comment by high-voltage** [comment]
Alright, I'll remember this.

**Comment by Ayuto** [comment]
Just tested CS:GO and it does indeed reset the ammo.

**Comment by high-voltage** [comment]
I found a solution that works for primary and secondary weapons:

```
from players.entity import PlayerEntity
from entities.entity import BaseEntity


player = PlayerEntity(1)
weapon = "weapon_awp"
value = 10

def set_ammo(player, weapon, value):
    weapon_index = player.get_weapon_index(weapon)
    if weapon_index:
        entity = BaseEntity(weapon_index)
        entity.set_property_int('m_iPrimaryReserveAmmoCount', value)
        
def set_clip(player, weapon, value):
    weapon_index = player.get_weapon_index(weapon)
    if weapon_index:
        entity = BaseEntity(weapon_index)
        entity.set_property_int('m_iClip1', value)

```

This solution still doesn't want to accept 0 as value tho (same bug as before).

**Comment by satoon101** [comment]
I was able to get a little testing of my own done this morning.  Setting to 0 seems to work fine for me:

```python
from entities.helpers import index_from_inthandle
from events import Event
from players.entity import PlayerEntity
from players.helpers import index_from_userid
from weapons.entity import WeaponEntity


@Event
def player_say(game_event):
    player = PlayerEntity(index_from_userid(game_event.get_int('userid')))
    weapon = WeaponEntity(index_from_inthandle(player.active_weapon))
    if weapon.ammoprop == -1:
        return
    current = weapon.get_property_int('m_iPrimaryReserveAmmoCount')
    weapon.set_property_int('m_iPrimaryReserveAmmoCount', 0)
```

However, setting above the maximum amount for the weapon's ammo type has a little bit of an issue.

```python
from entities.helpers import index_from_inthandle
from events import Event
from players.entity import PlayerEntity
from players.helpers import index_from_userid
from weapons.entity import WeaponEntity


@Event
def player_say(game_event):
    player = PlayerEntity(index_from_userid(game_event.get_int('userid')))
    weapon = WeaponEntity(index_from_inthandle(player.active_weapon))
    if weapon.ammoprop == -1:
        return
    current = weapon.get_property_int('m_iPrimaryReserveAmmoCount')
    weapon.set_property_int('m_iPrimaryReserveAmmoCount', current + 8)
```

Using that script, I force the reserve ammo above the maximum amount by 8.  Then, if I shoot between 1 and 7 bullets, when I reload, it goes back to the maximum amount instead of the current amount minus the number of shots I took.  I don't think the plugin itself should handle that issue, though.  The best way to avoid that would be to increase the maximum allowed ammo by using its cvar.

We will have to create a separate module to handle many of these differences from CS:GO from all other games.

**Comment by satoon101** [comment]
Commit https://github.com/Source-Python-Dev-Team/Source.Python/commit/6bd2ee2ee2d5366477919d4589def963bce24f1d should fix this issue.  It is part of a bigger change, though, so it won't be available until everything in the [player_weapons_update2](https://github.com/Source-Python-Dev-Team/Source.Python/tree/player_weapons_update2) branch has been fully tested and merged into master.

**Comment by satoon101** [comment]
We have merged the player_weapons_update2 branch, so this should be fixed in master now.
