### ISSUE TITLE
Unable to find some properties

### ISSUE THREAD

**Issue by Ayuto** [Source-Python-Dev-Team/Source.Python#51]
There are properties which can't be found by < Entity >.get/set_property_< type >(). E.g. this little script will cause an error, although the property exists (CBaseEntity.m_flGravity).
```
from players.entity import PlayerEntity

player = PlayerEntity(1)
print(player.get_property_float('m_flGravity'))
```
```
Traceback (most recent call last):
  File '..\addons\source-python\packages\source-python\plugins\manager.py', line 72, in __missing__
    instance = self.instance(plugin_name, self.base_import)
  File '..\addons\source-python\packages\source-python\plugins\instance.py', line 82, in __init__
    self._plugin = import_module(import_name)
  File '..\addons\source-python\plugins\test8\test8.py', line 13, in <module>
    print(player.get_property_float('m_flGravity'))
  File '..\addons\source-python\packages\source-python\entities\entity.py', line 356, in get_property_float
    return self._get_property(name, 'float')
  File '..\addons\source-python\packages\source-python\entities\entity.py', line 419, in _get_property
    name, self.classname))

ValueError: Property 'm_flGravity' not found for entity type 'player'
```

**Comment by invincibleqc** [comment]
I guess this get registered as keyvalue and all we need is to add the external name.

**Comment by satoon101** [comment]
That is odd, as long as it is a non-embedded property, what you have should certainly work.  I won't be home till tomorrow night, but when I do get home I will do some testing.  And yes, I believe we so have the gravity keyvalue registered as a property.

**Comment by Ayuto** [comment]
Just did a few tests and it seems that this really just happens if the property was added as a keyvalue. Nevertheless, I would actually expect that < Entity >.get/set_property_< type >() would work with every existing property.

**Comment by satoon101** [comment]
Yes, it definitely should work.  This will be on the top of my priority list when I get home, if you haven't already solved it.

**Comment by invincibleqc** [comment]
Fixed: https://github.com/Source-Python-Dev-Team/Source.Python/commit/8f73bfe59d2b825f484d4113a3f082f73d412c5b
