### ISSUE TITLE
menus.PagedMenu() idea of "back" option

### ISSUE THREAD

**Issue by high-voltage** [Source-Python-Dev-Team/Source.Python#53]
It would be really nice if we could bind the "Back"-button in the first page of a PagedMenu() manually in our scripts. Example script of how it could look in usage:

```
def some_menu(index):
    menu = SimpleMenu()
    menu.append(SimpleOption(1, "some other menu", 1)
    menu.select_callback = some_menu_callback
    menu.send(index)

def some_menu_callback(menu, index, option):
    if option.value == 1:
        some_other_menu(index)

def some_other_menu(index):
    # create a paged menu with 2 pages
    menu = PagedMenu()
    for x in range(1, 10):
        menu.append(PagedOption(x, x))

    # this would tell the PagedMenu that we want to bind the "Back"-button on the first page on ourselves
    # the argument is what would be passed as option.value in the callback
    menu.add_back_option('go_back')

    menu.select_callback = some_other_menu_callback
    menu.send(index)

def some_other_menu_callback(menu, index, option):
    if option.value == "go_back":
        # would be only called if we are in the first page of the menu, otherwise behave normally
        return some_menu(index)

    print(option.value)

```

Might not be the best way to do this, but it's just an idea so you know what I mean.

**Comment by MarkusMeskanen** [comment]
We did something similar on [Hero-Wars](https://github.com/Hero-Wars-Dev-Team/Hero-Wars/blob/master/addons/source-python/plugins/hw/menus.py#L72). Basically there's `previous_menu` attribute for PagedMenus, and pressing `Back` on page 1 will open the previous menu instead.

**Comment by high-voltage** [comment]
@MarkusMeskanen This would mean that every menu needs to be in the global scope of the script if the previous_menu attribute calls a PagedMenu instance, doesn't it? 

I also thought about adding an own callback for this option, but the way I did it works best in my opinion. Tell me what you think about it.

**Comment by Ayuto** [comment]
Added with PR #111.
