### ISSUE TITLE
get_color, set_color function throws an exception

### ISSUE THREAD

**Issue by Andrej730** [Source-Python-Dev-Team/Source.Python#58]
[SP] Caught an Exception:
Traceback (most recent call last): 
 File '..\addons\source-python\packages\source-python\entities\entity.py', line289, in get_color
    value & 0xff, (value & 0xff00) >> 8,
TypeError: unsupported operand type(s) for &: 'Color' and 'int'

I think this is due to that render_color is Color type and return object itself but not 4byte integer value as expected in code. Also set_color function throws a similar exception.

**Comment by Ayuto** [comment]
Thanks for reporting! As soon as we have fixed issue #59, we can simply use this:
```
def get_color(self):
    """Return the entity's color as a Color instance."""
    return self.render_color

def set_color(self, color, current_alpha=False):
    """Set the entity's color to the given RGBA values."""
    self.render_color = color
    
    # Don't keep current alpha?
    if not current_alpha:
        self.render_amt = color.a
```
