### ISSUE TITLE
Unable to add hardcoded keyvalues

### ISSUE THREAD

**Issue by Ayuto** [Source-Python-Dev-Team/Source.Python#59]
Currently, only keyvalues are added, which are part of a datamap. But there are keyvalues, which are hardcoded in CBaseEntity::KeyValue(). E.g. renderamt: https://github.com/alliedmodders/hl2sdk/blob/28b43b06249837c1517db1468af14678080715f6/game/shared/baseentity_shared.cpp#L339

Should we loop through keyvalue_contents and add them regardless of the datamap?. https://github.com/Source-Python-Dev-Team/Source.Python/blob/a6c6e392a3dba391c171744068c6fb2f01d856b3/addons/source-python/packages/source-python/entities/classes.py#L245

**Comment by satoon101** [comment]
Are those the only entity KeyValues we know of that are hard coded?  rendercolor is a part of the DataMap, so that gets added already.  The others are as follows:
```
    rendercolor32
    renderamt
    disableshadows
    mins
    maxs
    disablereceiveshadows
    nodamageforces
    angle
    angles
    origin
    targetname
```

Should we include all of the above or just the most useful?

**Comment by Ayuto** [comment]
No, these are just the keyvalues of CBaseEntity. Subclasses might hardcode more keyvalues.

**Comment by satoon101** [comment]
The tricky part is that we are going to have to provide three values for each:

1. The name of the KeyValue
2. The attribute name (sometimes the same as the name of KeyValue)
3. The type to use with get/set_key_value_&lt;type&gt;

I think we should create a new section within the data files for these specifically.  What are your thoughts on what to call the section and the format of the section itself?  Just a quick outline and one possibility of what it could look like:
```ini
[hardcoded keyvalue]

    [[origin]]
        name = origin
        type = vector
```

**Comment by invincibleqc** [comment]
They could be in the same Section, I guess:

```ini
[keyvalue]
    x = y
    y = x

    [[origin]]
        name = origin
        type = vector

    a = b
    b = c

    [[renderamt]]
        name = render_amt
        type = float
```

Then while looping over we can verify if we have the type or we need to find it in the datamap:

```python
for keyvalue, data in ConfigObj(file)['keyvalue'].items():
    if isinstance(keyvalue, configobj.Section):
        self._register_keyvalue(keyvalue, data['name'], data['type'])
    elif keyvalue not in datamap:
         raise?
    else:
          self._register_keyvalue_from_datamap(blah, blah)
```

Or something like that. That make me thinks that we still need to implement something like this for properties: http://forums.sourcepython.com/showthread.php?780-Data-files&p=4663&viewfull=1#post4663

**Comment by Ayuto** [comment]
I think I would prefer having that in the same section. But the key should be the alias name for the attribute.
````
    [[render_amt]]
        name = renderamt
        type = int
````
