### ISSUE TITLE
Add the ability to get command line arguments

### ISSUE THREAD

**Issue by necavi** [Source-Python-Dev-Team/Source.Python#60]
I could definitely use the ability to get the command lines options, similar to: https://sm.alliedmods.net/new-api/commandline. Seems incredibly easy to add, preferably accessible through the standard sys.argv so that libraries like argparse work correctly.

**Comment by Ayuto** [comment]
Added sys.argv! https://github.com/Source-Python-Dev-Team/Source.Python/commit/d44413ace7001b573b6e99ba9825d5d168c2f16a
