### ISSUE TITLE
PlayerEntity.set_model causes AttributeError

### ISSUE THREAD

**Issue by backraw** [Source-Python-Dev-Team/Source.Python#61]
<b>I'm using the May 21, 2015 release</b>

Edit: I should also mention that it's orangebox/css.

Whenever I want to set a player's model to another one, it raises an AttributeError:

```
File '../addons/source-python/packages/source-python/menus/radio.py', line 343, in _select 
    return super(PagedRadioMenu, self)._select(player_index, choice_index) 
  File '../addons/source-python/packages/source-python/menus/radio.py', line 97, in _select 
    self._player_pages[player_index].options[choice_index]) 
  File '../addons/source-python/packages/source-python/menus/base.py', line 124, in _select 
    return self.select_callback(self, player_index, choice_index) 
  File '../addons/source-python/plugins/seekme/models.py', line 48, in model_menu_callback 
    player.model = option.value 
  File '../addons/source-python/packages/source-python/entities/entity.py', line 118, in __setattr__ 
    super(Entity, self).__setattr__(attr, value) 
  File '../addons/source-python/packages/source-python/entities/entity.py', line 335, in set_model 
    self.edict.set_model_index(model.index) 
 
AttributeError: 'Edict' object has no attribute 'set_model_index' 
```

The model's index definitely exists because it's a server-side model and has been instantiated with <b>engines.prechache.Model</b>.

Code which handles setting the player's model:
https://github.com/backraw/seekme/blob/master/addons/source-python/plugins/seekme/models.py#L48

Code which instantiates the model:
https://github.com/backraw/seekme/blob/master/addons/source-python/plugins/seekme/models.py#L99

... from an ini file's section's "path" key, if you want to know:
https://github.com/backraw/seekme/blob/master/addons/source-python/data/plugins/seekme/models/de_dust2.ini

**Comment by Ayuto** [comment]
Thanks for reporting!
