### ISSUE TITLE
VGUIMenu issues

### ISSUE THREAD

**Issue by satoon101** [Source-Python-Dev-Team/Source.Python#65]
This was first reported [here](http://forums.sourcepython.com/showthread.php?718-TF2-VGUIMenu-not-working&p=5137&viewfull=1#post5137).

So, I did some testing, and it seems there are a few issues.  First, in [this line](https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/messages/base.py#L503), if you pass any more than 2 parameters, since we have ["length" set to 2](https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/data/source-python/messages/usermessages.ini#L124), only 2 parameters are iterated over, not all of them.

Also, in that same line, since we iterate over parameter_values, we are only iterating over the keys themselves and we never account for the values.

Also, we never seem to set the 'length'.  I do see where we [account for length](https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/messages/types/cstrike/vguimenu.py#L40).  However, this seems to just be setting the length to 1 (and it never specifies "length", though I don't think we really have to  on the OrangeBox).  The length should be set to the number of subkeys.

Here is my test code:
```python
from events import Event
from messages import VGUIMenu
from messages import SayText2
from players.helpers import index_from_userid


motd = VGUIMenu(name='info', show=True, subkeys={
    'title': 'GunGame Winner', 'type': '2',
    'msg': 'http://gungame.net/gg5_win.php?winningTeam=Terrorist',})

chat = SayText2(message='This is a test.')


@Event
def player_say(game_event):
    motd.send(index_from_userid(game_event.get_int('userid')))

    # Make sure I didn't break other messages with special parameters
    chat.send(index_from_userid(game_event.get_int('userid')))
```

**Comment by Ayuto** [comment]
While looking at the CS:GO VGUIMenu issue (http://forums.sourcepython.com/showthread.php?902-Csgo-motd) I came to the conclusion that we should re-write the messages package. Games that are using protobuf will need methods like this to handle special message parameters:
```
void CUserMessageImplementation::set_dict( dict field_value )
{
	if (strcmp(m_message->GetTypeName().c_str(), "CCSUsrMsg_VGUIMenu") == 0)
	{
		CCSUsrMsg_VGUIMenu* pMsg = (CCSUsrMsg_VGUIMenu *) m_message;

		for(int i=0; i < len(field_value); i++)
		{
			const char* key = extract<const char*>(field_value.keys()[i]);
			const char* value = extract<const char*>(field_value[key]);

			CCSUsrMsg_VGUIMenu_Subkey* subkey = pMsg->add_subkeys();
			subkey->set_name(key);
			subkey->set_str(value);
		}
	}
	else
	{
		BOOST_RAISE_EXCEPTION(PyExc_ValueError, "Unsupported message")
	}
}
```
But this isn't a nice solution. I also never really liked the messages package as it's not quite easy to read due to it's long methods and isn't very flexible. I would suggest to expose very basic functions, which send the messages. Those functions could be extended on the Python side to handle translations etc.

What do you think?
