### ISSUE TITLE
Apparent memory leak in output listener manager

### ISSUE THREAD

**Issue by jsza** [Source-Python-Dev-Team/Source.Python#74]
This one was a little tricky to track down. It seems to only happen (or at least with a much higher rate) on maps with func_tracktrain. Memory usage will steadily increase with at least one player connected to the server (tested in CS:S and TF2 on Debian).

It's possible to reproduce on this map: http://files.gamebanana.com/maps/surf_fast.7z

Commenting out this line seems to stop the leak: https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/listeners/_entity_output.py#L40

**Comment by Ayuto** [comment]
Thanks for reporting! I tested your map on my CS:S Server (Windows) and found two memory leaks. After I have fixed them your map didn't leak anymore on my side.

Please verify that build 71 (it's currently building) fixes your issue.

**Comment by jsza** [comment]
I've just had a chance to test the new build and it seems to be working great! :)
