### ISSUE TITLE
temp_entities.beam_points

### ISSUE THREAD

**Issue by Manifest1** [Source-Python-Dev-Team/Source.Python#77]
Hi there SourcePython developing team!

First off I'd like to thank you all for all your effort and energy that you have put into this project and all the tools you have provided us with, it's very much appreciated.
That being said I think I have found a bug, whether it is the code for the temp entities, or the engine in CS:GO itself, I do not actually know.

The bug that I have encountered is when you are trying to use temp_entities.beam_points and setting the start and end width to be two different values.
I've previously worked with ES:S in CS:S and when defining 2 different kinds of width it worked just fine.

However I am now trying out the same thing in source python, in CS:GO and it does not seem to work as I intend it to.
It is supposed to make the line get bigger/wider in one of the ends, however that is not the case, no matter which values you put in the start and end width the line always stay the same as one of the values.

E.g. a start width of 5 and an end width of 20 will then be a straight line with no change, probably using the start and end width of either 5 or 20.
If you guys want a look at it for yourself here is the example I used when noticing this:

laser = model('sprites/laser.vmt')

		location1 = defender.origin
		location2 = defender.origin
		location1.z += 5
		location2.z += 140
		temp_entities.beam_points(self._recipients, 0, location1, location2, laser.index, laser.index, 10, 10, 1, 5, 50, 0, 0, 255, 150, 150, 170, 1)

I hope this information is detailed and explained well enough, I did my best to explain it in the best way I could.
I hope you guys will be able to fix this issue as it will open up for a lot more of opportunities when it comes to working with effects in SourcePython.

Sincerely
- Manifest

**Comment by Ayuto** [comment]
Can you show me the working ES code?

**Comment by MarkusMeskanen** [comment]
I'm not sure about this, but I once came to the conclusion that CS:GO itself doesn't support different start and end width. The same code worked just fine for CS:Source but not for CS:GO.

**Comment by Manifest1** [comment]
Well this code is different from what I posted, but is using the star and end width feature, so I guess it should do the job. (Note the 9 and 90, that's the start and end width for this effect, which should be similar to the sourcepython version posted above) 

	es_getplayerlocation wcs_x1 wcs_y1 wcs_z1 event_var(userid)
	es_getplayerlocation wcs_x2 wcs_y2 wcs_z2 event_var(userid)
	es_xmath wcs_x2 - 160
	es_createvectorstring vector1 server_var(wcs_x1) server_var(wcs_y1) server_var(wcs_z1)
	es_createvectorstring vector2 server_var(wcs_x2) server_var(wcs_y2) server_var(wcs_z2)
	es est_effect_06 #a 0 sprites/hydraspinalcord.vmt server_var(vector1) server_var(vector2) 5 3.5 9 90 0 0 62 197 255 255 100

**Comment by Ayuto** [comment]
Which plugin do you use for the est commands?

It would be nice if you only post fully working examples to reproduce the issue.

**Comment by Manifest1** [comment]
This example is fully working when you have the latest version of eventscripts installed, as well as sourcemod and the latest version of as well as the wcs_effects.smx, which can be obtained in this download here: http://warcraft-source.com/board/index.php?action=tpmod;dl=item132

Normally the est commands wouldn't work properly indeed, however the syntax for effects weren't changed when this plugin was added after OB, probably for the sake of user friendliness, but I honestly don't know.

I hope this will help solve the issue at hand.


Sincerely
- Manifest.

**Comment by Ayuto** [comment]
Thanks! I will take a look at it at the weekend.

**Comment by Manifest1** [comment]
No problem at all, I just updated the code real quick and it should now be easy to just add onto the server once the wcs_effects.smx is running. This code itself should atleast not give any errors when that plugin is enabled.

I really hope you will be able to fix this part, it may seem like a minor thing, but for one like me (I love working with visual effects ranging from simple circles, to particle effects) then this minor feature with width can really mean the world. So hopefully it's just a minor error and not the CS:GO not supporting this feature :-)

Anyway thank you for taking the time to look into it Ayuto

**Comment by Ayuto** [comment]
Just wanted to let you know that I wasn't able to look at it at the weekend, sorry. I'm currently too busy, but I hope that I will be able at the next weekend.

**Comment by Ayuto** [comment]
``temp_entities`` is about to get removed. Use ``TempEntity`` instead.
