### ISSUE TITLE
[CS:GO] Unable to change WeaponEntity's color

### ISSUE THREAD

**Issue by Mahi** [Source-Python-Dev-Team/Source.Python#78]
Using the following code:

```
from players.entity import PlayerEntity
from players.helpers import index_from_userid
from colors import Color
from events import Event
from entities.helpers import index_from_inthandle
from weapons.entity import WeaponEntity


@Event('player_jump')
def player_jump(event):
    player = PlayerEntity(index_from_userid(event['userid']))
    weapon = WeaponEntity(index_from_inthandle(player.active_weapon))
    weapon.color = Color(0, 0, 0)
```

I was able to raise the following error:

```
[SP] Caught an Exception:
Traceback (most recent call last):
  File '..\addons\source-python\packages\source-python\events\listener.py', line
 92, in fire_game_event
    callback(game_event)
  File '..\addons\source-python\plugins\test\test.py', line 13, in player_jump
    weapon.color = Color(0, 0, 0)
  File '..\addons\source-python\packages\source-python\entities\entity.py', line
 105, in __setattr__
    super().__setattr__(attr, value)
  File '..\addons\source-python\packages\source-python\entities\entity.py', line
 303, in set_color
    self.render_mode |= RenderMode.TRANS_COLOR
  File '..\addons\source-python\packages\source-python\entities\entity.py', line
 117, in __setattr__
    setattr(server_class(self.pointer, wrap=True), attr, value)
  File '..\addons\source-python\packages\source-python\entities\classes.py', lin
e 517, in fset
    pointer), 'set_key_value_' + type_name)(name, value)

NameError: 'rendermode' is not a valid KeyValue for entity class 'CWeaponCSBase'
```

**Comment by satoon101** [comment]
For further reference:
http://forums.sourcepython.com/showthread.php?869

Thank you for making an official issue report for this.

**Comment by MarkusMeskanen** [comment]
Didn't see that one, only seached GitHub's issues... Silly me. Well, here it is on GitHub! And while probably quite obvious, I can verify that this is still happening to only weapons, not players.

**Comment by Ayuto** [comment]
Does this also happen with other games? I guess you are testing with CS:GO?

**Comment by necavi** [comment]
I believe that this is a CS:GO bug as I recall the same thing being reported on a sourcemod project's bugtracker.

**Comment by MarkusMeskanen** [comment]
@Ayuto I was indeed testing with CS:GO. I don't know if it happens with other games, I don't have any other servers installed so can't test right now.

**Comment by satoon101** [comment]
I just tested this on CS:S and am encountering the same error.  I have only tested setting player and weapon colors.  Both games work fine for players but have the error for weapons.

**Comment by satoon101** [comment]
I did some testing last night by switching to use the same method as ES' playerlib.Player.setColor.  It seemed to work fine and did not error after moving all the render keyvalues to their respective SendProp names.  I did not do extensive testing, but hope to get that done tonight.

**Comment by satoon101** [comment]
I created a new branch to test out some changes.  The errors are gone with this new implementation.  However, it doesn't seem to work at all on CS:GO...
https://github.com/Source-Python-Dev-Team/Source.Python/commits/weapon_color_update

Currently just has one commit:
https://github.com/Source-Python-Dev-Team/Source.Python/commit/0912efb2c0a991d060f24a217b9d67ed12fc95b4

**Comment by Ayuto** [comment]
I think we should merge the branch for now and keep the issue open. Then have at least fixed the error in other games.

**Comment by satoon101** [comment]
Done.  We still need to figure out how to change the weapon color in CS:GO.  I haven't really tested that for a while and cannot remember what I have tested in the past.

**Comment by Ayuto** [comment]
Changing the weapon color in CS:GO seems to work fine. I guess that has been fixed.

**Comment by satoon101** [comment]
This works for you now?  I just tested and it doesn't for me.

Code tested in the csgo_weapons branch:
```python
from colors import BLUE, RED
from events import Event
from filters.players import PlayerIter


team_colors = {
    2: RED,
    3: BLUE,
}


@Event('round_freeze_end')
def do_stuff(game_event):
    for player in PlayerIter('bot'):
        player.frozen = True

    for player in PlayerIter('alive'):
        for weapon in player.weapons():
            weapon.color = team_colors[player.team]
```

The weapon in my hands and the weapon in other players' hands do not change color.  When I drop my weapon or kill an enemy causing them to drop their weapon, the color change is seen.

**Comment by Ayuto** [comment]
> The weapon in my hands and the weapon in other players' hands do not change color. When I drop my weapon or kill an enemy causing them to drop their weapon, the color change is seen.

That's also how it was working for me. I thought the issue was that it didn't change the color at all?!
