### ISSUE TITLE
Player.base_velocity doesn't do anything

### ISSUE THREAD

**Issue by MarkusMeskanen** [Source-Python-Dev-Team/Source.Python#81]
I'm not sure which patch broke it, but it used to work and apparently it doesn't do anything anymore. Tested only in CS:GO.

**Edit:** Setting it still works, but getting it will always return `Vector(0.0, 0.0, 0.0)`

**Comment by invincibleqc** [comment]
What if you set a Vector directly?

player.base_velocity = Vector(x, y, z)

**Comment by MarkusMeskanen** [comment]
Tested already, didn't work. :/

**Comment by Ayuto** [comment]
I don't have any issues using this test code.
```
from events import Event
from mathlib import Vector
from players.entity import Player
from players.helpers import index_from_userid

@Event('player_say')
def on_player_say(event):
    userid = event['userid']
    index = index_from_userid(userid)
    player = Player(index)
    player.base_velocity = Vector(0, 0, 300)
```

**Comment by MarkusMeskanen** [comment]
Sorry for the hazzle, Ayuto's code worked fine and the issue with my earlier `player.base_velocity = Vector(x, y, z)` test was that I was using too small values and the effect was unnoticeable.

However, there is an actual issue which caused the original problem: player's `base_velocity` seems to always equal to `Vector(0, 0, 0)`, regardless of how the player is moving. Using this code:

    @Event('player_jump')
    def player_jump(event):
        player = Player(index_from_userid(event['userid']))
        print(player.base_velocity)

I got the following results after running and jumping around:

    Vector(0.0, 0.0, 0.0)
    Vector(0.0, 0.0, 0.0)
    Vector(0.0, 0.0, 0.0)

The results are the same even with this code, by hitting a say bind right after jumping:

    @Event('player_jump')
    def player_jump(event):
        player = Player(index_from_userid(event['userid']))
        player.base_velocity = Vector(0, 0, 1000)

    @Event('player_say')
    def player_say(event):
        player = Player(index_from_userid(event['userid']))
        print(player.base_velocity)

The only time when I got `base_velocity` to be printed out as something other than `Vector(0, 0, 0)` was when I printed the velocity right after setting it in the same function:

    @Event('player_jump')
    def player_jump(event):
        player = Player(index_from_userid(event['userid']))
        player.base_velocity = Vector(0, 0, 1000)
        print(player.base_velocity)

**Comment by invincibleqc** [comment]
That's normal. That property only applies the value. If you want to read the actual play's velocity, you need to use the "velocity" property.

**Comment by Ayuto** [comment]
We should probably change that behaviour by renaming both attributes in the data files and create a velocity property that uses both correctly.

**Comment by invincibleqc** [comment]
Yeah, sounds like the way to go. However, I remember some entities not affected by base_velocity (projectiles, for example) and only move by calling the "teleport" method - just like Player.origin should wrap it. I will try to get an overall check on them later tonight.

**Comment by MarkusMeskanen** [comment]
Alright thanks guys, sorry for invalid issue!

After some googling, I found [this](https://forums.alliedmods.net/archive/index.php/t-210679.html) archive where someone mentions that `base_velocity` is the relative velocity to a moving train or something. I really don't know how all of this velocity stuff works, but I know for sure that this is very confusing:

   player.base_velocity = player.velocity * 2

So yeah, unless you find a good reason for this, I also vote for the `velocity` property that uses both of these property.
