### ISSUE TITLE
Inheritance for custom events

### ISSUE THREAD

**Issue by KirillMysnik** [Source-Python-Dev-Team/Source.Python#84]
Let's say you want to implement two similar custom events `player_death_fake` and `player_death_real`. Instead of defining the same exact variables two (or more) times, you could possibly do the following:

```python
class Custom_Player_Death_Base(CustomEvent):
    attacker = ShortVariable("The userid of the killer.")
    dominated = ShortVariable("True (1) if the kill caused the killer to be dominating the victim.")
    headshot = BoolVariable("True if the killshot was to the victim's head hitbox.")
    revenge = ShortVariable("True (1) if the victim was dominating the killer.")
    userid = ShortVariable("The userid of the victim.")
    weapon = StringVariable("The type of weapon used to kill the victim.")


class Player_Death_Fake(Custom_Player_Death_Base):
    pass


class Player_Death_Real(Custom_Player_Death_Base):
    pass
```

The issue is that Source.Python doesn't support this way of defining event variables. It only searches for variables defined inside of the class itself, not parent classes. In the example above both `player_death_fake` and `player_death_real` will turn out containing no variables in their .res-file.

Possible solution is to alter the metaclass for `CustomEvent` (`../events/custom.py`, line 45):
```python
...
    def __new__(mcs, name, bases, odict):
        """Called when the class is being created."""
        # Create the instance
        cls = super().__new__(mcs, name, bases, dict(odict))
        
        # Store an ordered dictionary
        cls._odict = OrderedDict()
        
        # We don't want to populate CustomEvent._odict with such entries as
        # 'fire', 'reset' and 'name'
        if not bases:
            return cls
        
        # Inherit dictionaries from parent classes
        for base in bases:
            cls._odict.update(base._odict)

...
```
Worth mentioning: current version of Source.Python also populates `CustomEvent._odict` with such entries as 'fire', 'reset' and 'name'. It's not critical becuse we actually never build .res-files upon `CustomEvent` itself, only upon its subclasses.
But once we decide to inherit parents' `._odict`'s, we don't want these extra names because they will raise later in `../events/resource.py`.
That's where these lines
```python
        if not bases:
            return cls
```
come from. If we're handling `CustomEvent` creation, the `bases` will be empty, because it doesn't inherit from anything.

Just an idea, because what else could inherintance be possibly useful for events for?

**Comment by satoon101** [comment]
Thank you for pointing this out.  I will work on a fix for this when I get the chance.

**Comment by satoon101** [comment]
Thanks again for mentioning this.  I used the following to test the new update:
```python
from events.custom import CustomEvent
from events.variable import BoolVariable
from events.variable import ShortVariable
from events.variable import StringVariable
from events.resource import ResourceFile


class Test_One(CustomEvent):
    userid = ShortVariable('The userid for the event.')


class Test_Two(Test_One):
    boolean = BoolVariable('Some boolean variable.')


class Test_Three(Test_One):
    pass


class Test_Four(Test_Two):
    weapon = StringVariable('Weapon used for event.')

resource = ResourceFile('test', Test_One, Test_Two, Test_Three, Test_Four)
resource.write()

print(hasattr(CustomEvent, '_odict'))
print(Test_One._odict)
print(Test_Two._odict)
print(Test_Three._odict)
print(Test_Four._odict)
```
