### ISSUE TITLE
[TF2] engine_server.is_map_valid always returns 0

### ISSUE THREAD

**Issue by jsza** [Source-Python-Dev-Team/Source.Python#85]
Since a few months back, `engine_server.is_map_valid` always returns `0` even if a map exists/is valid. It seems to have been deprecated in favor of `IVEngineServer::FindMap` judging from the changes in https://github.com/alliedmodders/hl2sdk/commit/f05f08ba9d62ccbbd44c84b01b44b0c8d5c79e9d.

Would it be feasible to expose this function and/or have some kind of wrapper function that can be used on all engines?

**Comment by Ayuto** [comment]
I just checked that method in CS:S and it's still working, altough it received the same update.

Example:
```
from engines.server import engine_server

print(engine_server.is_map_valid('maps/de_dust2.bsp'))
```

**Comment by jsza** [comment]
Oh... interesting, thanks. Prior to that update (at least on TF2), `is_map_valid('cp_dustbowl')` would return valid.

Writing it as `maps/cp_dustbowl.bsp` on TF2 does function correctly.

Assuming there are still any SP-supported engines with the old behaviour, should this be up to plugin authors to handle? Otherwise, this can probably be closed.

**Comment by Ayuto** [comment]
We will need to check the other games (CS:GO, L4D2 and BM:S). If they are working like the OrangeBox version, we probably don't need to update it.

**Comment by satoon101** [comment]
I just tested all of the currently supported servers.  It seems like CS:S, DOD:S, HL2:MP, and TF2 are working fine using the following as the test code:
```python
from engines.server import engine_server
from paths import GAME_PATH

for m in GAME_PATH.joinpath('maps').files('*.bsp'):
    print(engine_server.is_map_valid(m.replace(GAME_PATH, '')), m.namebase)
```


CS:GO, L4D2, and BM:S, however, automatically add the **maps/** and **.bsp** to the file when checking.  If I change the code to the following, those 3 games work fine:
```python
from engines.server import engine_server
from paths import GAME_PATH

for m in GAME_PATH.joinpath('maps').files('*.bsp'):
    print(engine_server.is_map_valid(m.namebase), m.namebase)
```

**Comment by Ayuto** [comment]
Thanks for testing! I have updated the method, so it will only require the map name without any file extensions or directories (e.g. just ``de_dust2``).

@jsza Plase test the new version and tell us if it's working for you.
