### ISSUE TITLE
players.weapons._PlayerWeapons is not completely updated

### ISSUE THREAD

**Issue by KirillMysnik** [Source-Python-Dev-Team/Source.Python#86]
The class is not completely updated to use new conversion functions. I'm talking about this update: http://forums.sourcepython.com/showthread.php?991-Updated-conversion-functions&p=6402&viewfull=1#post6402

Some parts of it still use outdated calls to these functions. Take a look at `get_weapon_color` and `set_weapon_color`:
```python
        # Get the weapon's BaseHandle instance
        index = index_from_inthandle(handle)

        # Was no index found?
        if index is None:

            # Raise an error
            raise ValueError(
                'No active weapon found for player "{0}"'.format(self.userid))
```
If the active weapon is already dropped and there're no more valid weapons on player, `index_from_inthandle` will raise an exception. It won't return `None`.
As a result, instead of getting
`ValueError: No active weapon found for player "2"`
we will get
`ValueError: Unable to get an index from the given IntHandle (-1)`

The comment is also misleading. We're getting an index there, not BaseHandle instance.

**Comment by satoon101** [comment]
This will not matter in future versions.  We have already begun work on updating player weapon functionality in a new branch:
https://github.com/Source-Python-Dev-Team/Source.Python/tree/player_weapons_update

In that branch, we have removed all weapon functionality from the Player class itself and now it should be used to get the weapon's Weapon instance instead.  Then, getting/setting the color will be up to the Weapon class itself.

That being said, the new branch does need updating to not raise an error in Player.active_weapon.

**Comment by KirillMysnik** [comment]
I see. Sorry for the invalid ticket.

**Comment by Ayuto** [comment]
Since we have no ETA when the branch gets merged, we should fix it for now on the master.
