### ISSUE TITLE
Unable to override __setattr__ in Entity subclasses

### ISSUE THREAD

**Issue by Mahi** [Source-Python-Dev-Team/Source.Python#89]
In `players.entity` package, [this line](https://github.com/Source-Python-Dev-Team/Source.Python/blob/7fd47410b0bb6db61e27715e07bc85fa8cb39626/addons/source-python/packages/source-python/players/entity.py#L73) assigns to `self._playerinfo` (thus calling `__setattr__`) and prevents me from implementing a custom `__setattr__` like this:

    def __setattr__(self, attr, value):
        if attr in super().__dir__():
            super().__setattr__(attr, value)
        else:
            print('Setting a new attribute', attr, 'my way!')

Your `__dir__` method uses `self.playerinfo`, which assigns to `self._playerinfo`, which calls my custom `__setattr__`, which again calls your `__dir__`, etc...

So two quick solutions I came up with:

 1. Inside your `playerinfo` property, explicitly use a different `__setattr__`, possibly from `object` or `super()`?
 2. Set the `_playerinfo` outside of the property and have the `playerinfo` property only return a value (don't know if possible)

Or maybe there's something I'm doing wrong?

**Comment by satoon101** [comment]
You probably should specify the Entity class in you super call, much like this line:
https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/players/entity.py#L67

**Comment by Mahi** [comment]
I'm not sure I follow here, that's only required in Python 2 and is unrelated to my issue... Besides, even if it worked, it would be just a workaround, not a fix.

Since it's as easy as:

    playerinfo = playerinfo_from_index(self.index)
    object.__setattr__(self, '_playerinfo', playerinfo)

Shouldn't each class take care of its own attributes instead of messing the extendability of the class? Currently there's no proper way of having a custom `__setattr__` method in a subclass of `Player`, since that will prevent `__dir__` from being called.

**Comment by satoon101** [comment]
That line isn't in the Entity class, it is in the Player sub-class.  So yes, it is related.

**Comment by Mahi** [comment]
Oh that was stupid from me, I thought you meant that I should do:

    super(Entity, self).__setattr__(attr, value)

When you obviously meant:

    if attr in super(Entity, self).__dir__():

But still, isn't this just a quick workaround, not a fix? Is there any reason not to use the `object.__setattr__` like I proposed?

**Comment by Mahi** [comment]
Also, `'speed' in super(Entity, self).__dir__()` returns `False`, so this will completely ignore some of `Player`'s attributes.

**Comment by satoon101** [comment]
Would you mind issuing a pull request that ises super in each case?  Make sure to specify Entity in the Player class instance.  Thank you.

**Comment by Mahi** [comment]
[Done.](https://github.com/Mahi/Source.Python/commit/18f01f1501b671ae9d304e40a793c1a4fc16cd20) Though I'm not sure how you guys want your code since in some places you use `super(cls, self)` and in others you only have `super()`, but I ended up using `super(cls, self)`.

> Make sure to specify Entity in the Player class instance.

Not sure what you mean by this, I used `super(Player, self)` and it worked just fine after 10-15 minutes of testing it with different methods, attributes, and subclasses. As long as it's not `Player`'s children whose `__setattr__` gets called, everything should be fine.

**Comment by satoon101** [comment]
Ah, I see why that works, but technically, we should remove lines 93-107 of Entity.__setattr__ and specify Entity in the _playerinfo setattr, which bypasses Entity.__setattr__ and just sets the values to the instance without all that nonsense that we have used as a workaround.

And, we only specify the arguments of super() if they differ from the hosting class.  As far as I know, Player's setting of _playerinfo specifying Entity is the only instance currently in the code.

**Comment by Mahi** [comment]
In that case, wouldn't it be best to just use `object.__setattr__()` directly? That'd skip absolutely everything extra, and just set the attribute.

> And, we only specify the arguments of super() if they differ from the hosting class. As far as I know, Player's setting of _playerinfo specifying Entity is the only instance currently in the code.

For some reason I always thought you used `super(cls, self)` almost everywhere, but now that you mentioned, it seems like `super()` is used everywhere. That's nice!

**Comment by Ayuto** [comment]
Fixed with PR #90
