### ISSUE TITLE
Add Activate function to CBaseEntity

### ISSUE THREAD

**Issue by KirillMysnik** [Source-Python-Dev-Team/Source.Python#93]
As defined at https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/baseentity.cpp#L1311

This function proved useful to activate `info_particle_system`'s, because if you spawn and set particle system up without activating it in the end, the particles won't appear.

I use this virtual function in CBaseEntity.ini
```ini
    # _ZN14CBaseAnimating8ActivateEv
    [[activate]]
        offset_linux = 34
        offset_windows = 33
```
That's correct for Counter-Strike: Source.

I'm not sure how to use your virtuals extractor to get windows offests, I just tried to set `offset_windows` to `offset_linux - 1` and it worked on Windows. So I can't really provide correct offset for other games.

**Comment by invincibleqc** [comment]
Actually, you could also set the m_iEffectIndex manually to activate the particles. Example (outdated): http://forums.sourcepython.com/showthread.php?515

**Comment by KirillMysnik** [comment]
Thanks, didn't know about that.
