### ISSUE TITLE
Add .expired property/attribute to the Delay class

### ISSUE THREAD

**Issue by KirillMysnik** [Source-Python-Dev-Team/Source.Python#95]
Hey there again.

Although this issue might turn out to be negligible, there is still possible improvement in terms of simply raising a much friendlier exception.

# Research
So. Let's take a look at [`listeners.tick._TickDelays`](https://github.com/Source-Python-Dev-Team/Source.Python/blob/8b2ac092dcb301c3c8dc63fb6da7266c12505ee8/addons/source-python/packages/source-python/listeners/tick.py#L104) - it inherits from `dict` and implements some kind of an ordered dict functionality when we iterate over it.

It registers its own tick listener `_tick`. In `_tick` it simply removes all delays that are expired or expire right now (lines 190 - 199):
```python
        for item in self:

            # Should the delays be called?
            if item > current_time:

                # If not, no need to continue looping
                break

            # Remove the item from the dictionary
            del self[item]
```
Upon removal the item gets called, as can be seen in `__delitem__` (line 165), and then finally removed from both the `_order` list (that list helps us stay ordered when iterated) and the actual dict (lines 168-171):
```python
        # Call all delays for the given item
        self[item].call_delays()

        # Remove the item from the ordered list
        self._order.remove(item)

        # Remove the item from the dictionary
        super().__delitem__(item)
```

`item` here is just a container for the actual callbacks and its `call_delays` method just redirects the call to all of them.

# Issue
Now to the issue - I'll try to make it look as legit as possible. Say we want to have a delayed callback with a functionality that can possibly be issued before the delay expires.
```python
def delayed_callback():
    print("Do something useful")
```
But if we want to use this functionality before the delay expires, we need to cancel the delay itself, so the functionality won't be executed 2 times - manually and by delay.

One naive coder could come up with only one callback:
```python
def delayed_callback():       # This is a delayed callback, but can also be called manually
    delay.cancel()
    print("Do something useful")

delay = tick_delays.delay(10, delay_callback)
```
instead of splitting it:
```python
def delayed_callback():       # This should only be called by expiring delay
    print("Do something useful")

def call_prematurely():     # This should only be called manually
    delay.cancel()
    delayed_callback()

delay = tick_delays.delay(10, delay_callback)
```

The reasoning behind this is "if it's not expired yet, we cancel it, but if this call is actually issued by expired delay - cancelling it won't do anything bad, right". How about no?
```
[SP] Caught an Exception: 
Traceback (most recent call last): 
  File '..\addons\source-python\packages\source-python\listeners\tick.py', line 199, in _tick 
    del self[item] 
  File '..\addons\source-python\packages\source-python\listeners\tick.py', line 168, in __delitem__ 
    self._order.remove(item) 
 
ValueError: list.remove(x): x not in list 
 ```
**The problem with this exception is that it's hard to tell where it comes from. It does not even provide a plugin name!**
Now where it comes from (`__delitem__`):
```python
        # Call all delays for the given item
        self[item].call_delays()

        # Remove the item from the ordered list
        self._order.remove(item)
```
You can assume that if we made our way to `__delitem__`, the item just has to be in `self._order` list, because there's no other place the item can be removed from this list. But what if one of the callbacks in `.call_delays` decided to cancel itself? In that case we're getting into the `cancel_delay` at line 235:

```python
# Remove the delay from its time (from its container with .call_delays method)
self[delay_object._exec_time].remove(delay_object)
```
Then we have 2 cases:
- if there're other callbacks that are executed at the same time (not interesting)
- if our callback was the only one (our case).

Guess what it does in the latter case? It deletes the container:
```python
    del self[delay_object._exec_time]
````
And we're getting into `__delitem__`. Again! There `.call_delays` doesn't make any sense because we already removed the last remaining callback from the container. But there's still one fatal thing we do here:
```python
self._order.remove(item)
super().__delitem__(item)
```

Then we dive out of this `__delitem__` back to our `delayed_callback` where we successfully execute `print("Do something useful")`. Then we dive out back to initial `__delitem__` which tries to remove the container from `._order` list and from the dict and raises this absolutely uninformative exception.

# What do I propose?
Add `called` or `expired` property to the `Delay` class. And make it `True` right before the callback is called:
```python
    def call_delays(self):
        """Call the delays in the list."""
        # Loop through the delays in the list
        for item in self:

            # Mark the delay as expired
            item.expired = True

            # Call the delay
            item()
```

Then, in `_TickDelays.cancel_delay` the first thing to do is to check if the delay is expired. If it is, then raise an exception or just return.

Benefits:
1. No more exceptions that come out of nowhere
2. Our multi-functional `delayed_callback` can be written this way:
```python
def delayed_callback():       # This is a delayed callback, but can also be called manually
    if not delay.expired:
        delay.cancel()
    
    print("Do something useful")
```
In fact, there's one more thing to it: I have a clean-up code that just tries to undo everything done by some other processes. Including canceling all delays. At the moment I do:
```python
for delay in _delays:
    try:
        delay.cancel()
    except KeyError:
        pass

_delays.clear()
```
It's just brute force.
Other way of doing it at the moment is to remove the delay from `_delays` when it's called. That's 1 additional line of code to all of the delayed callbacks. Or is it just one line?
```python
_delays = []
_delays.append(tick_delays.delay(10, my_entity.kill))
```
turns into
```python
_delays = {}
def my_callback():
    del _delays['kill-my-entity']
    my_entity.kill()

_delays['kill-my-entity'] = tick_delays.delay(10, my_callback)
```

With the `.expired` property I could do such a simple clean-up:
```python
for delay in _delays:
    if not delay.expired:
        delay.cancel()

_delays.clear()
```

Thank you all for reading all this.

**Comment by KirillMysnik** [comment]
Setting `.expired` attribute/property might also be done in the `Delay` itself, in its `__call__`:
```python
# Mark this delay as expired
self.expired = True

# Use try/except in case an error is encountered
try:

    # Execute the callback with the arguments and keywords
    self.callback(*self.args, **self.kwargs)

...
```

**Comment by Mahi** [comment]
> **The problem with this exception is that it's hard to tell where it comes from. It does not even provide a plugin name!**

I completely agree that this is a vague error, but I'm not sure I agree with your solution. In my opinion, every plugin should handle its own resources, including its delays without overlapping `cancel()`s. On those rare cases where overlapping `cancel()`s may appear (such as `cancel()` happening on an event), one can just use `try`/`except`.

However, I would love to see a custom exception which gets raised when `cancel()` is called on an already expired delay.

**Comment by KirillMysnik** [comment]
> I would love to see a custom exception which gets raised when cancel() is called on an already expired delay.

Well, even that way internally there must be a way to determine if the callback is expired, right? Calling time.time() and comparing it to the delay's `_exec_time` is not that reliable in my eyes. We can be in the same tick but we can't know for sure if we are called before the delayed callback or later.

**Comment by KirillMysnik** [comment]
Delayed callback should also be considered expired if it was cancelled.

Also, this neat exception on line 228
```python
raise KeyError('Object is no longer registered.')
```
only gets raised if we're trying to cancel already cancelled/expired callback __and__ there're no other callbacks registered to the same exact time. If there're other callbacks registered to the same exact `._exec_time`, we will get an unhandled exception literally in the next 2 lines:
```python
self[delay_object._exec_time].remove(delay_object)
```
But this time it will be a `ValueError`. A bit of inconsistency for those who want to catch these exceptions, because he actually needs to be ready to except both `KeyError` raised manually and `ValueError` that gets raised by interpreter.

**Comment by Ayuto** [comment]
I have created a new branch to address this issue:
https://github.com/Source-Python-Dev-Team/Source.Python/tree/delays_update

To create a delay you now need to call the Delay constructor directly. The Delay class now also inherits from AutoUnload, so all running delays will be cancelled now if a plugin is unloaded.

You can also call the delay to cancel the delay and immediately call the callback.

Is there anything left?

**Comment by KirillMysnik** [comment]
I like your branch. I felt uncomfortable with calling callbacks in their deletion code and the old Delay class which stored all callbacks that should be fired at the given time. Now it's all clear.

`python
self.pop(0).execute()
`
I guess this line solved the issue. Delay is removed from the list before it's called.

Although I haven't tried your branch on out on my code, I guess there's nothing that can be added.

**Comment by satoon101** [comment]
I really like this implementation, too.  I have not had a chance to test it, yet, with the holidays.  I hope to have time tonight or tomorrow night to do so.

**Comment by satoon101** [comment]
Having tested, it seems everything is well accounted for.  The only 2 (minor) changes I would recommend are changing the __add__ method to __append__ (since _delay_manager is a list object and should never really be used outside of the module itself) and changing the __try/except/pass__ in _unload_instance to instead just use contextlib.suppress.

**Comment by Ayuto** [comment]
I didn't choose append, because I think it means adding something to the end, which we don't do.

I'm not a big fan of contextlib.suppress(), because it actually requires you to write more code and doesn't make your code cleaner (imo). try/except/pass seems to be quite clean already. But I'm fine with adding it.

**Comment by Mahi** [comment]
> I didn't choose append, because I think it means adding something to the end, which we don't do.

Is there a reason to use `list` and `bisect.insort_left` instead of just using `deque` with `append_left`?

> I'm not a big fan of contextlib.suppress(), because it actually requires you to write more code and doesn't make your code cleaner (imo).

I personally think it's cleaner, but that's quite obviously just opinion based. But what do you mean it requires you two rite more code? To me it seems like you removed three lines of code and added only one (or two if you count the import statement): https://github.com/Source-Python-Dev-Team/Source.Python/commit/e7cea45ce8273e00be63043a2eb9349e68ac9040

**Comment by Ayuto** [comment]
> Is there a reason to use list and bisect.insort_left instead of just using deque with its append_left?

Yes, the result is not the same. append_left adds it to the beginning of the deque. insort_left adds it to the left and keeps the order of the list!

> I personally think it's much cleaner, but that's quite obviously just opinion based. But what do you mean it requires you two write more code? To me it seems like you removed three lines of code and added only one (or two if you count the import statement): e7cea45

Counting characters try/except/pass wins. And since it doesn't make the code cleaner (imo) why should I use something different than the built-ins?

**Comment by Ayuto** [comment]
I have merged the branch with the master. https://github.com/Source-Python-Dev-Team/Source.Python/commit/0310106ccde9a69ca4776b677fead236894103d3
