### ISSUE TITLE
Server crash after new revolver update

### ISSUE THREAD

**Issue by Mahi** [Source-Python-Dev-Team/Source.Python#96]
Console output right before the crash:

    [Source.Python] Loading...
    Missing shutdown function for sv.Init( bDedicated ) : sv.Shutdown()

Tested on Windows 7 with CS:GO dedicated server

**Comment by satoon101** [comment]
Do you have __+developer 1__ in your command line?  Just checking to see if SP gets any further in the loading process by the time the crash occurs.

**Comment by Mahi** [comment]
Using `+developer 1` has no effect on the console output.

**Comment by Ayuto** [comment]
The crash should be fixed with this commit:
https://github.com/Source-Python-Dev-Team/Source.Python/commit/e6091c49fb76f19795c0efaa92f4092c6c1a094e

We might need to update data files as well.

**Comment by satoon101** [comment]
I haven't tested anything until today, but I am crashing on CS:GO only right now.  With `+developer 1`, I can see that it crashes right after the `Setting sys.argv` message.  I added DevMsg's to all of the lines following that, and found that nothing prints after the following line is executed:
```cpp
	int iParamCount = pCommandLine->ParmCount();
```

This is on Windows, have not tested Linux, yet.

**Comment by satoon101** [comment]
Ahh, nevermind me, for some reason git isn't a recognized command after I updated to Windows 10.  I will get this fixed on my end.  Sorry.
