### ISSUE TITLE
<Sound object>.duration always returns 0

### ISSUE THREAD

**Issue by Ayuto** [Source-Python-Dev-Team/Source.Python#97]
Reference:
http://forums.sourcepython.com/showthread.php?940-Plugins-converts-from-Eventscripts-to-Source-Python&p=6441&viewfull=1#post6441

A possible solution is to add a sound library like [mutagen](https://mutagen.readthedocs.org/en/latest/). This would allow us to add more attributes to the Sound class.

Question:
What do we do with sound files packed in VPK files? Actually, this is not just about sound files, but any file within a VPK file. What if we want to call a function that requires a file path? Should we create a temporary file?

**Comment by KirillMysnik** [comment]
Real-time VPK unpacking?

How about manually hashing all stock game VPKs and just creating corresponding tables to them which contain information like
<sound path> - duration
?

And if the server uses a custom VPK - well, then unpack VPK either in real time on request (slow?) or unpack and create such tables on server startup.

**Comment by Ayuto** [comment]
Actually, reading a file from a VPK file seems to be fast and it's probably much faster if we create the file-like object with the functionality provided by the SDK (because it's implemented in C++). If someone needs a name on the file system, we could provide a named temporary file (there is a Python library for that).

I don't want a hash table, because that only fixes the duration issue and not accessing packed files.

**Comment by dsezen** [comment]
No need for special libraries. IEngineTool contains exactly what you need ;)

**Comment by satoon101** [comment]
This should all be fixed as of this commit:
https://github.com/Source-Python-Dev-Team/Source.Python/commit/bc4b1ded4110d8d105a36f81721686b204510b5b

**Comment by Ayuto** [comment]
The reason for reopening this issue is that the interface is not available on Linux.

**Comment by Killer0561** [comment]
If this interface for Linux ever be available? This topic is now long open without a solution, unfortunately.

**Comment by satoon101** [comment]
@Killer0561 - That interface will never be available for Linux (or at least very highly unlikely).  We are working on a solution.  The most recent commit should allow access to the duration for all wav, mp3, and ogg files that are directly on the server.  We still have to figure out how we want to get the duration for sounds in vpk files.

**Comment by satoon101** [comment]
The newest solution seems to work fine, but I would like more people to do more testing on it to verify.  It now allows for getting the sound duration from sounds within vpk files.  My test script on CS:S was:
```python
from engines.sound import Sound
from stringtables import string_tables

sounds = [
    'hostage/hpain/hpain1.wav',
    'player/headshot1.wav',
    'guita17.wav',
    'source-python/gungame/default/gg_handicap.mp3',
    'source-python/gungame/default/smb_star.mp3',
]

from time import time
start = time()
for path in sounds:
    sound = Sound(path)
    sound.precache()
    print(path, sound.duration, string_tables.soundprecache[sound.sample])
minutes, seconds = divmod(time() - start, 60)
print(
    'Total time: {minutes} minute(s), {seconds:.2f} seconds'.format(
        minutes=int(minutes),
        seconds=seconds,
    )
)
```

**Comment by Killer0561** [comment]
Thanks, I'll try it later.
- Killer0561

**Comment by satoon101** [comment]
Slight update.  I went ahead and added a dictionary to store the duration for each sound so that we only have to look it up once:
b7cff47

The only issue here is that if you update a sound whose duration has already been retrieved and stored, you will have to restart the server to get the updated sound's duration properly.

**Comment by satoon101** [comment]
Should we go ahead and merge this branch, too?  I don't think it will hurt anything to do so.

I do have a few minor questions.  First, will all .vpk files always be in the root game directories (and the hl2 directory, as well).  Can they be in other very specific places, as well?  Or, can they be anywhere and everywhere on the server?  If the last one, then we'll have to leave the walkfiles as-is.  Otherwise, we can shorten up the time it takes to parse all vpk files by only looking for files in those specific areas.

Also, will all primary vpk files always end in _dir.vpk?  I know the ones that come with the servers all do, but I'm not sure if user created ones do.  Currently the code assumes the answer to this is 'yes'.

**Comment by KirillMysnik** [comment]
@satoon101 
What about `gameinfo.txt`? It contains exact paths to the vpk dirs.

**Comment by Ayuto** [comment]
I started working on a SourceFile class today that utilizes the built-in filesystem. If that is working fine, we don't need the VPK library and don't need to care about the VPK file names.

**Comment by Ayuto** [comment]
Just added the base: https://github.com/Source-Python-Dev-Team/Source.Python/commit/ac6d8e6fbbdf3796284ba60329af73c4c9aa7c8a

I haven't finished the SourceFile class, but with the ``source_file`` context manager, we can fix this issue and remove that VPK library.

**Comment by Ayuto** [comment]
Just saw that the latest version of mutagen now supports file-like objects. So, when the SourceFile class is finished, we don't even need to copy the file anymore.

**Comment by Ayuto** [comment]
Thanks for updating mutagen! 

I have updated the Sound class to use the SourceFile class and I think this issue is finally fixed! :D
https://github.com/Source-Python-Dev-Team/Source.Python/commit/475bcac1556690b69e2946c96dd2519e62172e0d

**Comment by satoon101** [comment]
As far as I know, mutagen does not work with .wav files and the wave package does not seem to support file-like objects.  So, this is currently broken for .wav files.  I'm getting an EOFError with my testing.  I'm still using the same test script as [above](https://github.com/Source-Python-Dev-Team/Source.Python/issues/97#issuecomment-233191821).

Also, for my tests, not every file is properly recognized by mutagen.File.  I'm not sure why that is, and need to test further.  The gg_handicap.mp3 works fine, but the smb_star.mp3 returns None.  I have currently only tested with CS:S.  Both .wav files are in vpks and both .mp3 files are not.  I don't know of any .mp3 files that are in vpks to even be able to test with, unfortunately, but I have also added a .wav file to my servers to test them outside of a vpk.

**Comment by Ayuto** [comment]
> [...] the wave package does not seem to support file-like objects. So, this is currently broken for .wav files. I'm getting an EOFError with my testing.

It's working fine for me and the wave module does support file-like objects:
https://github.com/python/cpython/blob/master/Lib/wave.py#L7-L8

>  I don't know of any .mp3 files that are in vpks to even be able to test with, unfortunately, but I have also added a .wav file to my servers to test them outside of a vpk.

Yeah, I didn't found an mp3 file neither.

**Comment by satoon101** [comment]
Sorry, the error was my fault.  I had added a line to print mutagen.File(f) prior to the extension check, and that is what caused the error.  Removing that, it works properly.  I did test with a .wav file directly on the server, and it works, too.

I will test further to see if I can figure out why some of the mutagen.File objects are returning None, but the current implementation should suffice for now.

**Comment by Ayuto** [comment]
Okay, I have merged the sound_duration branch: https://github.com/Source-Python-Dev-Team/Source.Python/commit/daf06d0532b2be2a2a57b292e18364baec988c10#diff-2f8de5e897a7ac08563e71603ce036b1

I will also close this issue as the mutagen.File enhancement is not directly related to this issue.
