### ISSUE TITLE
WeaponInfo structure differs in CS:GO

### ISSUE THREAD

**Issue by Ayuto** [Source-Python-Dev-Team/Source.Python#98]
This structure isn't valid (anymore?) in CS:GO:
https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/data/source-python/weapons/scripts/WeaponInfo.ini

If you dump all weapon info instances, you will get an error due to accessing wrong memory locations.
```
sp dump weapon_scripts weapon_scripts
```

**Comment by invincibleqc** [comment]
While this doesn't add CS:GO specific attributes, commit https://github.com/Source-Python-Dev-Team/Source.Python/commit/973575763aea458291a9665819bd6f6c45e38529 _technically_ fix this issue.
